package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatCondicionCultivo generated by hbm2java
 */
@Entity
@Table(name="Cat_Condicion_Cultivo"
    ,catalog="sisem"
)
public class CatCondicionCultivo  implements java.io.Serializable {


     private Integer idCondicionCultivo;
     private DatUsuario datUsuarioByIdUsuarioCreacion;
     private DatUsuario datUsuarioByIdUsuarioEdicion;
     private String nombreCondicionCultivo;
     private boolean status;
     private Date fechaCreacion;
     private Date fechaEdicion;
     private Set<DatR1Inspeccion> datR1Inspeccions = new HashSet<DatR1Inspeccion>(0);

    public CatCondicionCultivo() {
    }

	
    public CatCondicionCultivo(DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, String nombreCondicionCultivo, boolean status, Date fechaCreacion, Date fechaEdicion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
        this.nombreCondicionCultivo = nombreCondicionCultivo;
        this.status = status;
        this.fechaCreacion = fechaCreacion;
        this.fechaEdicion = fechaEdicion;
    }
    public CatCondicionCultivo(DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, String nombreCondicionCultivo, boolean status, Date fechaCreacion, Date fechaEdicion, Set<DatR1Inspeccion> datR1Inspeccions) {
       this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
       this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
       this.nombreCondicionCultivo = nombreCondicionCultivo;
       this.status = status;
       this.fechaCreacion = fechaCreacion;
       this.fechaEdicion = fechaEdicion;
       this.datR1Inspeccions = datR1Inspeccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Condicion_Cultivo", unique=true, nullable=false)
    public Integer getIdCondicionCultivo() {
        return this.idCondicionCultivo;
    }
    
    public void setIdCondicionCultivo(Integer idCondicionCultivo) {
        this.idCondicionCultivo = idCondicionCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioCreacion() {
        return this.datUsuarioByIdUsuarioCreacion;
    }
    
    public void setDatUsuarioByIdUsuarioCreacion(DatUsuario datUsuarioByIdUsuarioCreacion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Edicion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioEdicion() {
        return this.datUsuarioByIdUsuarioEdicion;
    }
    
    public void setDatUsuarioByIdUsuarioEdicion(DatUsuario datUsuarioByIdUsuarioEdicion) {
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
    }

    
    @Column(name="Nombre_Condicion_cultivo", nullable=false, length=45)
    public String getNombreCondicionCultivo() {
        return this.nombreCondicionCultivo;
    }
    
    public void setNombreCondicionCultivo(String nombreCondicionCultivo) {
        this.nombreCondicionCultivo = nombreCondicionCultivo;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Edicion", nullable=false, length=19)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCondicionCultivo")
    public Set<DatR1Inspeccion> getDatR1Inspeccions() {
        return this.datR1Inspeccions;
    }
    
    public void setDatR1Inspeccions(Set<DatR1Inspeccion> datR1Inspeccions) {
        this.datR1Inspeccions = datR1Inspeccions;
    }




}


