package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatColonia generated by hbm2java
 */
@Entity
@Table(name="Cat_Colonia"
    ,catalog="sisem"
)
public class CatColonia  implements java.io.Serializable {


     private Integer idColonia;
     private CatMunicipio catMunicipio;
     private int claveColonia;
     private String nombreColonia;
     private String codigoPostal;
     private boolean status;
     private Set<DatDomicilioFiscal> datDomicilioFiscals = new HashSet<DatDomicilioFiscal>(0);
     private Set<DatR1Predio> datR1Predios = new HashSet<DatR1Predio>(0);
     private Set<CatUnidadSnics> catUnidadSnicses = new HashSet<CatUnidadSnics>(0);
     private Set<DatAlmacenBeneficio> datAlmacenBeneficios = new HashSet<DatAlmacenBeneficio>(0);
     private Set<DatR4Direccion> datR4Direccions = new HashSet<DatR4Direccion>(0);

    public CatColonia() {
    }

	
    public CatColonia(CatMunicipio catMunicipio, int claveColonia, String nombreColonia, String codigoPostal, boolean status) {
        this.catMunicipio = catMunicipio;
        this.claveColonia = claveColonia;
        this.nombreColonia = nombreColonia;
        this.codigoPostal = codigoPostal;
        this.status = status;
    }
    public CatColonia(CatMunicipio catMunicipio, int claveColonia, String nombreColonia, String codigoPostal, boolean status, Set<DatDomicilioFiscal> datDomicilioFiscals, Set<DatR1Predio> datR1Predios, Set<CatUnidadSnics> catUnidadSnicses, Set<DatAlmacenBeneficio> datAlmacenBeneficios, Set<DatR4Direccion> datR4Direccions) {
       this.catMunicipio = catMunicipio;
       this.claveColonia = claveColonia;
       this.nombreColonia = nombreColonia;
       this.codigoPostal = codigoPostal;
       this.status = status;
       this.datDomicilioFiscals = datDomicilioFiscals;
       this.datR1Predios = datR1Predios;
       this.catUnidadSnicses = catUnidadSnicses;
       this.datAlmacenBeneficios = datAlmacenBeneficios;
       this.datR4Direccions = datR4Direccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Colonia", unique=true, nullable=false)
    public Integer getIdColonia() {
        return this.idColonia;
    }
    
    public void setIdColonia(Integer idColonia) {
        this.idColonia = idColonia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

    
    @Column(name="Clave_colonia", nullable=false)
    public int getClaveColonia() {
        return this.claveColonia;
    }
    
    public void setClaveColonia(int claveColonia) {
        this.claveColonia = claveColonia;
    }

    
    @Column(name="Nombre_Colonia", nullable=false, length=100)
    public String getNombreColonia() {
        return this.nombreColonia;
    }
    
    public void setNombreColonia(String nombreColonia) {
        this.nombreColonia = nombreColonia;
    }

    
    @Column(name="Codigo_Postal", nullable=false, length=10)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catColonia")
    public Set<DatDomicilioFiscal> getDatDomicilioFiscals() {
        return this.datDomicilioFiscals;
    }
    
    public void setDatDomicilioFiscals(Set<DatDomicilioFiscal> datDomicilioFiscals) {
        this.datDomicilioFiscals = datDomicilioFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catColonia")
    public Set<DatR1Predio> getDatR1Predios() {
        return this.datR1Predios;
    }
    
    public void setDatR1Predios(Set<DatR1Predio> datR1Predios) {
        this.datR1Predios = datR1Predios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catColonia")
    public Set<CatUnidadSnics> getCatUnidadSnicses() {
        return this.catUnidadSnicses;
    }
    
    public void setCatUnidadSnicses(Set<CatUnidadSnics> catUnidadSnicses) {
        this.catUnidadSnicses = catUnidadSnicses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catColonia")
    public Set<DatAlmacenBeneficio> getDatAlmacenBeneficios() {
        return this.datAlmacenBeneficios;
    }
    
    public void setDatAlmacenBeneficios(Set<DatAlmacenBeneficio> datAlmacenBeneficios) {
        this.datAlmacenBeneficios = datAlmacenBeneficios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catColonia")
    public Set<DatR4Direccion> getDatR4Direccions() {
        return this.datR4Direccions;
    }
    
    public void setDatR4Direccions(Set<DatR4Direccion> datR4Direccions) {
        this.datR4Direccions = datR4Direccions;
    }




}


