package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatCicloAgricola generated by hbm2java
 */
@Entity
@Table(name="Cat_Ciclo_Agricola"
    ,catalog="sisem"
)
public class CatCicloAgricola  implements java.io.Serializable {


     private Integer idCicloAgricola;
     private DatUsuario datUsuarioByIdUsuarioCreacion;
     private DatUsuario datUsuarioByIdUsuarioEdicion;
     private String nombreCicloAgricola;
     private boolean status;
     private Date fechaCreacion;
     private Date fechaEdicion;
     private Set<DatR7Inspeccion> datR7Inspeccions = new HashSet<DatR7Inspeccion>(0);
     private Set<DatR1Cabecera> datR1CabecerasForIdCicloAgricolaProduccion = new HashSet<DatR1Cabecera>(0);
     private Set<DatR1Cabecera> datR1CabecerasForIdCicloAgricolaOrigen = new HashSet<DatR1Cabecera>(0);
     private Set<DatR5Ciclo> datR5Ciclos = new HashSet<DatR5Ciclo>(0);

    public CatCicloAgricola() {
    }

	
    public CatCicloAgricola(DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, String nombreCicloAgricola, boolean status, Date fechaCreacion, Date fechaEdicion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
        this.nombreCicloAgricola = nombreCicloAgricola;
        this.status = status;
        this.fechaCreacion = fechaCreacion;
        this.fechaEdicion = fechaEdicion;
    }
    public CatCicloAgricola(DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, String nombreCicloAgricola, boolean status, Date fechaCreacion, Date fechaEdicion, Set<DatR7Inspeccion> datR7Inspeccions, Set<DatR1Cabecera> datR1CabecerasForIdCicloAgricolaProduccion, Set<DatR1Cabecera> datR1CabecerasForIdCicloAgricolaOrigen, Set<DatR5Ciclo> datR5Ciclos) {
       this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
       this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
       this.nombreCicloAgricola = nombreCicloAgricola;
       this.status = status;
       this.fechaCreacion = fechaCreacion;
       this.fechaEdicion = fechaEdicion;
       this.datR7Inspeccions = datR7Inspeccions;
       this.datR1CabecerasForIdCicloAgricolaProduccion = datR1CabecerasForIdCicloAgricolaProduccion;
       this.datR1CabecerasForIdCicloAgricolaOrigen = datR1CabecerasForIdCicloAgricolaOrigen;
       this.datR5Ciclos = datR5Ciclos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Ciclo_Agricola", unique=true, nullable=false)
    public Integer getIdCicloAgricola() {
        return this.idCicloAgricola;
    }
    
    public void setIdCicloAgricola(Integer idCicloAgricola) {
        this.idCicloAgricola = idCicloAgricola;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioCreacion() {
        return this.datUsuarioByIdUsuarioCreacion;
    }
    
    public void setDatUsuarioByIdUsuarioCreacion(DatUsuario datUsuarioByIdUsuarioCreacion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Edicion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioEdicion() {
        return this.datUsuarioByIdUsuarioEdicion;
    }
    
    public void setDatUsuarioByIdUsuarioEdicion(DatUsuario datUsuarioByIdUsuarioEdicion) {
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
    }

    
    @Column(name="Nombre_Ciclo_Agricola", nullable=false, length=45)
    public String getNombreCicloAgricola() {
        return this.nombreCicloAgricola;
    }
    
    public void setNombreCicloAgricola(String nombreCicloAgricola) {
        this.nombreCicloAgricola = nombreCicloAgricola;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Edicion", nullable=false, length=19)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCicloAgricola")
    public Set<DatR7Inspeccion> getDatR7Inspeccions() {
        return this.datR7Inspeccions;
    }
    
    public void setDatR7Inspeccions(Set<DatR7Inspeccion> datR7Inspeccions) {
        this.datR7Inspeccions = datR7Inspeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCicloAgricolaByIdCicloAgricolaProduccion")
    public Set<DatR1Cabecera> getDatR1CabecerasForIdCicloAgricolaProduccion() {
        return this.datR1CabecerasForIdCicloAgricolaProduccion;
    }
    
    public void setDatR1CabecerasForIdCicloAgricolaProduccion(Set<DatR1Cabecera> datR1CabecerasForIdCicloAgricolaProduccion) {
        this.datR1CabecerasForIdCicloAgricolaProduccion = datR1CabecerasForIdCicloAgricolaProduccion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCicloAgricolaByIdCicloAgricolaOrigen")
    public Set<DatR1Cabecera> getDatR1CabecerasForIdCicloAgricolaOrigen() {
        return this.datR1CabecerasForIdCicloAgricolaOrigen;
    }
    
    public void setDatR1CabecerasForIdCicloAgricolaOrigen(Set<DatR1Cabecera> datR1CabecerasForIdCicloAgricolaOrigen) {
        this.datR1CabecerasForIdCicloAgricolaOrigen = datR1CabecerasForIdCicloAgricolaOrigen;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCicloAgricola")
    public Set<DatR5Ciclo> getDatR5Ciclos() {
        return this.datR5Ciclos;
    }
    
    public void setDatR5Ciclos(Set<DatR5Ciclo> datR5Ciclos) {
        this.datR5Ciclos = datR5Ciclos;
    }




}


