package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatCultivo generated by hbm2java
 */
@Entity
@Table(name="Cat_Cultivo"
    ,catalog="sisem"
)
public class CatCultivo  implements java.io.Serializable {


     private Integer idCultivo;
     private String identificador;
     private String nombre;
     private String nombreCientifico;
     private boolean status;
     private Set<CatVariedadCultivo> catVariedadCultivos = new HashSet<CatVariedadCultivo>(0);
     private Set<DatR7Inspeccion> datR7Inspeccions = new HashSet<DatR7Inspeccion>(0);
     private Set<LinkOrganismoCultivo> linkOrganismoCultivos = new HashSet<LinkOrganismoCultivo>(0);

    public CatCultivo() {
    }

	
    public CatCultivo(String identificador, String nombre, String nombreCientifico, boolean status) {
        this.identificador = identificador;
        this.nombre = nombre;
        this.nombreCientifico = nombreCientifico;
        this.status = status;
    }
    public CatCultivo(String identificador, String nombre, String nombreCientifico, boolean status, Set<CatVariedadCultivo> catVariedadCultivos, Set<DatR7Inspeccion> datR7Inspeccions, Set<LinkOrganismoCultivo> linkOrganismoCultivos) {
       this.identificador = identificador;
       this.nombre = nombre;
       this.nombreCientifico = nombreCientifico;
       this.status = status;
       this.catVariedadCultivos = catVariedadCultivos;
       this.datR7Inspeccions = datR7Inspeccions;
       this.linkOrganismoCultivos = linkOrganismoCultivos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Cultivo", unique=true, nullable=false)
    public Integer getIdCultivo() {
        return this.idCultivo;
    }
    
    public void setIdCultivo(Integer idCultivo) {
        this.idCultivo = idCultivo;
    }

    
    @Column(name="Identificador", nullable=false, length=45)
    public String getIdentificador() {
        return this.identificador;
    }
    
    public void setIdentificador(String identificador) {
        this.identificador = identificador;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Nombre_Cientifico", nullable=false, length=45)
    public String getNombreCientifico() {
        return this.nombreCientifico;
    }
    
    public void setNombreCientifico(String nombreCientifico) {
        this.nombreCientifico = nombreCientifico;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCultivo")
    public Set<CatVariedadCultivo> getCatVariedadCultivos() {
        return this.catVariedadCultivos;
    }
    
    public void setCatVariedadCultivos(Set<CatVariedadCultivo> catVariedadCultivos) {
        this.catVariedadCultivos = catVariedadCultivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCultivo")
    public Set<DatR7Inspeccion> getDatR7Inspeccions() {
        return this.datR7Inspeccions;
    }
    
    public void setDatR7Inspeccions(Set<DatR7Inspeccion> datR7Inspeccions) {
        this.datR7Inspeccions = datR7Inspeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catCultivo")
    public Set<LinkOrganismoCultivo> getLinkOrganismoCultivos() {
        return this.linkOrganismoCultivos;
    }
    
    public void setLinkOrganismoCultivos(Set<LinkOrganismoCultivo> linkOrganismoCultivos) {
        this.linkOrganismoCultivos = linkOrganismoCultivos;
    }




}


