package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatEtapaCultivo generated by hbm2java
 */
@Entity
@Table(name="Cat_Etapa_Cultivo"
    ,catalog="sisem"
)
public class CatEtapaCultivo  implements java.io.Serializable {


     private Integer idEtapaCultivo;
     private String nombre;
     private boolean status;
     private Set<DatR1Inspeccion> datR1Inspeccions = new HashSet<DatR1Inspeccion>(0);

    public CatEtapaCultivo() {
    }

	
    public CatEtapaCultivo(String nombre, boolean status) {
        this.nombre = nombre;
        this.status = status;
    }
    public CatEtapaCultivo(String nombre, boolean status, Set<DatR1Inspeccion> datR1Inspeccions) {
       this.nombre = nombre;
       this.status = status;
       this.datR1Inspeccions = datR1Inspeccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Etapa_Cultivo", unique=true, nullable=false)
    public Integer getIdEtapaCultivo() {
        return this.idEtapaCultivo;
    }
    
    public void setIdEtapaCultivo(Integer idEtapaCultivo) {
        this.idEtapaCultivo = idEtapaCultivo;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catEtapaCultivo")
    public Set<DatR1Inspeccion> getDatR1Inspeccions() {
        return this.datR1Inspeccions;
    }
    
    public void setDatR1Inspeccions(Set<DatR1Inspeccion> datR1Inspeccions) {
        this.datR1Inspeccions = datR1Inspeccions;
    }




}


