package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CatFuncion generated by hbm2java
 */
@Entity
@Table(name="Cat_Funcion"
    ,catalog="sisem"
)
public class CatFuncion  implements java.io.Serializable {


     private Integer idFuncion;
     private CatPermiso catPermiso;
     private String nombreFuncion;
     private String urlFuncion;
     private Boolean status;

    public CatFuncion() {
    }

	
    public CatFuncion(CatPermiso catPermiso) {
        this.catPermiso = catPermiso;
    }
    public CatFuncion(CatPermiso catPermiso, String nombreFuncion, String urlFuncion, Boolean status) {
       this.catPermiso = catPermiso;
       this.nombreFuncion = nombreFuncion;
       this.urlFuncion = urlFuncion;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Funcion", unique=true, nullable=false)
    public Integer getIdFuncion() {
        return this.idFuncion;
    }
    
    public void setIdFuncion(Integer idFuncion) {
        this.idFuncion = idFuncion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Permiso", nullable=false)
    public CatPermiso getCatPermiso() {
        return this.catPermiso;
    }
    
    public void setCatPermiso(CatPermiso catPermiso) {
        this.catPermiso = catPermiso;
    }

    
    @Column(name="Nombre_Funcion", length=150)
    public String getNombreFuncion() {
        return this.nombreFuncion;
    }
    
    public void setNombreFuncion(String nombreFuncion) {
        this.nombreFuncion = nombreFuncion;
    }

    
    @Column(name="Url_Funcion", length=150)
    public String getUrlFuncion() {
        return this.urlFuncion;
    }
    
    public void setUrlFuncion(String urlFuncion) {
        this.urlFuncion = urlFuncion;
    }

    
    @Column(name="Status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


