package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatMunicipio generated by hbm2java
 */
@Entity
@Table(name="Cat_Municipio"
    ,catalog="sisem"
)
public class CatMunicipio  implements java.io.Serializable {


     private Integer idMunicipio;
     private CatEstado catEstado;
     private String claveMunicipio;
     private String nombreMunicipio;
     private boolean status;
     private String catMunicipiocol;
     private Set<DatR1Predio> datR1Predios = new HashSet<DatR1Predio>(0);
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);
     private Set<DatAlmacenBeneficio> datAlmacenBeneficios = new HashSet<DatAlmacenBeneficio>(0);
     private Set<DatR7Inspeccion> datR7Inspeccions = new HashSet<DatR7Inspeccion>(0);
     private Set<DatDomicilioFiscal> datDomicilioFiscals = new HashSet<DatDomicilioFiscal>(0);
     private Set<CatColonia> catColonias = new HashSet<CatColonia>(0);
     private Set<DatR4Direccion> datR4Direccions = new HashSet<DatR4Direccion>(0);
     private Set<DatR3Cabecera> datR3Cabeceras = new HashSet<DatR3Cabecera>(0);
     private Set<CatUnidadSnics> catUnidadSnicses = new HashSet<CatUnidadSnics>(0);

    public CatMunicipio() {
    }

	
    public CatMunicipio(CatEstado catEstado, String claveMunicipio, String nombreMunicipio, boolean status, String catMunicipiocol) {
        this.catEstado = catEstado;
        this.claveMunicipio = claveMunicipio;
        this.nombreMunicipio = nombreMunicipio;
        this.status = status;
        this.catMunicipiocol = catMunicipiocol;
    }
    public CatMunicipio(CatEstado catEstado, String claveMunicipio, String nombreMunicipio, boolean status, String catMunicipiocol, Set<DatR1Predio> datR1Predios, Set<DatR5Cabecera> datR5Cabeceras, Set<DatAlmacenBeneficio> datAlmacenBeneficios, Set<DatR7Inspeccion> datR7Inspeccions, Set<DatDomicilioFiscal> datDomicilioFiscals, Set<CatColonia> catColonias, Set<DatR4Direccion> datR4Direccions, Set<DatR3Cabecera> datR3Cabeceras, Set<CatUnidadSnics> catUnidadSnicses) {
       this.catEstado = catEstado;
       this.claveMunicipio = claveMunicipio;
       this.nombreMunicipio = nombreMunicipio;
       this.status = status;
       this.catMunicipiocol = catMunicipiocol;
       this.datR1Predios = datR1Predios;
       this.datR5Cabeceras = datR5Cabeceras;
       this.datAlmacenBeneficios = datAlmacenBeneficios;
       this.datR7Inspeccions = datR7Inspeccions;
       this.datDomicilioFiscals = datDomicilioFiscals;
       this.catColonias = catColonias;
       this.datR4Direccions = datR4Direccions;
       this.datR3Cabeceras = datR3Cabeceras;
       this.catUnidadSnicses = catUnidadSnicses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Municipio", unique=true, nullable=false)
    public Integer getIdMunicipio() {
        return this.idMunicipio;
    }
    
    public void setIdMunicipio(Integer idMunicipio) {
        this.idMunicipio = idMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

    
    @Column(name="Clave_Municipio", nullable=false, length=45)
    public String getClaveMunicipio() {
        return this.claveMunicipio;
    }
    
    public void setClaveMunicipio(String claveMunicipio) {
        this.claveMunicipio = claveMunicipio;
    }

    
    @Column(name="Nombre_Municipio", nullable=false, length=100)
    public String getNombreMunicipio() {
        return this.nombreMunicipio;
    }
    
    public void setNombreMunicipio(String nombreMunicipio) {
        this.nombreMunicipio = nombreMunicipio;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="Cat_Municipiocol", nullable=false, length=45)
    public String getCatMunicipiocol() {
        return this.catMunicipiocol;
    }
    
    public void setCatMunicipiocol(String catMunicipiocol) {
        this.catMunicipiocol = catMunicipiocol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatR1Predio> getDatR1Predios() {
        return this.datR1Predios;
    }
    
    public void setDatR1Predios(Set<DatR1Predio> datR1Predios) {
        this.datR1Predios = datR1Predios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatAlmacenBeneficio> getDatAlmacenBeneficios() {
        return this.datAlmacenBeneficios;
    }
    
    public void setDatAlmacenBeneficios(Set<DatAlmacenBeneficio> datAlmacenBeneficios) {
        this.datAlmacenBeneficios = datAlmacenBeneficios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatR7Inspeccion> getDatR7Inspeccions() {
        return this.datR7Inspeccions;
    }
    
    public void setDatR7Inspeccions(Set<DatR7Inspeccion> datR7Inspeccions) {
        this.datR7Inspeccions = datR7Inspeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatDomicilioFiscal> getDatDomicilioFiscals() {
        return this.datDomicilioFiscals;
    }
    
    public void setDatDomicilioFiscals(Set<DatDomicilioFiscal> datDomicilioFiscals) {
        this.datDomicilioFiscals = datDomicilioFiscals;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<CatColonia> getCatColonias() {
        return this.catColonias;
    }
    
    public void setCatColonias(Set<CatColonia> catColonias) {
        this.catColonias = catColonias;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatR4Direccion> getDatR4Direccions() {
        return this.datR4Direccions;
    }
    
    public void setDatR4Direccions(Set<DatR4Direccion> datR4Direccions) {
        this.datR4Direccions = datR4Direccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<DatR3Cabecera> getDatR3Cabeceras() {
        return this.datR3Cabeceras;
    }
    
    public void setDatR3Cabeceras(Set<DatR3Cabecera> datR3Cabeceras) {
        this.datR3Cabeceras = datR3Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catMunicipio")
    public Set<CatUnidadSnics> getCatUnidadSnicses() {
        return this.catUnidadSnicses;
    }
    
    public void setCatUnidadSnicses(Set<CatUnidadSnics> catUnidadSnicses) {
        this.catUnidadSnicses = catUnidadSnicses;
    }




}


