package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatPermiso generated by hbm2java
 */
@Entity
@Table(name="Cat_Permiso"
    ,catalog="sisem"
)
public class CatPermiso  implements java.io.Serializable {


     private Integer idPermiso;
     private String nombrePermiso;
     private String funcionUrl;
     private String descripcion;
     private Set<LinkRolPermiso> linkRolPermisos = new HashSet<LinkRolPermiso>(0);
     private Set<CatFuncion> catFuncions = new HashSet<CatFuncion>(0);

    public CatPermiso() {
    }

	
    public CatPermiso(String nombrePermiso, String funcionUrl, String descripcion) {
        this.nombrePermiso = nombrePermiso;
        this.funcionUrl = funcionUrl;
        this.descripcion = descripcion;
    }
    public CatPermiso(String nombrePermiso, String funcionUrl, String descripcion, Set<LinkRolPermiso> linkRolPermisos, Set<CatFuncion> catFuncions) {
       this.nombrePermiso = nombrePermiso;
       this.funcionUrl = funcionUrl;
       this.descripcion = descripcion;
       this.linkRolPermisos = linkRolPermisos;
       this.catFuncions = catFuncions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Permiso", unique=true, nullable=false)
    public Integer getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(Integer idPermiso) {
        this.idPermiso = idPermiso;
    }

    
    @Column(name="Nombre_Permiso", nullable=false, length=100)
    public String getNombrePermiso() {
        return this.nombrePermiso;
    }
    
    public void setNombrePermiso(String nombrePermiso) {
        this.nombrePermiso = nombrePermiso;
    }

    
    @Column(name="Funcion_Url", nullable=false, length=200)
    public String getFuncionUrl() {
        return this.funcionUrl;
    }
    
    public void setFuncionUrl(String funcionUrl) {
        this.funcionUrl = funcionUrl;
    }

    
    @Column(name="Descripcion", nullable=false, length=300)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catPermiso")
    public Set<LinkRolPermiso> getLinkRolPermisos() {
        return this.linkRolPermisos;
    }
    
    public void setLinkRolPermisos(Set<LinkRolPermiso> linkRolPermisos) {
        this.linkRolPermisos = linkRolPermisos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catPermiso")
    public Set<CatFuncion> getCatFuncions() {
        return this.catFuncions;
    }
    
    public void setCatFuncions(Set<CatFuncion> catFuncions) {
        this.catFuncions = catFuncions;
    }




}


