package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatPais generated by hbm2java
 */
@Entity
@Table(name="Cat_Pais"
    ,catalog="sisem"
)
public class CatPais  implements java.io.Serializable {


     private Integer idPais;
     private String nombrePais;
     private String status;
     private Set<CatEstado> catEstados = new HashSet<CatEstado>(0);

    public CatPais() {
    }

    public CatPais(String nombrePais, String status, Set<CatEstado> catEstados) {
       this.nombrePais = nombrePais;
       this.status = status;
       this.catEstados = catEstados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Pais", unique=true, nullable=false)
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }

    
    @Column(name="Nombre_Pais", length=45)
    public String getNombrePais() {
        return this.nombrePais;
    }
    
    public void setNombrePais(String nombrePais) {
        this.nombrePais = nombrePais;
    }

    
    @Column(name="Status", length=45)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catPais")
    public Set<CatEstado> getCatEstados() {
        return this.catEstados;
    }
    
    public void setCatEstados(Set<CatEstado> catEstados) {
        this.catEstados = catEstados;
    }




}


