package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatRol generated by hbm2java
 */
@Entity
@Table(name="Cat_Rol"
    ,catalog="sisem"
)
public class CatRol  implements java.io.Serializable {


     private Integer idRol;
     private String nombreRol;
     private Boolean status;
     private Set<DatAlerta> datAlertas = new HashSet<DatAlerta>(0);
     private Set<LinkRolUsuario> linkRolUsuarios = new HashSet<LinkRolUsuario>(0);
     private Set<LinkRolPermiso> linkRolPermisos = new HashSet<LinkRolPermiso>(0);
     private Set<DatBoletin> datBoletins = new HashSet<DatBoletin>(0);

    public CatRol() {
    }

    public CatRol(String nombreRol, Boolean status, Set<DatAlerta> datAlertas, Set<LinkRolUsuario> linkRolUsuarios, Set<LinkRolPermiso> linkRolPermisos, Set<DatBoletin> datBoletins) {
       this.nombreRol = nombreRol;
       this.status = status;
       this.datAlertas = datAlertas;
       this.linkRolUsuarios = linkRolUsuarios;
       this.linkRolPermisos = linkRolPermisos;
       this.datBoletins = datBoletins;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Rol", unique=true, nullable=false)
    public Integer getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(Integer idRol) {
        this.idRol = idRol;
    }

    
    @Column(name="Nombre_Rol", length=50)
    public String getNombreRol() {
        return this.nombreRol;
    }
    
    public void setNombreRol(String nombreRol) {
        this.nombreRol = nombreRol;
    }

    
    @Column(name="Status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catRol")
    public Set<DatAlerta> getDatAlertas() {
        return this.datAlertas;
    }
    
    public void setDatAlertas(Set<DatAlerta> datAlertas) {
        this.datAlertas = datAlertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catRol")
    public Set<LinkRolUsuario> getLinkRolUsuarios() {
        return this.linkRolUsuarios;
    }
    
    public void setLinkRolUsuarios(Set<LinkRolUsuario> linkRolUsuarios) {
        this.linkRolUsuarios = linkRolUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catRol")
    public Set<LinkRolPermiso> getLinkRolPermisos() {
        return this.linkRolPermisos;
    }
    
    public void setLinkRolPermisos(Set<LinkRolPermiso> linkRolPermisos) {
        this.linkRolPermisos = linkRolPermisos;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="catRols")
    public Set<DatBoletin> getDatBoletins() {
        return this.datBoletins;
    }
    
    public void setDatBoletins(Set<DatBoletin> datBoletins) {
        this.datBoletins = datBoletins;
    }




}


