package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatStatusMovilizacion generated by hbm2java
 */
@Entity
@Table(name="Cat_Status_Movilizacion"
    ,catalog="sisem"
)
public class CatStatusMovilizacion  implements java.io.Serializable {


     private Integer idStatusMovilizacion;
     private String nombreStatusMovilizacion;
     private Set<DatR3Cabecera> datR3Cabeceras = new HashSet<DatR3Cabecera>(0);
     private Set<DatR4Cabecera> datR4Cabeceras = new HashSet<DatR4Cabecera>(0);

    public CatStatusMovilizacion() {
    }

    public CatStatusMovilizacion(String nombreStatusMovilizacion, Set<DatR3Cabecera> datR3Cabeceras, Set<DatR4Cabecera> datR4Cabeceras) {
       this.nombreStatusMovilizacion = nombreStatusMovilizacion;
       this.datR3Cabeceras = datR3Cabeceras;
       this.datR4Cabeceras = datR4Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Status_Movilizacion", unique=true, nullable=false)
    public Integer getIdStatusMovilizacion() {
        return this.idStatusMovilizacion;
    }
    
    public void setIdStatusMovilizacion(Integer idStatusMovilizacion) {
        this.idStatusMovilizacion = idStatusMovilizacion;
    }

    
    @Column(name="Nombre_Status_Movilizacion", length=45)
    public String getNombreStatusMovilizacion() {
        return this.nombreStatusMovilizacion;
    }
    
    public void setNombreStatusMovilizacion(String nombreStatusMovilizacion) {
        this.nombreStatusMovilizacion = nombreStatusMovilizacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catStatusMovilizacion")
    public Set<DatR3Cabecera> getDatR3Cabeceras() {
        return this.datR3Cabeceras;
    }
    
    public void setDatR3Cabeceras(Set<DatR3Cabecera> datR3Cabeceras) {
        this.datR3Cabeceras = datR3Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catStatusMovilizacion")
    public Set<DatR4Cabecera> getDatR4Cabeceras() {
        return this.datR4Cabeceras;
    }
    
    public void setDatR4Cabeceras(Set<DatR4Cabecera> datR4Cabeceras) {
        this.datR4Cabeceras = datR4Cabeceras;
    }




}


