package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatTipoCultivo generated by hbm2java
 */
@Entity
@Table(name="Cat_Tipo_Cultivo"
    ,catalog="sisem"
)
public class CatTipoCultivo  implements java.io.Serializable {


     private Integer idTipoCultivo;
     private String nombreTipoCultivo;
     private boolean status;
     private Set<LinkOrganismoCultivo> linkOrganismoCultivos = new HashSet<LinkOrganismoCultivo>(0);

    public CatTipoCultivo() {
    }

	
    public CatTipoCultivo(String nombreTipoCultivo, boolean status) {
        this.nombreTipoCultivo = nombreTipoCultivo;
        this.status = status;
    }
    public CatTipoCultivo(String nombreTipoCultivo, boolean status, Set<LinkOrganismoCultivo> linkOrganismoCultivos) {
       this.nombreTipoCultivo = nombreTipoCultivo;
       this.status = status;
       this.linkOrganismoCultivos = linkOrganismoCultivos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Tipo_Cultivo", unique=true, nullable=false)
    public Integer getIdTipoCultivo() {
        return this.idTipoCultivo;
    }
    
    public void setIdTipoCultivo(Integer idTipoCultivo) {
        this.idTipoCultivo = idTipoCultivo;
    }

    
    @Column(name="Nombre_Tipo_Cultivo", nullable=false, length=45)
    public String getNombreTipoCultivo() {
        return this.nombreTipoCultivo;
    }
    
    public void setNombreTipoCultivo(String nombreTipoCultivo) {
        this.nombreTipoCultivo = nombreTipoCultivo;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catTipoCultivo")
    public Set<LinkOrganismoCultivo> getLinkOrganismoCultivos() {
        return this.linkOrganismoCultivos;
    }
    
    public void setLinkOrganismoCultivos(Set<LinkOrganismoCultivo> linkOrganismoCultivos) {
        this.linkOrganismoCultivos = linkOrganismoCultivos;
    }




}


