package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatTipoMedida generated by hbm2java
 */
@Entity
@Table(name="Cat_Tipo_Medida"
    ,catalog="sisem"
)
public class CatTipoMedida  implements java.io.Serializable {


     private Integer idTipoMedida;
     private String nombreTipoMedida;
     private boolean status;
     private Set<CatUnidadMedida> catUnidadMedidas = new HashSet<CatUnidadMedida>(0);

    public CatTipoMedida() {
    }

	
    public CatTipoMedida(String nombreTipoMedida, boolean status) {
        this.nombreTipoMedida = nombreTipoMedida;
        this.status = status;
    }
    public CatTipoMedida(String nombreTipoMedida, boolean status, Set<CatUnidadMedida> catUnidadMedidas) {
       this.nombreTipoMedida = nombreTipoMedida;
       this.status = status;
       this.catUnidadMedidas = catUnidadMedidas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Tipo_Medida", unique=true, nullable=false)
    public Integer getIdTipoMedida() {
        return this.idTipoMedida;
    }
    
    public void setIdTipoMedida(Integer idTipoMedida) {
        this.idTipoMedida = idTipoMedida;
    }

    
    @Column(name="Nombre_Tipo_Medida", nullable=false, length=45)
    public String getNombreTipoMedida() {
        return this.nombreTipoMedida;
    }
    
    public void setNombreTipoMedida(String nombreTipoMedida) {
        this.nombreTipoMedida = nombreTipoMedida;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catTipoMedida")
    public Set<CatUnidadMedida> getCatUnidadMedidas() {
        return this.catUnidadMedidas;
    }
    
    public void setCatUnidadMedidas(Set<CatUnidadMedida> catUnidadMedidas) {
        this.catUnidadMedidas = catUnidadMedidas;
    }




}


