package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatTipoAlertas generated by hbm2java
 */
@Entity
@Table(name="Cat_Tipo_Alertas"
    ,catalog="sisem"
)
public class CatTipoAlertas  implements java.io.Serializable {


     private Integer idAlertas;
     private String descripcion;
     private Set<DatAlerta> datAlertas = new HashSet<DatAlerta>(0);

    public CatTipoAlertas() {
    }

    public CatTipoAlertas(String descripcion, Set<DatAlerta> datAlertas) {
       this.descripcion = descripcion;
       this.datAlertas = datAlertas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Alertas", unique=true, nullable=false)
    public Integer getIdAlertas() {
        return this.idAlertas;
    }
    
    public void setIdAlertas(Integer idAlertas) {
        this.idAlertas = idAlertas;
    }

    
    @Column(name="Descripcion", length=200)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catTipoAlertas")
    public Set<DatAlerta> getDatAlertas() {
        return this.datAlertas;
    }
    
    public void setDatAlertas(Set<DatAlerta> datAlertas) {
        this.datAlertas = datAlertas;
    }




}


