package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatUnidadSnics generated by hbm2java
 */
@Entity
@Table(name="Cat_Unidad_Snics"
    ,catalog="sisem"
)
public class CatUnidadSnics  implements java.io.Serializable {


     private Integer idUnidadSnics;
     private CatColonia catColonia;
     private CatEstado catEstado;
     private CatMunicipio catMunicipio;
     private String codigoPostal;
     private String calle;
     private String numeroExterno;
     private String numeroInterno;
     private Set<DatR3Cabecera> datR3Cabeceras = new HashSet<DatR3Cabecera>(0);
     private Set<DatMovimientoEtiquetas> datMovimientoEtiquetases = new HashSet<DatMovimientoEtiquetas>(0);
     private Set<DatR1Cabecera> datR1Cabeceras = new HashSet<DatR1Cabecera>(0);
     private Set<DatR4Direccion> datR4Direccions = new HashSet<DatR4Direccion>(0);
     private Set<LinkMovimientoEtiquetasSnics> linkMovimientoEtiquetasSnicses = new HashSet<LinkMovimientoEtiquetasSnics>(0);
     private Set<LinkRolUsuario> linkRolUsuarios = new HashSet<LinkRolUsuario>(0);
     private Set<DatExistenciasEtiquetas> datExistenciasEtiquetases = new HashSet<DatExistenciasEtiquetas>(0);
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);
     private Set<DatOrganismo> datOrganismos = new HashSet<DatOrganismo>(0);
     private Set<DatR1Origen> datR1Origens = new HashSet<DatR1Origen>(0);

    public CatUnidadSnics() {
    }

	
    public CatUnidadSnics(CatColonia catColonia, CatEstado catEstado, CatMunicipio catMunicipio, String codigoPostal, String calle, String numeroExterno) {
        this.catColonia = catColonia;
        this.catEstado = catEstado;
        this.catMunicipio = catMunicipio;
        this.codigoPostal = codigoPostal;
        this.calle = calle;
        this.numeroExterno = numeroExterno;
    }
    public CatUnidadSnics(CatColonia catColonia, CatEstado catEstado, CatMunicipio catMunicipio, String codigoPostal, String calle, String numeroExterno, String numeroInterno, Set<DatR3Cabecera> datR3Cabeceras, Set<DatMovimientoEtiquetas> datMovimientoEtiquetases, Set<DatR1Cabecera> datR1Cabeceras, Set<DatR4Direccion> datR4Direccions, Set<LinkMovimientoEtiquetasSnics> linkMovimientoEtiquetasSnicses, Set<LinkRolUsuario> linkRolUsuarios, Set<DatExistenciasEtiquetas> datExistenciasEtiquetases, Set<DatR5Cabecera> datR5Cabeceras, Set<DatOrganismo> datOrganismos, Set<DatR1Origen> datR1Origens) {
       this.catColonia = catColonia;
       this.catEstado = catEstado;
       this.catMunicipio = catMunicipio;
       this.codigoPostal = codigoPostal;
       this.calle = calle;
       this.numeroExterno = numeroExterno;
       this.numeroInterno = numeroInterno;
       this.datR3Cabeceras = datR3Cabeceras;
       this.datMovimientoEtiquetases = datMovimientoEtiquetases;
       this.datR1Cabeceras = datR1Cabeceras;
       this.datR4Direccions = datR4Direccions;
       this.linkMovimientoEtiquetasSnicses = linkMovimientoEtiquetasSnicses;
       this.linkRolUsuarios = linkRolUsuarios;
       this.datExistenciasEtiquetases = datExistenciasEtiquetases;
       this.datR5Cabeceras = datR5Cabeceras;
       this.datOrganismos = datOrganismos;
       this.datR1Origens = datR1Origens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Unidad_Snics", unique=true, nullable=false)
    public Integer getIdUnidadSnics() {
        return this.idUnidadSnics;
    }
    
    public void setIdUnidadSnics(Integer idUnidadSnics) {
        this.idUnidadSnics = idUnidadSnics;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Colonia", nullable=false)
    public CatColonia getCatColonia() {
        return this.catColonia;
    }
    
    public void setCatColonia(CatColonia catColonia) {
        this.catColonia = catColonia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

    
    @Column(name="Codigo_Postal", nullable=false, length=45)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="Calle", nullable=false, length=45)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="Numero_Externo", nullable=false, length=45)
    public String getNumeroExterno() {
        return this.numeroExterno;
    }
    
    public void setNumeroExterno(String numeroExterno) {
        this.numeroExterno = numeroExterno;
    }

    
    @Column(name="Numero_Interno", length=45)
    public String getNumeroInterno() {
        return this.numeroInterno;
    }
    
    public void setNumeroInterno(String numeroInterno) {
        this.numeroInterno = numeroInterno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatR3Cabecera> getDatR3Cabeceras() {
        return this.datR3Cabeceras;
    }
    
    public void setDatR3Cabeceras(Set<DatR3Cabecera> datR3Cabeceras) {
        this.datR3Cabeceras = datR3Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatMovimientoEtiquetas> getDatMovimientoEtiquetases() {
        return this.datMovimientoEtiquetases;
    }
    
    public void setDatMovimientoEtiquetases(Set<DatMovimientoEtiquetas> datMovimientoEtiquetases) {
        this.datMovimientoEtiquetases = datMovimientoEtiquetases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatR1Cabecera> getDatR1Cabeceras() {
        return this.datR1Cabeceras;
    }
    
    public void setDatR1Cabeceras(Set<DatR1Cabecera> datR1Cabeceras) {
        this.datR1Cabeceras = datR1Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatR4Direccion> getDatR4Direccions() {
        return this.datR4Direccions;
    }
    
    public void setDatR4Direccions(Set<DatR4Direccion> datR4Direccions) {
        this.datR4Direccions = datR4Direccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<LinkMovimientoEtiquetasSnics> getLinkMovimientoEtiquetasSnicses() {
        return this.linkMovimientoEtiquetasSnicses;
    }
    
    public void setLinkMovimientoEtiquetasSnicses(Set<LinkMovimientoEtiquetasSnics> linkMovimientoEtiquetasSnicses) {
        this.linkMovimientoEtiquetasSnicses = linkMovimientoEtiquetasSnicses;
    }

@ManyToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnicses")
    public Set<LinkRolUsuario> getLinkRolUsuarios() {
        return this.linkRolUsuarios;
    }
    
    public void setLinkRolUsuarios(Set<LinkRolUsuario> linkRolUsuarios) {
        this.linkRolUsuarios = linkRolUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatExistenciasEtiquetas> getDatExistenciasEtiquetases() {
        return this.datExistenciasEtiquetases;
    }
    
    public void setDatExistenciasEtiquetases(Set<DatExistenciasEtiquetas> datExistenciasEtiquetases) {
        this.datExistenciasEtiquetases = datExistenciasEtiquetases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatOrganismo> getDatOrganismos() {
        return this.datOrganismos;
    }
    
    public void setDatOrganismos(Set<DatOrganismo> datOrganismos) {
        this.datOrganismos = datOrganismos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadSnics")
    public Set<DatR1Origen> getDatR1Origens() {
        return this.datR1Origens;
    }
    
    public void setDatR1Origens(Set<DatR1Origen> datR1Origens) {
        this.datR1Origens = datR1Origens;
    }




}


