package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CatUnidadMedida generated by hbm2java
 */
@Entity
@Table(name="Cat_Unidad_Medida"
    ,catalog="sisem"
)
public class CatUnidadMedida  implements java.io.Serializable {


     private Integer idUnidadMedida;
     private CatTipoMedida catTipoMedida;
     private DatUsuario datUsuarioByIdUsuarioCreacion;
     private DatUsuario datUsuarioByIdUsuarioEdicion;
     private String nombreUnidadMedida;
     private boolean status;
     private Date fechaCreacion;
     private Date fechaEdicion;
     private Set<DatR5Transporte> datR5Transportes = new HashSet<DatR5Transporte>(0);
     private Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaGranel = new HashSet<DatR4Cabecera>(0);
     private Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaEnvasado = new HashSet<DatR4Cabecera>(0);
     private Set<DatR7Inspeccion> datR7Inspeccions = new HashSet<DatR7Inspeccion>(0);
     private Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaTransporte = new HashSet<DatR4Cabecera>(0);
     private Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaEnvase = new HashSet<DatR5Detalle>(0);
     private Set<DatAlmacenBeneficio> datAlmacenBeneficios = new HashSet<DatAlmacenBeneficio>(0);
     private Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaEnvasada = new HashSet<DatR5Detalle>(0);
     private Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaGranel = new HashSet<DatR5Detalle>(0);
     private Set<DatR1Inspeccion> datR1InspeccionsForIdUnidadMedidaSuperficie = new HashSet<DatR1Inspeccion>(0);
     private Set<LinkOrganismoCultivo> linkOrganismoCultivos = new HashSet<LinkOrganismoCultivo>(0);
     private Set<DatLaboratorioGerminacion> datLaboratorioGerminacions = new HashSet<DatLaboratorioGerminacion>(0);
     private Set<DatR1Cabecera> datR1CabecerasForIdUnidadMedidaSemilla = new HashSet<DatR1Cabecera>(0);
     private Set<DatR1Inspeccion> datR1InspeccionsForIdUnidadMedidaMateriaPrima = new HashSet<DatR1Inspeccion>(0);
     private Set<DatR5Estiba> datR5Estibas = new HashSet<DatR5Estiba>(0);
     private Set<DatR7Cabecera> datR7Cabeceras = new HashSet<DatR7Cabecera>(0);
     private Set<DatR3Cabecera> datR3CabecerasForIdUnidadMedidaVehiculo = new HashSet<DatR3Cabecera>(0);
     private Set<DatR1Cabecera> datR1CabecerasForIdUnidadMedidaSuperficie = new HashSet<DatR1Cabecera>(0);
     private Set<DatR5MateriaPrima> datR5MateriaPrimas = new HashSet<DatR5MateriaPrima>(0);
     private Set<DatR3Cabecera> datR3CabecerasForIdUnidadMedidaCantidad = new HashSet<DatR3Cabecera>(0);

    public CatUnidadMedida() {
    }

	
    public CatUnidadMedida(CatTipoMedida catTipoMedida, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, String nombreUnidadMedida, boolean status, Date fechaCreacion, Date fechaEdicion) {
        this.catTipoMedida = catTipoMedida;
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
        this.nombreUnidadMedida = nombreUnidadMedida;
        this.status = status;
        this.fechaCreacion = fechaCreacion;
        this.fechaEdicion = fechaEdicion;
    }
    public CatUnidadMedida(CatTipoMedida catTipoMedida, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, String nombreUnidadMedida, boolean status, Date fechaCreacion, Date fechaEdicion, Set<DatR5Transporte> datR5Transportes, Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaGranel, Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaEnvasado, Set<DatR7Inspeccion> datR7Inspeccions, Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaTransporte, Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaEnvase, Set<DatAlmacenBeneficio> datAlmacenBeneficios, Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaEnvasada, Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaGranel, Set<DatR1Inspeccion> datR1InspeccionsForIdUnidadMedidaSuperficie, Set<LinkOrganismoCultivo> linkOrganismoCultivos, Set<DatLaboratorioGerminacion> datLaboratorioGerminacions, Set<DatR1Cabecera> datR1CabecerasForIdUnidadMedidaSemilla, Set<DatR1Inspeccion> datR1InspeccionsForIdUnidadMedidaMateriaPrima, Set<DatR5Estiba> datR5Estibas, Set<DatR7Cabecera> datR7Cabeceras, Set<DatR3Cabecera> datR3CabecerasForIdUnidadMedidaVehiculo, Set<DatR1Cabecera> datR1CabecerasForIdUnidadMedidaSuperficie, Set<DatR5MateriaPrima> datR5MateriaPrimas, Set<DatR3Cabecera> datR3CabecerasForIdUnidadMedidaCantidad) {
       this.catTipoMedida = catTipoMedida;
       this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
       this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
       this.nombreUnidadMedida = nombreUnidadMedida;
       this.status = status;
       this.fechaCreacion = fechaCreacion;
       this.fechaEdicion = fechaEdicion;
       this.datR5Transportes = datR5Transportes;
       this.datR4CabecerasForIdUnidadMedidaGranel = datR4CabecerasForIdUnidadMedidaGranel;
       this.datR4CabecerasForIdUnidadMedidaEnvasado = datR4CabecerasForIdUnidadMedidaEnvasado;
       this.datR7Inspeccions = datR7Inspeccions;
       this.datR4CabecerasForIdUnidadMedidaTransporte = datR4CabecerasForIdUnidadMedidaTransporte;
       this.datR5DetallesForIdUnidadMedidaEnvase = datR5DetallesForIdUnidadMedidaEnvase;
       this.datAlmacenBeneficios = datAlmacenBeneficios;
       this.datR5DetallesForIdUnidadMedidaEnvasada = datR5DetallesForIdUnidadMedidaEnvasada;
       this.datR5DetallesForIdUnidadMedidaGranel = datR5DetallesForIdUnidadMedidaGranel;
       this.datR1InspeccionsForIdUnidadMedidaSuperficie = datR1InspeccionsForIdUnidadMedidaSuperficie;
       this.linkOrganismoCultivos = linkOrganismoCultivos;
       this.datLaboratorioGerminacions = datLaboratorioGerminacions;
       this.datR1CabecerasForIdUnidadMedidaSemilla = datR1CabecerasForIdUnidadMedidaSemilla;
       this.datR1InspeccionsForIdUnidadMedidaMateriaPrima = datR1InspeccionsForIdUnidadMedidaMateriaPrima;
       this.datR5Estibas = datR5Estibas;
       this.datR7Cabeceras = datR7Cabeceras;
       this.datR3CabecerasForIdUnidadMedidaVehiculo = datR3CabecerasForIdUnidadMedidaVehiculo;
       this.datR1CabecerasForIdUnidadMedidaSuperficie = datR1CabecerasForIdUnidadMedidaSuperficie;
       this.datR5MateriaPrimas = datR5MateriaPrimas;
       this.datR3CabecerasForIdUnidadMedidaCantidad = datR3CabecerasForIdUnidadMedidaCantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Unidad_Medida", unique=true, nullable=false)
    public Integer getIdUnidadMedida() {
        return this.idUnidadMedida;
    }
    
    public void setIdUnidadMedida(Integer idUnidadMedida) {
        this.idUnidadMedida = idUnidadMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Tipo_Medida", nullable=false)
    public CatTipoMedida getCatTipoMedida() {
        return this.catTipoMedida;
    }
    
    public void setCatTipoMedida(CatTipoMedida catTipoMedida) {
        this.catTipoMedida = catTipoMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioCreacion() {
        return this.datUsuarioByIdUsuarioCreacion;
    }
    
    public void setDatUsuarioByIdUsuarioCreacion(DatUsuario datUsuarioByIdUsuarioCreacion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Edicion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioEdicion() {
        return this.datUsuarioByIdUsuarioEdicion;
    }
    
    public void setDatUsuarioByIdUsuarioEdicion(DatUsuario datUsuarioByIdUsuarioEdicion) {
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
    }

    
    @Column(name="Nombre_Unidad_Medida", nullable=false, length=45)
    public String getNombreUnidadMedida() {
        return this.nombreUnidadMedida;
    }
    
    public void setNombreUnidadMedida(String nombreUnidadMedida) {
        this.nombreUnidadMedida = nombreUnidadMedida;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Edicion", nullable=false, length=19)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatR5Transporte> getDatR5Transportes() {
        return this.datR5Transportes;
    }
    
    public void setDatR5Transportes(Set<DatR5Transporte> datR5Transportes) {
        this.datR5Transportes = datR5Transportes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaGranel")
    public Set<DatR4Cabecera> getDatR4CabecerasForIdUnidadMedidaGranel() {
        return this.datR4CabecerasForIdUnidadMedidaGranel;
    }
    
    public void setDatR4CabecerasForIdUnidadMedidaGranel(Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaGranel) {
        this.datR4CabecerasForIdUnidadMedidaGranel = datR4CabecerasForIdUnidadMedidaGranel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaEnvasado")
    public Set<DatR4Cabecera> getDatR4CabecerasForIdUnidadMedidaEnvasado() {
        return this.datR4CabecerasForIdUnidadMedidaEnvasado;
    }
    
    public void setDatR4CabecerasForIdUnidadMedidaEnvasado(Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaEnvasado) {
        this.datR4CabecerasForIdUnidadMedidaEnvasado = datR4CabecerasForIdUnidadMedidaEnvasado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatR7Inspeccion> getDatR7Inspeccions() {
        return this.datR7Inspeccions;
    }
    
    public void setDatR7Inspeccions(Set<DatR7Inspeccion> datR7Inspeccions) {
        this.datR7Inspeccions = datR7Inspeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaTransporte")
    public Set<DatR4Cabecera> getDatR4CabecerasForIdUnidadMedidaTransporte() {
        return this.datR4CabecerasForIdUnidadMedidaTransporte;
    }
    
    public void setDatR4CabecerasForIdUnidadMedidaTransporte(Set<DatR4Cabecera> datR4CabecerasForIdUnidadMedidaTransporte) {
        this.datR4CabecerasForIdUnidadMedidaTransporte = datR4CabecerasForIdUnidadMedidaTransporte;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaEnvase")
    public Set<DatR5Detalle> getDatR5DetallesForIdUnidadMedidaEnvase() {
        return this.datR5DetallesForIdUnidadMedidaEnvase;
    }
    
    public void setDatR5DetallesForIdUnidadMedidaEnvase(Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaEnvase) {
        this.datR5DetallesForIdUnidadMedidaEnvase = datR5DetallesForIdUnidadMedidaEnvase;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatAlmacenBeneficio> getDatAlmacenBeneficios() {
        return this.datAlmacenBeneficios;
    }
    
    public void setDatAlmacenBeneficios(Set<DatAlmacenBeneficio> datAlmacenBeneficios) {
        this.datAlmacenBeneficios = datAlmacenBeneficios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaEnvasada")
    public Set<DatR5Detalle> getDatR5DetallesForIdUnidadMedidaEnvasada() {
        return this.datR5DetallesForIdUnidadMedidaEnvasada;
    }
    
    public void setDatR5DetallesForIdUnidadMedidaEnvasada(Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaEnvasada) {
        this.datR5DetallesForIdUnidadMedidaEnvasada = datR5DetallesForIdUnidadMedidaEnvasada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaGranel")
    public Set<DatR5Detalle> getDatR5DetallesForIdUnidadMedidaGranel() {
        return this.datR5DetallesForIdUnidadMedidaGranel;
    }
    
    public void setDatR5DetallesForIdUnidadMedidaGranel(Set<DatR5Detalle> datR5DetallesForIdUnidadMedidaGranel) {
        this.datR5DetallesForIdUnidadMedidaGranel = datR5DetallesForIdUnidadMedidaGranel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaSuperficie")
    public Set<DatR1Inspeccion> getDatR1InspeccionsForIdUnidadMedidaSuperficie() {
        return this.datR1InspeccionsForIdUnidadMedidaSuperficie;
    }
    
    public void setDatR1InspeccionsForIdUnidadMedidaSuperficie(Set<DatR1Inspeccion> datR1InspeccionsForIdUnidadMedidaSuperficie) {
        this.datR1InspeccionsForIdUnidadMedidaSuperficie = datR1InspeccionsForIdUnidadMedidaSuperficie;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<LinkOrganismoCultivo> getLinkOrganismoCultivos() {
        return this.linkOrganismoCultivos;
    }
    
    public void setLinkOrganismoCultivos(Set<LinkOrganismoCultivo> linkOrganismoCultivos) {
        this.linkOrganismoCultivos = linkOrganismoCultivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatLaboratorioGerminacion> getDatLaboratorioGerminacions() {
        return this.datLaboratorioGerminacions;
    }
    
    public void setDatLaboratorioGerminacions(Set<DatLaboratorioGerminacion> datLaboratorioGerminacions) {
        this.datLaboratorioGerminacions = datLaboratorioGerminacions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaSemilla")
    public Set<DatR1Cabecera> getDatR1CabecerasForIdUnidadMedidaSemilla() {
        return this.datR1CabecerasForIdUnidadMedidaSemilla;
    }
    
    public void setDatR1CabecerasForIdUnidadMedidaSemilla(Set<DatR1Cabecera> datR1CabecerasForIdUnidadMedidaSemilla) {
        this.datR1CabecerasForIdUnidadMedidaSemilla = datR1CabecerasForIdUnidadMedidaSemilla;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaMateriaPrima")
    public Set<DatR1Inspeccion> getDatR1InspeccionsForIdUnidadMedidaMateriaPrima() {
        return this.datR1InspeccionsForIdUnidadMedidaMateriaPrima;
    }
    
    public void setDatR1InspeccionsForIdUnidadMedidaMateriaPrima(Set<DatR1Inspeccion> datR1InspeccionsForIdUnidadMedidaMateriaPrima) {
        this.datR1InspeccionsForIdUnidadMedidaMateriaPrima = datR1InspeccionsForIdUnidadMedidaMateriaPrima;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatR5Estiba> getDatR5Estibas() {
        return this.datR5Estibas;
    }
    
    public void setDatR5Estibas(Set<DatR5Estiba> datR5Estibas) {
        this.datR5Estibas = datR5Estibas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatR7Cabecera> getDatR7Cabeceras() {
        return this.datR7Cabeceras;
    }
    
    public void setDatR7Cabeceras(Set<DatR7Cabecera> datR7Cabeceras) {
        this.datR7Cabeceras = datR7Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaVehiculo")
    public Set<DatR3Cabecera> getDatR3CabecerasForIdUnidadMedidaVehiculo() {
        return this.datR3CabecerasForIdUnidadMedidaVehiculo;
    }
    
    public void setDatR3CabecerasForIdUnidadMedidaVehiculo(Set<DatR3Cabecera> datR3CabecerasForIdUnidadMedidaVehiculo) {
        this.datR3CabecerasForIdUnidadMedidaVehiculo = datR3CabecerasForIdUnidadMedidaVehiculo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaSuperficie")
    public Set<DatR1Cabecera> getDatR1CabecerasForIdUnidadMedidaSuperficie() {
        return this.datR1CabecerasForIdUnidadMedidaSuperficie;
    }
    
    public void setDatR1CabecerasForIdUnidadMedidaSuperficie(Set<DatR1Cabecera> datR1CabecerasForIdUnidadMedidaSuperficie) {
        this.datR1CabecerasForIdUnidadMedidaSuperficie = datR1CabecerasForIdUnidadMedidaSuperficie;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedida")
    public Set<DatR5MateriaPrima> getDatR5MateriaPrimas() {
        return this.datR5MateriaPrimas;
    }
    
    public void setDatR5MateriaPrimas(Set<DatR5MateriaPrima> datR5MateriaPrimas) {
        this.datR5MateriaPrimas = datR5MateriaPrimas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catUnidadMedidaByIdUnidadMedidaCantidad")
    public Set<DatR3Cabecera> getDatR3CabecerasForIdUnidadMedidaCantidad() {
        return this.datR3CabecerasForIdUnidadMedidaCantidad;
    }
    
    public void setDatR3CabecerasForIdUnidadMedidaCantidad(Set<DatR3Cabecera> datR3CabecerasForIdUnidadMedidaCantidad) {
        this.datR3CabecerasForIdUnidadMedidaCantidad = datR3CabecerasForIdUnidadMedidaCantidad;
    }




}


