package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CatVariedadCultivo generated by hbm2java
 */
@Entity
@Table(name="Cat_Variedad_Cultivo"
    ,catalog="sisem"
)
public class CatVariedadCultivo  implements java.io.Serializable {


     private Integer idVariedadCultivo;
     private CatCultivo catCultivo;
     private String nombreVariedadCultivo;
     private Set<DatR5Detalle> datR5Detalles = new HashSet<DatR5Detalle>(0);
     private Set<DatR7Inspeccion> datR7Inspeccions = new HashSet<DatR7Inspeccion>(0);

    public CatVariedadCultivo() {
    }

	
    public CatVariedadCultivo(CatCultivo catCultivo) {
        this.catCultivo = catCultivo;
    }
    public CatVariedadCultivo(CatCultivo catCultivo, String nombreVariedadCultivo, Set<DatR5Detalle> datR5Detalles, Set<DatR7Inspeccion> datR7Inspeccions) {
       this.catCultivo = catCultivo;
       this.nombreVariedadCultivo = nombreVariedadCultivo;
       this.datR5Detalles = datR5Detalles;
       this.datR7Inspeccions = datR7Inspeccions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Variedad_Cultivo", unique=true, nullable=false)
    public Integer getIdVariedadCultivo() {
        return this.idVariedadCultivo;
    }
    
    public void setIdVariedadCultivo(Integer idVariedadCultivo) {
        this.idVariedadCultivo = idVariedadCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Cultivo", nullable=false)
    public CatCultivo getCatCultivo() {
        return this.catCultivo;
    }
    
    public void setCatCultivo(CatCultivo catCultivo) {
        this.catCultivo = catCultivo;
    }

    
    @Column(name="Nombre_Variedad_cultivo", length=45)
    public String getNombreVariedadCultivo() {
        return this.nombreVariedadCultivo;
    }
    
    public void setNombreVariedadCultivo(String nombreVariedadCultivo) {
        this.nombreVariedadCultivo = nombreVariedadCultivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catVariedadCultivo")
    public Set<DatR5Detalle> getDatR5Detalles() {
        return this.datR5Detalles;
    }
    
    public void setDatR5Detalles(Set<DatR5Detalle> datR5Detalles) {
        this.datR5Detalles = datR5Detalles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="catVariedadCultivo")
    public Set<DatR7Inspeccion> getDatR7Inspeccions() {
        return this.datR7Inspeccions;
    }
    
    public void setDatR7Inspeccions(Set<DatR7Inspeccion> datR7Inspeccions) {
        this.datR7Inspeccions = datR7Inspeccions;
    }




}


