package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DatAlerta generated by hbm2java
 */
@Entity
@Table(name="Dat_Alerta"
    ,catalog="sisem"
)
public class DatAlerta  implements java.io.Serializable {


     private Integer idAlerta;
     private CatTipoAlertas catTipoAlertas;
     private CatRol catRol;
     private DatR3Cabecera datR3Cabecera;
     private DatR4Cabecera datR4Cabecera;
     private DatOrganismo datOrganismo;
     private DatMovimientoEtiquetas datMovimientoEtiquetas;
     private boolean status;

    public DatAlerta() {
    }

	
    public DatAlerta(CatTipoAlertas catTipoAlertas, CatRol catRol, boolean status) {
        this.catTipoAlertas = catTipoAlertas;
        this.catRol = catRol;
        this.status = status;
    }
    public DatAlerta(CatTipoAlertas catTipoAlertas, CatRol catRol, DatR3Cabecera datR3Cabecera, DatR4Cabecera datR4Cabecera, DatOrganismo datOrganismo, DatMovimientoEtiquetas datMovimientoEtiquetas, boolean status) {
       this.catTipoAlertas = catTipoAlertas;
       this.catRol = catRol;
       this.datR3Cabecera = datR3Cabecera;
       this.datR4Cabecera = datR4Cabecera;
       this.datOrganismo = datOrganismo;
       this.datMovimientoEtiquetas = datMovimientoEtiquetas;
       this.status = status;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Alerta", unique=true, nullable=false)
    public Integer getIdAlerta() {
        return this.idAlerta;
    }
    
    public void setIdAlerta(Integer idAlerta) {
        this.idAlerta = idAlerta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Tipo_Alerta", nullable=false)
    public CatTipoAlertas getCatTipoAlertas() {
        return this.catTipoAlertas;
    }
    
    public void setCatTipoAlertas(CatTipoAlertas catTipoAlertas) {
        this.catTipoAlertas = catTipoAlertas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Rol", nullable=false)
    public CatRol getCatRol() {
        return this.catRol;
    }
    
    public void setCatRol(CatRol catRol) {
        this.catRol = catRol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R3_Cabecera")
    public DatR3Cabecera getDatR3Cabecera() {
        return this.datR3Cabecera;
    }
    
    public void setDatR3Cabecera(DatR3Cabecera datR3Cabecera) {
        this.datR3Cabecera = datR3Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R4_cabecera")
    public DatR4Cabecera getDatR4Cabecera() {
        return this.datR4Cabecera;
    }
    
    public void setDatR4Cabecera(DatR4Cabecera datR4Cabecera) {
        this.datR4Cabecera = datR4Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo")
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Movimiento_Etiquetas")
    public DatMovimientoEtiquetas getDatMovimientoEtiquetas() {
        return this.datMovimientoEtiquetas;
    }
    
    public void setDatMovimientoEtiquetas(DatMovimientoEtiquetas datMovimientoEtiquetas) {
        this.datMovimientoEtiquetas = datMovimientoEtiquetas;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


