package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatA5Cabecera generated by hbm2java
 */
@Entity
@Table(name="Dat_A5_Cabecera"
    ,catalog="sisem"
)
public class DatA5Cabecera  implements java.io.Serializable {


     private Integer idA5Cabecera;
     private DatUsuario datUsuario;
     private DatLaboratorioCabecera datLaboratorioCabecera;
     private DatDomicilioFiscal datDomicilioFiscal;
     private DatRepresentanteLegal datRepresentanteLegal;
     private Date fechaCreacion;
     private int cantidad;

    public DatA5Cabecera() {
    }

	
    public DatA5Cabecera(DatUsuario datUsuario, DatLaboratorioCabecera datLaboratorioCabecera, DatDomicilioFiscal datDomicilioFiscal, Date fechaCreacion, int cantidad) {
        this.datUsuario = datUsuario;
        this.datLaboratorioCabecera = datLaboratorioCabecera;
        this.datDomicilioFiscal = datDomicilioFiscal;
        this.fechaCreacion = fechaCreacion;
        this.cantidad = cantidad;
    }
    public DatA5Cabecera(DatUsuario datUsuario, DatLaboratorioCabecera datLaboratorioCabecera, DatDomicilioFiscal datDomicilioFiscal, DatRepresentanteLegal datRepresentanteLegal, Date fechaCreacion, int cantidad) {
       this.datUsuario = datUsuario;
       this.datLaboratorioCabecera = datLaboratorioCabecera;
       this.datDomicilioFiscal = datDomicilioFiscal;
       this.datRepresentanteLegal = datRepresentanteLegal;
       this.fechaCreacion = fechaCreacion;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_A5_Cabecera", unique=true, nullable=false)
    public Integer getIdA5Cabecera() {
        return this.idA5Cabecera;
    }
    
    public void setIdA5Cabecera(Integer idA5Cabecera) {
        this.idA5Cabecera = idA5Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuario() {
        return this.datUsuario;
    }
    
    public void setDatUsuario(DatUsuario datUsuario) {
        this.datUsuario = datUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Laboratorio", nullable=false)
    public DatLaboratorioCabecera getDatLaboratorioCabecera() {
        return this.datLaboratorioCabecera;
    }
    
    public void setDatLaboratorioCabecera(DatLaboratorioCabecera datLaboratorioCabecera) {
        this.datLaboratorioCabecera = datLaboratorioCabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Domicilio_Fiscal", nullable=false)
    public DatDomicilioFiscal getDatDomicilioFiscal() {
        return this.datDomicilioFiscal;
    }
    
    public void setDatDomicilioFiscal(DatDomicilioFiscal datDomicilioFiscal) {
        this.datDomicilioFiscal = datDomicilioFiscal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Representante_Legal")
    public DatRepresentanteLegal getDatRepresentanteLegal() {
        return this.datRepresentanteLegal;
    }
    
    public void setDatRepresentanteLegal(DatRepresentanteLegal datRepresentanteLegal) {
        this.datRepresentanteLegal = datRepresentanteLegal;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="Cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


