package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DatBoletinesArchivos generated by hbm2java
 */
@Entity
@Table(name="Dat_Boletines_Archivos"
    ,catalog="sisem"
)
public class DatBoletinesArchivos  implements java.io.Serializable {


     private Integer idBoletinesArchivos;
     private DatBoletin datBoletin;
     private String urlArchivo;

    public DatBoletinesArchivos() {
    }

    public DatBoletinesArchivos(DatBoletin datBoletin, String urlArchivo) {
       this.datBoletin = datBoletin;
       this.urlArchivo = urlArchivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Boletines_Archivos", unique=true, nullable=false)
    public Integer getIdBoletinesArchivos() {
        return this.idBoletinesArchivos;
    }
    
    public void setIdBoletinesArchivos(Integer idBoletinesArchivos) {
        this.idBoletinesArchivos = idBoletinesArchivos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Boletin", nullable=false)
    public DatBoletin getDatBoletin() {
        return this.datBoletin;
    }
    
    public void setDatBoletin(DatBoletin datBoletin) {
        this.datBoletin = datBoletin;
    }

    
    @Column(name="Url_Archivo", nullable=false, length=100)
    public String getUrlArchivo() {
        return this.urlArchivo;
    }
    
    public void setUrlArchivo(String urlArchivo) {
        this.urlArchivo = urlArchivo;
    }




}


