package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatBoletin generated by hbm2java
 */
@Entity
@Table(name="Dat_Boletin"
    ,catalog="sisem"
)
public class DatBoletin  implements java.io.Serializable {


     private Integer idBoletin;
     private String textoBoletin;
     private Date fechaBoletin;
     private String encabezadoBoletin;
     private Boolean urgente;
     private Boolean status;
     private Set<CatRol> catRols = new HashSet<CatRol>(0);
     private Set<LinkBoletinUsuario> linkBoletinUsuarios = new HashSet<LinkBoletinUsuario>(0);
     private Set<DatBoletinesArchivos> datBoletinesArchivoses = new HashSet<DatBoletinesArchivos>(0);

    public DatBoletin() {
    }

	
    public DatBoletin(String textoBoletin) {
        this.textoBoletin = textoBoletin;
    }
    public DatBoletin(String textoBoletin, Date fechaBoletin, String encabezadoBoletin, Boolean urgente, Boolean status, Set<CatRol> catRols, Set<LinkBoletinUsuario> linkBoletinUsuarios, Set<DatBoletinesArchivos> datBoletinesArchivoses) {
       this.textoBoletin = textoBoletin;
       this.fechaBoletin = fechaBoletin;
       this.encabezadoBoletin = encabezadoBoletin;
       this.urgente = urgente;
       this.status = status;
       this.catRols = catRols;
       this.linkBoletinUsuarios = linkBoletinUsuarios;
       this.datBoletinesArchivoses = datBoletinesArchivoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Boletin", unique=true, nullable=false)
    public Integer getIdBoletin() {
        return this.idBoletin;
    }
    
    public void setIdBoletin(Integer idBoletin) {
        this.idBoletin = idBoletin;
    }

    
    @Column(name="Texto_Boletin", nullable=false, length=500)
    public String getTextoBoletin() {
        return this.textoBoletin;
    }
    
    public void setTextoBoletin(String textoBoletin) {
        this.textoBoletin = textoBoletin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Boletin", length=19)
    public Date getFechaBoletin() {
        return this.fechaBoletin;
    }
    
    public void setFechaBoletin(Date fechaBoletin) {
        this.fechaBoletin = fechaBoletin;
    }

    
    @Column(name="Encabezado_Boletin", length=150)
    public String getEncabezadoBoletin() {
        return this.encabezadoBoletin;
    }
    
    public void setEncabezadoBoletin(String encabezadoBoletin) {
        this.encabezadoBoletin = encabezadoBoletin;
    }

    
    @Column(name="Urgente")
    public Boolean getUrgente() {
        return this.urgente;
    }
    
    public void setUrgente(Boolean urgente) {
        this.urgente = urgente;
    }

    
    @Column(name="Status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Link_Boletin_Rol", catalog="sisem", joinColumns = { 
        @JoinColumn(name="Id_Boletin", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Id_Rol", nullable=false, updatable=false) })
    public Set<CatRol> getCatRols() {
        return this.catRols;
    }
    
    public void setCatRols(Set<CatRol> catRols) {
        this.catRols = catRols;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datBoletin")
    public Set<LinkBoletinUsuario> getLinkBoletinUsuarios() {
        return this.linkBoletinUsuarios;
    }
    
    public void setLinkBoletinUsuarios(Set<LinkBoletinUsuario> linkBoletinUsuarios) {
        this.linkBoletinUsuarios = linkBoletinUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datBoletin")
    public Set<DatBoletinesArchivos> getDatBoletinesArchivoses() {
        return this.datBoletinesArchivoses;
    }
    
    public void setDatBoletinesArchivoses(Set<DatBoletinesArchivos> datBoletinesArchivoses) {
        this.datBoletinesArchivoses = datBoletinesArchivoses;
    }




}


