package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatDomicilioFiscal generated by hbm2java
 */
@Entity
@Table(name="Dat_Domicilio_Fiscal"
    ,catalog="sisem"
)
public class DatDomicilioFiscal  implements java.io.Serializable {


     private Integer idDomicilioFiscal;
     private CatColonia catColonia;
     private CatEstado catEstado;
     private CatTipoDomicilio catTipoDomicilio;
     private DatOrganismo datOrganismo;
     private CatMunicipio catMunicipio;
     private String calle;
     private String numero;
     private Integer claveLada;
     private int telefono;
     private String codigoPostal;
     private String correoElectronico;
     private boolean sucursal;
     private boolean status;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);
     private Set<DatA5Cabecera> datA5Cabeceras = new HashSet<DatA5Cabecera>(0);

    public DatDomicilioFiscal() {
    }

	
    public DatDomicilioFiscal(CatColonia catColonia, CatEstado catEstado, CatTipoDomicilio catTipoDomicilio, DatOrganismo datOrganismo, CatMunicipio catMunicipio, String calle, int telefono, String codigoPostal, boolean sucursal, boolean status) {
        this.catColonia = catColonia;
        this.catEstado = catEstado;
        this.catTipoDomicilio = catTipoDomicilio;
        this.datOrganismo = datOrganismo;
        this.catMunicipio = catMunicipio;
        this.calle = calle;
        this.telefono = telefono;
        this.codigoPostal = codigoPostal;
        this.sucursal = sucursal;
        this.status = status;
    }
    public DatDomicilioFiscal(CatColonia catColonia, CatEstado catEstado, CatTipoDomicilio catTipoDomicilio, DatOrganismo datOrganismo, CatMunicipio catMunicipio, String calle, String numero, Integer claveLada, int telefono, String codigoPostal, String correoElectronico, boolean sucursal, boolean status, Set<DatR5Cabecera> datR5Cabeceras, Set<DatA5Cabecera> datA5Cabeceras) {
       this.catColonia = catColonia;
       this.catEstado = catEstado;
       this.catTipoDomicilio = catTipoDomicilio;
       this.datOrganismo = datOrganismo;
       this.catMunicipio = catMunicipio;
       this.calle = calle;
       this.numero = numero;
       this.claveLada = claveLada;
       this.telefono = telefono;
       this.codigoPostal = codigoPostal;
       this.correoElectronico = correoElectronico;
       this.sucursal = sucursal;
       this.status = status;
       this.datR5Cabeceras = datR5Cabeceras;
       this.datA5Cabeceras = datA5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Domicilio_Fiscal", unique=true, nullable=false)
    public Integer getIdDomicilioFiscal() {
        return this.idDomicilioFiscal;
    }
    
    public void setIdDomicilioFiscal(Integer idDomicilioFiscal) {
        this.idDomicilioFiscal = idDomicilioFiscal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Colonia", nullable=false)
    public CatColonia getCatColonia() {
        return this.catColonia;
    }
    
    public void setCatColonia(CatColonia catColonia) {
        this.catColonia = catColonia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Tipo_Domicilio", nullable=false)
    public CatTipoDomicilio getCatTipoDomicilio() {
        return this.catTipoDomicilio;
    }
    
    public void setCatTipoDomicilio(CatTipoDomicilio catTipoDomicilio) {
        this.catTipoDomicilio = catTipoDomicilio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo", nullable=false)
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

    
    @Column(name="Calle", nullable=false, length=250)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }

    
    @Column(name="Numero", length=50)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="Clave_Lada")
    public Integer getClaveLada() {
        return this.claveLada;
    }
    
    public void setClaveLada(Integer claveLada) {
        this.claveLada = claveLada;
    }

    
    @Column(name="Telefono", nullable=false)
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Codigo_Postal", nullable=false, length=50)
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }

    
    @Column(name="Correo_Electronico", length=50)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

    
    @Column(name="Sucursal", nullable=false)
    public boolean isSucursal() {
        return this.sucursal;
    }
    
    public void setSucursal(boolean sucursal) {
        this.sucursal = sucursal;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datDomicilioFiscal")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datDomicilioFiscal")
    public Set<DatA5Cabecera> getDatA5Cabeceras() {
        return this.datA5Cabeceras;
    }
    
    public void setDatA5Cabeceras(Set<DatA5Cabecera> datA5Cabeceras) {
        this.datA5Cabeceras = datA5Cabeceras;
    }




}


