package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * DatExistenciasEtiquetas generated by hbm2java
 */
@Entity
@Table(name="Dat_Existencias_Etiquetas"
    ,catalog="sisem"
)
public class DatExistenciasEtiquetas  implements java.io.Serializable {


     private Integer idExistenciasEtiquetas;
     private CatCategoria catCategoria;
     private CatUnidadSnics catUnidadSnics;
     private Integer existencias;
     private DatSerieExistencias datSerieExistencias;
     private DatFoliosExistencias datFoliosExistencias;

    public DatExistenciasEtiquetas() {
    }

	
    public DatExistenciasEtiquetas(CatCategoria catCategoria, CatUnidadSnics catUnidadSnics) {
        this.catCategoria = catCategoria;
        this.catUnidadSnics = catUnidadSnics;
    }
    public DatExistenciasEtiquetas(CatCategoria catCategoria, CatUnidadSnics catUnidadSnics, Integer existencias, DatSerieExistencias datSerieExistencias, DatFoliosExistencias datFoliosExistencias) {
       this.catCategoria = catCategoria;
       this.catUnidadSnics = catUnidadSnics;
       this.existencias = existencias;
       this.datSerieExistencias = datSerieExistencias;
       this.datFoliosExistencias = datFoliosExistencias;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Existencias_Etiquetas", unique=true, nullable=false)
    public Integer getIdExistenciasEtiquetas() {
        return this.idExistenciasEtiquetas;
    }
    
    public void setIdExistenciasEtiquetas(Integer idExistenciasEtiquetas) {
        this.idExistenciasEtiquetas = idExistenciasEtiquetas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria_Etiqueta", nullable=false)
    public CatCategoria getCatCategoria() {
        return this.catCategoria;
    }
    
    public void setCatCategoria(CatCategoria catCategoria) {
        this.catCategoria = catCategoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Snics", nullable=false)
    public CatUnidadSnics getCatUnidadSnics() {
        return this.catUnidadSnics;
    }
    
    public void setCatUnidadSnics(CatUnidadSnics catUnidadSnics) {
        this.catUnidadSnics = catUnidadSnics;
    }

    
    @Column(name="Existencias")
    public Integer getExistencias() {
        return this.existencias;
    }
    
    public void setExistencias(Integer existencias) {
        this.existencias = existencias;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="datExistenciasEtiquetas")
    public DatSerieExistencias getDatSerieExistencias() {
        return this.datSerieExistencias;
    }
    
    public void setDatSerieExistencias(DatSerieExistencias datSerieExistencias) {
        this.datSerieExistencias = datSerieExistencias;
    }

@OneToOne(fetch=FetchType.LAZY, mappedBy="datExistenciasEtiquetas")
    public DatFoliosExistencias getDatFoliosExistencias() {
        return this.datFoliosExistencias;
    }
    
    public void setDatFoliosExistencias(DatFoliosExistencias datFoliosExistencias) {
        this.datFoliosExistencias = datFoliosExistencias;
    }




}


