package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DatFoliosExistencias generated by hbm2java
 */
@Entity
@Table(name="Dat_Folios_Existencias"
    ,catalog="sisem"
)
public class DatFoliosExistencias  implements java.io.Serializable {


     private Integer idExistenciasEtiquetas;
     private DatExistenciasEtiquetas datExistenciasEtiquetas;
     private int idFoliosExistencias;
     private String folioInicial;
     private String folioFinal;

    public DatFoliosExistencias() {
    }

    public DatFoliosExistencias(DatExistenciasEtiquetas datExistenciasEtiquetas, int idFoliosExistencias, String folioInicial, String folioFinal) {
       this.datExistenciasEtiquetas = datExistenciasEtiquetas;
       this.idFoliosExistencias = idFoliosExistencias;
       this.folioInicial = folioInicial;
       this.folioFinal = folioFinal;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="datExistenciasEtiquetas"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Id_Existencias_Etiquetas", unique=true, nullable=false)
    public Integer getIdExistenciasEtiquetas() {
        return this.idExistenciasEtiquetas;
    }
    
    public void setIdExistenciasEtiquetas(Integer idExistenciasEtiquetas) {
        this.idExistenciasEtiquetas = idExistenciasEtiquetas;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public DatExistenciasEtiquetas getDatExistenciasEtiquetas() {
        return this.datExistenciasEtiquetas;
    }
    
    public void setDatExistenciasEtiquetas(DatExistenciasEtiquetas datExistenciasEtiquetas) {
        this.datExistenciasEtiquetas = datExistenciasEtiquetas;
    }

    
    @Column(name="Id_Folios_Existencias", nullable=false)
    public int getIdFoliosExistencias() {
        return this.idFoliosExistencias;
    }
    
    public void setIdFoliosExistencias(int idFoliosExistencias) {
        this.idFoliosExistencias = idFoliosExistencias;
    }

    
    @Column(name="Folio_Inicial", nullable=false, length=45)
    public String getFolioInicial() {
        return this.folioInicial;
    }
    
    public void setFolioInicial(String folioInicial) {
        this.folioInicial = folioInicial;
    }

    
    @Column(name="Folio_Final", nullable=false, length=45)
    public String getFolioFinal() {
        return this.folioFinal;
    }
    
    public void setFolioFinal(String folioFinal) {
        this.folioFinal = folioFinal;
    }




}


