package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatLaboatorioSemillas generated by hbm2java
 */
@Entity
@Table(name="Dat_Laboatorio_Semillas"
    ,catalog="sisem"
)
public class DatLaboatorioSemillas  implements java.io.Serializable {


     private Integer idLaboatorioSemillas;
     private Integer malesaNocivas;
     private Integer malesaComunes;
     private Integer cultivosOtros;
     private String cultivosInseparables;
     private Integer variedadesOtras;
     private Integer semillasManchadas;
     private Integer semillasEnfermas;
     private Set<DatLaboratorioCabecera> datLaboratorioCabeceras = new HashSet<DatLaboratorioCabecera>(0);

    public DatLaboatorioSemillas() {
    }

    public DatLaboatorioSemillas(Integer malesaNocivas, Integer malesaComunes, Integer cultivosOtros, String cultivosInseparables, Integer variedadesOtras, Integer semillasManchadas, Integer semillasEnfermas, Set<DatLaboratorioCabecera> datLaboratorioCabeceras) {
       this.malesaNocivas = malesaNocivas;
       this.malesaComunes = malesaComunes;
       this.cultivosOtros = cultivosOtros;
       this.cultivosInseparables = cultivosInseparables;
       this.variedadesOtras = variedadesOtras;
       this.semillasManchadas = semillasManchadas;
       this.semillasEnfermas = semillasEnfermas;
       this.datLaboratorioCabeceras = datLaboratorioCabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Laboatorio_Semillas", unique=true, nullable=false)
    public Integer getIdLaboatorioSemillas() {
        return this.idLaboatorioSemillas;
    }
    
    public void setIdLaboatorioSemillas(Integer idLaboatorioSemillas) {
        this.idLaboatorioSemillas = idLaboatorioSemillas;
    }

    
    @Column(name="Malesa_Nocivas")
    public Integer getMalesaNocivas() {
        return this.malesaNocivas;
    }
    
    public void setMalesaNocivas(Integer malesaNocivas) {
        this.malesaNocivas = malesaNocivas;
    }

    
    @Column(name="Malesa_Comunes")
    public Integer getMalesaComunes() {
        return this.malesaComunes;
    }
    
    public void setMalesaComunes(Integer malesaComunes) {
        this.malesaComunes = malesaComunes;
    }

    
    @Column(name="Cultivos_Otros")
    public Integer getCultivosOtros() {
        return this.cultivosOtros;
    }
    
    public void setCultivosOtros(Integer cultivosOtros) {
        this.cultivosOtros = cultivosOtros;
    }

    
    @Column(name="Cultivos_Inseparables", length=45)
    public String getCultivosInseparables() {
        return this.cultivosInseparables;
    }
    
    public void setCultivosInseparables(String cultivosInseparables) {
        this.cultivosInseparables = cultivosInseparables;
    }

    
    @Column(name="Variedades_Otras")
    public Integer getVariedadesOtras() {
        return this.variedadesOtras;
    }
    
    public void setVariedadesOtras(Integer variedadesOtras) {
        this.variedadesOtras = variedadesOtras;
    }

    
    @Column(name="Semillas_Manchadas")
    public Integer getSemillasManchadas() {
        return this.semillasManchadas;
    }
    
    public void setSemillasManchadas(Integer semillasManchadas) {
        this.semillasManchadas = semillasManchadas;
    }

    
    @Column(name="Semillas_Enfermas")
    public Integer getSemillasEnfermas() {
        return this.semillasEnfermas;
    }
    
    public void setSemillasEnfermas(Integer semillasEnfermas) {
        this.semillasEnfermas = semillasEnfermas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datLaboatorioSemillas")
    public Set<DatLaboratorioCabecera> getDatLaboratorioCabeceras() {
        return this.datLaboratorioCabeceras;
    }
    
    public void setDatLaboratorioCabeceras(Set<DatLaboratorioCabecera> datLaboratorioCabeceras) {
        this.datLaboratorioCabeceras = datLaboratorioCabeceras;
    }




}


