package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatLaboratorioDatos generated by hbm2java
 */
@Entity
@Table(name="Dat_Laboratorio_Datos"
    ,catalog="sisem"
)
public class DatLaboratorioDatos  implements java.io.Serializable {


     private Integer idLaboratorioDatos;
     private Float semillaPura;
     private Float materiaInerte;
     private Float otrasEspecies;
     private Float humedad;
     private Float cantidadVolumetrico;
     private String datLaboratorioDatoscol;
     private Set<DatLaboratorioCabecera> datLaboratorioCabeceras = new HashSet<DatLaboratorioCabecera>(0);

    public DatLaboratorioDatos() {
    }

    public DatLaboratorioDatos(Float semillaPura, Float materiaInerte, Float otrasEspecies, Float humedad, Float cantidadVolumetrico, String datLaboratorioDatoscol, Set<DatLaboratorioCabecera> datLaboratorioCabeceras) {
       this.semillaPura = semillaPura;
       this.materiaInerte = materiaInerte;
       this.otrasEspecies = otrasEspecies;
       this.humedad = humedad;
       this.cantidadVolumetrico = cantidadVolumetrico;
       this.datLaboratorioDatoscol = datLaboratorioDatoscol;
       this.datLaboratorioCabeceras = datLaboratorioCabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Laboratorio_Datos", unique=true, nullable=false)
    public Integer getIdLaboratorioDatos() {
        return this.idLaboratorioDatos;
    }
    
    public void setIdLaboratorioDatos(Integer idLaboratorioDatos) {
        this.idLaboratorioDatos = idLaboratorioDatos;
    }

    
    @Column(name="Semilla_Pura", precision=12, scale=0)
    public Float getSemillaPura() {
        return this.semillaPura;
    }
    
    public void setSemillaPura(Float semillaPura) {
        this.semillaPura = semillaPura;
    }

    
    @Column(name="Materia_Inerte", precision=12, scale=0)
    public Float getMateriaInerte() {
        return this.materiaInerte;
    }
    
    public void setMateriaInerte(Float materiaInerte) {
        this.materiaInerte = materiaInerte;
    }

    
    @Column(name="Otras_Especies", precision=12, scale=0)
    public Float getOtrasEspecies() {
        return this.otrasEspecies;
    }
    
    public void setOtrasEspecies(Float otrasEspecies) {
        this.otrasEspecies = otrasEspecies;
    }

    
    @Column(name="Humedad", precision=12, scale=0)
    public Float getHumedad() {
        return this.humedad;
    }
    
    public void setHumedad(Float humedad) {
        this.humedad = humedad;
    }

    
    @Column(name="Cantidad_volumetrico", precision=12, scale=0)
    public Float getCantidadVolumetrico() {
        return this.cantidadVolumetrico;
    }
    
    public void setCantidadVolumetrico(Float cantidadVolumetrico) {
        this.cantidadVolumetrico = cantidadVolumetrico;
    }

    
    @Column(name="Dat_Laboratorio_Datoscol", length=45)
    public String getDatLaboratorioDatoscol() {
        return this.datLaboratorioDatoscol;
    }
    
    public void setDatLaboratorioDatoscol(String datLaboratorioDatoscol) {
        this.datLaboratorioDatoscol = datLaboratorioDatoscol;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datLaboratorioDatos")
    public Set<DatLaboratorioCabecera> getDatLaboratorioCabeceras() {
        return this.datLaboratorioCabeceras;
    }
    
    public void setDatLaboratorioCabeceras(Set<DatLaboratorioCabecera> datLaboratorioCabeceras) {
        this.datLaboratorioCabeceras = datLaboratorioCabeceras;
    }




}


