package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatLaboratorioCabecera generated by hbm2java
 */
@Entity
@Table(name="Dat_Laboratorio_Cabecera"
    ,catalog="sisem"
)
public class DatLaboratorioCabecera  implements java.io.Serializable {


     private Integer idLaboratorio;
     private CatCalificacion catCalificacion;
     private DatLaboatorioSemillas datLaboatorioSemillas;
     private DatLaboratorioDatos datLaboratorioDatos;
     private DatR5Cabecera datR5Cabecera;
     private DatUsuario datUsuarioByIdUsuarioCreacion;
     private DatUsuario datUsuarioByIdUsuarioEdicion;
     private DatLaboratorioGerminacion datLaboratorioGerminacion;
     private DatLaboratorioPantulas datLaboratorioPantulas;
     private String observaciones;
     private Boolean status;
     private Boolean statusCerrada;
     private Date fechaCreacion;
     private Date fechaEdicion;
     private Set<DatA5Cabecera> datA5Cabeceras = new HashSet<DatA5Cabecera>(0);

    public DatLaboratorioCabecera() {
    }

	
    public DatLaboratorioCabecera(CatCalificacion catCalificacion, DatLaboatorioSemillas datLaboatorioSemillas, DatLaboratorioDatos datLaboratorioDatos, DatR5Cabecera datR5Cabecera, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, DatLaboratorioGerminacion datLaboratorioGerminacion, DatLaboratorioPantulas datLaboratorioPantulas) {
        this.catCalificacion = catCalificacion;
        this.datLaboatorioSemillas = datLaboatorioSemillas;
        this.datLaboratorioDatos = datLaboratorioDatos;
        this.datR5Cabecera = datR5Cabecera;
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
        this.datLaboratorioGerminacion = datLaboratorioGerminacion;
        this.datLaboratorioPantulas = datLaboratorioPantulas;
    }
    public DatLaboratorioCabecera(CatCalificacion catCalificacion, DatLaboatorioSemillas datLaboatorioSemillas, DatLaboratorioDatos datLaboratorioDatos, DatR5Cabecera datR5Cabecera, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, DatLaboratorioGerminacion datLaboratorioGerminacion, DatLaboratorioPantulas datLaboratorioPantulas, String observaciones, Boolean status, Boolean statusCerrada, Date fechaCreacion, Date fechaEdicion, Set<DatA5Cabecera> datA5Cabeceras) {
       this.catCalificacion = catCalificacion;
       this.datLaboatorioSemillas = datLaboatorioSemillas;
       this.datLaboratorioDatos = datLaboratorioDatos;
       this.datR5Cabecera = datR5Cabecera;
       this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
       this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
       this.datLaboratorioGerminacion = datLaboratorioGerminacion;
       this.datLaboratorioPantulas = datLaboratorioPantulas;
       this.observaciones = observaciones;
       this.status = status;
       this.statusCerrada = statusCerrada;
       this.fechaCreacion = fechaCreacion;
       this.fechaEdicion = fechaEdicion;
       this.datA5Cabeceras = datA5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Laboratorio", unique=true, nullable=false)
    public Integer getIdLaboratorio() {
        return this.idLaboratorio;
    }
    
    public void setIdLaboratorio(Integer idLaboratorio) {
        this.idLaboratorio = idLaboratorio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Calificacion", nullable=false)
    public CatCalificacion getCatCalificacion() {
        return this.catCalificacion;
    }
    
    public void setCatCalificacion(CatCalificacion catCalificacion) {
        this.catCalificacion = catCalificacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Laboatorio_Semillas", nullable=false)
    public DatLaboatorioSemillas getDatLaboatorioSemillas() {
        return this.datLaboatorioSemillas;
    }
    
    public void setDatLaboatorioSemillas(DatLaboatorioSemillas datLaboatorioSemillas) {
        this.datLaboatorioSemillas = datLaboatorioSemillas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Laboratorio_Datos", nullable=false)
    public DatLaboratorioDatos getDatLaboratorioDatos() {
        return this.datLaboratorioDatos;
    }
    
    public void setDatLaboratorioDatos(DatLaboratorioDatos datLaboratorioDatos) {
        this.datLaboratorioDatos = datLaboratorioDatos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R5_Cabecera", nullable=false)
    public DatR5Cabecera getDatR5Cabecera() {
        return this.datR5Cabecera;
    }
    
    public void setDatR5Cabecera(DatR5Cabecera datR5Cabecera) {
        this.datR5Cabecera = datR5Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioCreacion() {
        return this.datUsuarioByIdUsuarioCreacion;
    }
    
    public void setDatUsuarioByIdUsuarioCreacion(DatUsuario datUsuarioByIdUsuarioCreacion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Edicion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioEdicion() {
        return this.datUsuarioByIdUsuarioEdicion;
    }
    
    public void setDatUsuarioByIdUsuarioEdicion(DatUsuario datUsuarioByIdUsuarioEdicion) {
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Laboratorio_Germinacion", nullable=false)
    public DatLaboratorioGerminacion getDatLaboratorioGerminacion() {
        return this.datLaboratorioGerminacion;
    }
    
    public void setDatLaboratorioGerminacion(DatLaboratorioGerminacion datLaboratorioGerminacion) {
        this.datLaboratorioGerminacion = datLaboratorioGerminacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Laboratorio_Plantulas", nullable=false)
    public DatLaboratorioPantulas getDatLaboratorioPantulas() {
        return this.datLaboratorioPantulas;
    }
    
    public void setDatLaboratorioPantulas(DatLaboratorioPantulas datLaboratorioPantulas) {
        this.datLaboratorioPantulas = datLaboratorioPantulas;
    }

    
    @Column(name="Observaciones", length=450)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="Status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="Status_Cerrada")
    public Boolean getStatusCerrada() {
        return this.statusCerrada;
    }
    
    public void setStatusCerrada(Boolean statusCerrada) {
        this.statusCerrada = statusCerrada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Edicion", length=19)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datLaboratorioCabecera")
    public Set<DatA5Cabecera> getDatA5Cabeceras() {
        return this.datA5Cabeceras;
    }
    
    public void setDatA5Cabeceras(Set<DatA5Cabecera> datA5Cabeceras) {
        this.datA5Cabeceras = datA5Cabeceras;
    }




}


