package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatLaboratorioGerminacion generated by hbm2java
 */
@Entity
@Table(name="Dat_Laboratorio_Germinacion"
    ,catalog="sisem"
)
public class DatLaboratorioGerminacion  implements java.io.Serializable {


     private Integer idLaboratorioGerminacion;
     private CatSustrato catSustrato;
     private CatIntervalo catIntervaloByCatIntervaloConstante;
     private CatIntervalo catIntervaloByIdIntervalo16;
     private CatUnidadMedida catUnidadMedida;
     private CatIntervalo catIntervaloByIdIntervalo08;
     private Date fechaSiembra;
     private Date fechaConteo1;
     private Date fechaConteo2;
     private Float temperatura;
     private int idTipoGerminacion;
     private Set<DatLaboratorioCabecera> datLaboratorioCabeceras = new HashSet<DatLaboratorioCabecera>(0);

    public DatLaboratorioGerminacion() {
    }

	
    public DatLaboratorioGerminacion(CatSustrato catSustrato, CatIntervalo catIntervaloByCatIntervaloConstante, CatIntervalo catIntervaloByIdIntervalo16, CatUnidadMedida catUnidadMedida, CatIntervalo catIntervaloByIdIntervalo08, int idTipoGerminacion) {
        this.catSustrato = catSustrato;
        this.catIntervaloByCatIntervaloConstante = catIntervaloByCatIntervaloConstante;
        this.catIntervaloByIdIntervalo16 = catIntervaloByIdIntervalo16;
        this.catUnidadMedida = catUnidadMedida;
        this.catIntervaloByIdIntervalo08 = catIntervaloByIdIntervalo08;
        this.idTipoGerminacion = idTipoGerminacion;
    }
    public DatLaboratorioGerminacion(CatSustrato catSustrato, CatIntervalo catIntervaloByCatIntervaloConstante, CatIntervalo catIntervaloByIdIntervalo16, CatUnidadMedida catUnidadMedida, CatIntervalo catIntervaloByIdIntervalo08, Date fechaSiembra, Date fechaConteo1, Date fechaConteo2, Float temperatura, int idTipoGerminacion, Set<DatLaboratorioCabecera> datLaboratorioCabeceras) {
       this.catSustrato = catSustrato;
       this.catIntervaloByCatIntervaloConstante = catIntervaloByCatIntervaloConstante;
       this.catIntervaloByIdIntervalo16 = catIntervaloByIdIntervalo16;
       this.catUnidadMedida = catUnidadMedida;
       this.catIntervaloByIdIntervalo08 = catIntervaloByIdIntervalo08;
       this.fechaSiembra = fechaSiembra;
       this.fechaConteo1 = fechaConteo1;
       this.fechaConteo2 = fechaConteo2;
       this.temperatura = temperatura;
       this.idTipoGerminacion = idTipoGerminacion;
       this.datLaboratorioCabeceras = datLaboratorioCabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Laboratorio_Germinacion", unique=true, nullable=false)
    public Integer getIdLaboratorioGerminacion() {
        return this.idLaboratorioGerminacion;
    }
    
    public void setIdLaboratorioGerminacion(Integer idLaboratorioGerminacion) {
        this.idLaboratorioGerminacion = idLaboratorioGerminacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Sustrato", nullable=false)
    public CatSustrato getCatSustrato() {
        return this.catSustrato;
    }
    
    public void setCatSustrato(CatSustrato catSustrato) {
        this.catSustrato = catSustrato;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cat_Intervalo_Constante", nullable=false)
    public CatIntervalo getCatIntervaloByCatIntervaloConstante() {
        return this.catIntervaloByCatIntervaloConstante;
    }
    
    public void setCatIntervaloByCatIntervaloConstante(CatIntervalo catIntervaloByCatIntervaloConstante) {
        this.catIntervaloByCatIntervaloConstante = catIntervaloByCatIntervaloConstante;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Intervalo_16", nullable=false)
    public CatIntervalo getCatIntervaloByIdIntervalo16() {
        return this.catIntervaloByIdIntervalo16;
    }
    
    public void setCatIntervaloByIdIntervalo16(CatIntervalo catIntervaloByIdIntervalo16) {
        this.catIntervaloByIdIntervalo16 = catIntervaloByIdIntervalo16;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Temperatura", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Intervalo_08", nullable=false)
    public CatIntervalo getCatIntervaloByIdIntervalo08() {
        return this.catIntervaloByIdIntervalo08;
    }
    
    public void setCatIntervaloByIdIntervalo08(CatIntervalo catIntervaloByIdIntervalo08) {
        this.catIntervaloByIdIntervalo08 = catIntervaloByIdIntervalo08;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Siembra", length=19)
    public Date getFechaSiembra() {
        return this.fechaSiembra;
    }
    
    public void setFechaSiembra(Date fechaSiembra) {
        this.fechaSiembra = fechaSiembra;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Conteo1", length=19)
    public Date getFechaConteo1() {
        return this.fechaConteo1;
    }
    
    public void setFechaConteo1(Date fechaConteo1) {
        this.fechaConteo1 = fechaConteo1;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Conteo2", length=19)
    public Date getFechaConteo2() {
        return this.fechaConteo2;
    }
    
    public void setFechaConteo2(Date fechaConteo2) {
        this.fechaConteo2 = fechaConteo2;
    }

    
    @Column(name="Temperatura", precision=12, scale=0)
    public Float getTemperatura() {
        return this.temperatura;
    }
    
    public void setTemperatura(Float temperatura) {
        this.temperatura = temperatura;
    }

    
    @Column(name="Id_Tipo_Germinacion", nullable=false)
    public int getIdTipoGerminacion() {
        return this.idTipoGerminacion;
    }
    
    public void setIdTipoGerminacion(int idTipoGerminacion) {
        this.idTipoGerminacion = idTipoGerminacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datLaboratorioGerminacion")
    public Set<DatLaboratorioCabecera> getDatLaboratorioCabeceras() {
        return this.datLaboratorioCabeceras;
    }
    
    public void setDatLaboratorioCabeceras(Set<DatLaboratorioCabecera> datLaboratorioCabeceras) {
        this.datLaboratorioCabeceras = datLaboratorioCabeceras;
    }




}


