package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatMovimientoEtiquetas generated by hbm2java
 */
@Entity
@Table(name="Dat_Movimiento_Etiquetas"
    ,catalog="sisem"
)
public class DatMovimientoEtiquetas  implements java.io.Serializable {


     private Integer idMovimientoEtiquetas;
     private CatUnidadSnics catUnidadSnics;
     private CatCategoria catCategoria;
     private CatStatusMovimientoEtiqueta catStatusMovimientoEtiqueta;
     private int cantidadSolicitada;
     private Integer cantidadAutorizada;
     private boolean asignacion;
     private String cantidadEstiba;
     private Set<DatAlerta> datAlertas = new HashSet<DatAlerta>(0);
     private Set<LinkMovimientoEtiquetasSnics> linkMovimientoEtiquetasSnicses = new HashSet<LinkMovimientoEtiquetasSnics>(0);

    public DatMovimientoEtiquetas() {
    }

	
    public DatMovimientoEtiquetas(CatUnidadSnics catUnidadSnics, CatCategoria catCategoria, CatStatusMovimientoEtiqueta catStatusMovimientoEtiqueta, int cantidadSolicitada, boolean asignacion) {
        this.catUnidadSnics = catUnidadSnics;
        this.catCategoria = catCategoria;
        this.catStatusMovimientoEtiqueta = catStatusMovimientoEtiqueta;
        this.cantidadSolicitada = cantidadSolicitada;
        this.asignacion = asignacion;
    }
    public DatMovimientoEtiquetas(CatUnidadSnics catUnidadSnics, CatCategoria catCategoria, CatStatusMovimientoEtiqueta catStatusMovimientoEtiqueta, int cantidadSolicitada, Integer cantidadAutorizada, boolean asignacion, String cantidadEstiba, Set<DatAlerta> datAlertas, Set<LinkMovimientoEtiquetasSnics> linkMovimientoEtiquetasSnicses) {
       this.catUnidadSnics = catUnidadSnics;
       this.catCategoria = catCategoria;
       this.catStatusMovimientoEtiqueta = catStatusMovimientoEtiqueta;
       this.cantidadSolicitada = cantidadSolicitada;
       this.cantidadAutorizada = cantidadAutorizada;
       this.asignacion = asignacion;
       this.cantidadEstiba = cantidadEstiba;
       this.datAlertas = datAlertas;
       this.linkMovimientoEtiquetasSnicses = linkMovimientoEtiquetasSnicses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Movimiento_Etiquetas", unique=true, nullable=false)
    public Integer getIdMovimientoEtiquetas() {
        return this.idMovimientoEtiquetas;
    }
    
    public void setIdMovimientoEtiquetas(Integer idMovimientoEtiquetas) {
        this.idMovimientoEtiquetas = idMovimientoEtiquetas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Snics_Recibe", nullable=false)
    public CatUnidadSnics getCatUnidadSnics() {
        return this.catUnidadSnics;
    }
    
    public void setCatUnidadSnics(CatUnidadSnics catUnidadSnics) {
        this.catUnidadSnics = catUnidadSnics;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria_Etiqueta", nullable=false)
    public CatCategoria getCatCategoria() {
        return this.catCategoria;
    }
    
    public void setCatCategoria(CatCategoria catCategoria) {
        this.catCategoria = catCategoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Status_Movimiento_Etiqueta", nullable=false)
    public CatStatusMovimientoEtiqueta getCatStatusMovimientoEtiqueta() {
        return this.catStatusMovimientoEtiqueta;
    }
    
    public void setCatStatusMovimientoEtiqueta(CatStatusMovimientoEtiqueta catStatusMovimientoEtiqueta) {
        this.catStatusMovimientoEtiqueta = catStatusMovimientoEtiqueta;
    }

    
    @Column(name="Cantidad_Solicitada", nullable=false)
    public int getCantidadSolicitada() {
        return this.cantidadSolicitada;
    }
    
    public void setCantidadSolicitada(int cantidadSolicitada) {
        this.cantidadSolicitada = cantidadSolicitada;
    }

    
    @Column(name="Cantidad_Autorizada")
    public Integer getCantidadAutorizada() {
        return this.cantidadAutorizada;
    }
    
    public void setCantidadAutorizada(Integer cantidadAutorizada) {
        this.cantidadAutorizada = cantidadAutorizada;
    }

    
    @Column(name="Asignacion", nullable=false)
    public boolean isAsignacion() {
        return this.asignacion;
    }
    
    public void setAsignacion(boolean asignacion) {
        this.asignacion = asignacion;
    }

    
    @Column(name="Cantidad_Estiba", length=45)
    public String getCantidadEstiba() {
        return this.cantidadEstiba;
    }
    
    public void setCantidadEstiba(String cantidadEstiba) {
        this.cantidadEstiba = cantidadEstiba;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datMovimientoEtiquetas")
    public Set<DatAlerta> getDatAlertas() {
        return this.datAlertas;
    }
    
    public void setDatAlertas(Set<DatAlerta> datAlertas) {
        this.datAlertas = datAlertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datMovimientoEtiquetas")
    public Set<LinkMovimientoEtiquetasSnics> getLinkMovimientoEtiquetasSnicses() {
        return this.linkMovimientoEtiquetasSnicses;
    }
    
    public void setLinkMovimientoEtiquetasSnicses(Set<LinkMovimientoEtiquetasSnics> linkMovimientoEtiquetasSnicses) {
        this.linkMovimientoEtiquetasSnicses = linkMovimientoEtiquetasSnicses;
    }




}


