package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatOrganismo generated by hbm2java
 */
@Entity
@Table(name="Dat_Organismo"
    ,catalog="sisem"
)
public class DatOrganismo  implements java.io.Serializable {


     private Integer idOrganismo;
     private CatEstado catEstado;
     private CatUnidadSnics catUnidadSnics;
     private DatUsuario datUsuario;
     private String claveRegistro;
     private Date fechaExpedicion;
     private String nombreOrganismo;
     private String rfcCurp;
     private boolean status;
     private Set<DatPersonaContacto> datPersonaContactos = new HashSet<DatPersonaContacto>(0);
     private Set<DatR7Cabecera> datR7Cabeceras = new HashSet<DatR7Cabecera>(0);
     private Set<DatR5Cabecera> datR5CabecerasForIdOrganismoProductor = new HashSet<DatR5Cabecera>(0);
     private Set<DatAlmacenBeneficio> datAlmacenBeneficios = new HashSet<DatAlmacenBeneficio>(0);
     private Set<DatAlerta> datAlertas = new HashSet<DatAlerta>(0);
     private Set<LinkOrganismoCultivo> linkOrganismoCultivos = new HashSet<LinkOrganismoCultivo>(0);
     private Set<DatDomicilioFiscal> datDomicilioFiscals = new HashSet<DatDomicilioFiscal>(0);
     private Set<CatActividadesOrganismo> catActividadesOrganismos = new HashSet<CatActividadesOrganismo>(0);
     private Set<DatR1Cabecera> datR1CabecerasForIdProductor = new HashSet<DatR1Cabecera>(0);
     private Set<DatR1Cabecera> datR1CabecerasForIdOrganismo = new HashSet<DatR1Cabecera>(0);
     private Set<DatR5Cabecera> datR5CabecerasForIdOrganismo = new HashSet<DatR5Cabecera>(0);
     private Set<DatR3Cabecera> datR3Cabeceras = new HashSet<DatR3Cabecera>(0);
     private Set<DatRepresentanteLegal> datRepresentanteLegals = new HashSet<DatRepresentanteLegal>(0);

    public DatOrganismo() {
    }

	
    public DatOrganismo(CatEstado catEstado, CatUnidadSnics catUnidadSnics, DatUsuario datUsuario, String claveRegistro, Date fechaExpedicion, String nombreOrganismo, String rfcCurp, boolean status) {
        this.catEstado = catEstado;
        this.catUnidadSnics = catUnidadSnics;
        this.datUsuario = datUsuario;
        this.claveRegistro = claveRegistro;
        this.fechaExpedicion = fechaExpedicion;
        this.nombreOrganismo = nombreOrganismo;
        this.rfcCurp = rfcCurp;
        this.status = status;
    }
    public DatOrganismo(CatEstado catEstado, CatUnidadSnics catUnidadSnics, DatUsuario datUsuario, String claveRegistro, Date fechaExpedicion, String nombreOrganismo, String rfcCurp, boolean status, Set<DatPersonaContacto> datPersonaContactos, Set<DatR7Cabecera> datR7Cabeceras, Set<DatR5Cabecera> datR5CabecerasForIdOrganismoProductor, Set<DatAlmacenBeneficio> datAlmacenBeneficios, Set<DatAlerta> datAlertas, Set<LinkOrganismoCultivo> linkOrganismoCultivos, Set<DatDomicilioFiscal> datDomicilioFiscals, Set<CatActividadesOrganismo> catActividadesOrganismos, Set<DatR1Cabecera> datR1CabecerasForIdProductor, Set<DatR1Cabecera> datR1CabecerasForIdOrganismo, Set<DatR5Cabecera> datR5CabecerasForIdOrganismo, Set<DatR3Cabecera> datR3Cabeceras, Set<DatRepresentanteLegal> datRepresentanteLegals) {
       this.catEstado = catEstado;
       this.catUnidadSnics = catUnidadSnics;
       this.datUsuario = datUsuario;
       this.claveRegistro = claveRegistro;
       this.fechaExpedicion = fechaExpedicion;
       this.nombreOrganismo = nombreOrganismo;
       this.rfcCurp = rfcCurp;
       this.status = status;
       this.datPersonaContactos = datPersonaContactos;
       this.datR7Cabeceras = datR7Cabeceras;
       this.datR5CabecerasForIdOrganismoProductor = datR5CabecerasForIdOrganismoProductor;
       this.datAlmacenBeneficios = datAlmacenBeneficios;
       this.datAlertas = datAlertas;
       this.linkOrganismoCultivos = linkOrganismoCultivos;
       this.datDomicilioFiscals = datDomicilioFiscals;
       this.catActividadesOrganismos = catActividadesOrganismos;
       this.datR1CabecerasForIdProductor = datR1CabecerasForIdProductor;
       this.datR1CabecerasForIdOrganismo = datR1CabecerasForIdOrganismo;
       this.datR5CabecerasForIdOrganismo = datR5CabecerasForIdOrganismo;
       this.datR3Cabeceras = datR3Cabeceras;
       this.datRepresentanteLegals = datRepresentanteLegals;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Organismo", unique=true, nullable=false)
    public Integer getIdOrganismo() {
        return this.idOrganismo;
    }
    
    public void setIdOrganismo(Integer idOrganismo) {
        this.idOrganismo = idOrganismo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Unidad_Snics_Id", nullable=false)
    public CatUnidadSnics getCatUnidadSnics() {
        return this.catUnidadSnics;
    }
    
    public void setCatUnidadSnics(CatUnidadSnics catUnidadSnics) {
        this.catUnidadSnics = catUnidadSnics;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuario() {
        return this.datUsuario;
    }
    
    public void setDatUsuario(DatUsuario datUsuario) {
        this.datUsuario = datUsuario;
    }

    
    @Column(name="Clave_Registro", nullable=false, length=50)
    public String getClaveRegistro() {
        return this.claveRegistro;
    }
    
    public void setClaveRegistro(String claveRegistro) {
        this.claveRegistro = claveRegistro;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Expedicion", nullable=false, length=19)
    public Date getFechaExpedicion() {
        return this.fechaExpedicion;
    }
    
    public void setFechaExpedicion(Date fechaExpedicion) {
        this.fechaExpedicion = fechaExpedicion;
    }

    
    @Column(name="Nombre_Organismo", nullable=false, length=300)
    public String getNombreOrganismo() {
        return this.nombreOrganismo;
    }
    
    public void setNombreOrganismo(String nombreOrganismo) {
        this.nombreOrganismo = nombreOrganismo;
    }

    
    @Column(name="Rfc_Curp", nullable=false, length=50)
    public String getRfcCurp() {
        return this.rfcCurp;
    }
    
    public void setRfcCurp(String rfcCurp) {
        this.rfcCurp = rfcCurp;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatPersonaContacto> getDatPersonaContactos() {
        return this.datPersonaContactos;
    }
    
    public void setDatPersonaContactos(Set<DatPersonaContacto> datPersonaContactos) {
        this.datPersonaContactos = datPersonaContactos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatR7Cabecera> getDatR7Cabeceras() {
        return this.datR7Cabeceras;
    }
    
    public void setDatR7Cabeceras(Set<DatR7Cabecera> datR7Cabeceras) {
        this.datR7Cabeceras = datR7Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismoByIdOrganismoProductor")
    public Set<DatR5Cabecera> getDatR5CabecerasForIdOrganismoProductor() {
        return this.datR5CabecerasForIdOrganismoProductor;
    }
    
    public void setDatR5CabecerasForIdOrganismoProductor(Set<DatR5Cabecera> datR5CabecerasForIdOrganismoProductor) {
        this.datR5CabecerasForIdOrganismoProductor = datR5CabecerasForIdOrganismoProductor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatAlmacenBeneficio> getDatAlmacenBeneficios() {
        return this.datAlmacenBeneficios;
    }
    
    public void setDatAlmacenBeneficios(Set<DatAlmacenBeneficio> datAlmacenBeneficios) {
        this.datAlmacenBeneficios = datAlmacenBeneficios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatAlerta> getDatAlertas() {
        return this.datAlertas;
    }
    
    public void setDatAlertas(Set<DatAlerta> datAlertas) {
        this.datAlertas = datAlertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<LinkOrganismoCultivo> getLinkOrganismoCultivos() {
        return this.linkOrganismoCultivos;
    }
    
    public void setLinkOrganismoCultivos(Set<LinkOrganismoCultivo> linkOrganismoCultivos) {
        this.linkOrganismoCultivos = linkOrganismoCultivos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatDomicilioFiscal> getDatDomicilioFiscals() {
        return this.datDomicilioFiscals;
    }
    
    public void setDatDomicilioFiscals(Set<DatDomicilioFiscal> datDomicilioFiscals) {
        this.datDomicilioFiscals = datDomicilioFiscals;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="Link_Organismo_Actividades", catalog="sisem", joinColumns = { 
        @JoinColumn(name="Id_Organismo", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Id_Actividades_Organismo", nullable=false, updatable=false) })
    public Set<CatActividadesOrganismo> getCatActividadesOrganismos() {
        return this.catActividadesOrganismos;
    }
    
    public void setCatActividadesOrganismos(Set<CatActividadesOrganismo> catActividadesOrganismos) {
        this.catActividadesOrganismos = catActividadesOrganismos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismoByIdProductor")
    public Set<DatR1Cabecera> getDatR1CabecerasForIdProductor() {
        return this.datR1CabecerasForIdProductor;
    }
    
    public void setDatR1CabecerasForIdProductor(Set<DatR1Cabecera> datR1CabecerasForIdProductor) {
        this.datR1CabecerasForIdProductor = datR1CabecerasForIdProductor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismoByIdOrganismo")
    public Set<DatR1Cabecera> getDatR1CabecerasForIdOrganismo() {
        return this.datR1CabecerasForIdOrganismo;
    }
    
    public void setDatR1CabecerasForIdOrganismo(Set<DatR1Cabecera> datR1CabecerasForIdOrganismo) {
        this.datR1CabecerasForIdOrganismo = datR1CabecerasForIdOrganismo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismoByIdOrganismo")
    public Set<DatR5Cabecera> getDatR5CabecerasForIdOrganismo() {
        return this.datR5CabecerasForIdOrganismo;
    }
    
    public void setDatR5CabecerasForIdOrganismo(Set<DatR5Cabecera> datR5CabecerasForIdOrganismo) {
        this.datR5CabecerasForIdOrganismo = datR5CabecerasForIdOrganismo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatR3Cabecera> getDatR3Cabeceras() {
        return this.datR3Cabeceras;
    }
    
    public void setDatR3Cabeceras(Set<DatR3Cabecera> datR3Cabeceras) {
        this.datR3Cabeceras = datR3Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datOrganismo")
    public Set<DatRepresentanteLegal> getDatRepresentanteLegals() {
        return this.datRepresentanteLegals;
    }
    
    public void setDatRepresentanteLegals(Set<DatRepresentanteLegal> datRepresentanteLegals) {
        this.datRepresentanteLegals = datRepresentanteLegals;
    }




}


