package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatR7Inspeccion generated by hbm2java
 */
@Entity
@Table(name="Dat_R7_Inspeccion"
    ,catalog="sisem"
)
public class DatR7Inspeccion  implements java.io.Serializable {


     private Integer idR7Inspeccion;
     private CatFechaCiclo catFechaCiclo;
     private CatUnidadMedida catUnidadMedida;
     private CatCultivo catCultivo;
     private CatProblemasSupervision catProblemasSupervision;
     private CatEstado catEstado;
     private CatVariedadCultivo catVariedadCultivo;
     private CatCicloAgricola catCicloAgricola;
     private DatUsuario datUsuario;
     private CatCategoria catCategoria;
     private CatMunicipio catMunicipio;
     private Integer lotes;
     private int cantidad;
     private Date fechaSupervision;
     private Float precio;

    public DatR7Inspeccion() {
    }

	
    public DatR7Inspeccion(CatFechaCiclo catFechaCiclo, CatUnidadMedida catUnidadMedida, CatCultivo catCultivo, CatProblemasSupervision catProblemasSupervision, CatEstado catEstado, CatVariedadCultivo catVariedadCultivo, CatCicloAgricola catCicloAgricola, DatUsuario datUsuario, CatCategoria catCategoria, CatMunicipio catMunicipio, int cantidad, Date fechaSupervision) {
        this.catFechaCiclo = catFechaCiclo;
        this.catUnidadMedida = catUnidadMedida;
        this.catCultivo = catCultivo;
        this.catProblemasSupervision = catProblemasSupervision;
        this.catEstado = catEstado;
        this.catVariedadCultivo = catVariedadCultivo;
        this.catCicloAgricola = catCicloAgricola;
        this.datUsuario = datUsuario;
        this.catCategoria = catCategoria;
        this.catMunicipio = catMunicipio;
        this.cantidad = cantidad;
        this.fechaSupervision = fechaSupervision;
    }
    public DatR7Inspeccion(CatFechaCiclo catFechaCiclo, CatUnidadMedida catUnidadMedida, CatCultivo catCultivo, CatProblemasSupervision catProblemasSupervision, CatEstado catEstado, CatVariedadCultivo catVariedadCultivo, CatCicloAgricola catCicloAgricola, DatUsuario datUsuario, CatCategoria catCategoria, CatMunicipio catMunicipio, Integer lotes, int cantidad, Date fechaSupervision, Float precio) {
       this.catFechaCiclo = catFechaCiclo;
       this.catUnidadMedida = catUnidadMedida;
       this.catCultivo = catCultivo;
       this.catProblemasSupervision = catProblemasSupervision;
       this.catEstado = catEstado;
       this.catVariedadCultivo = catVariedadCultivo;
       this.catCicloAgricola = catCicloAgricola;
       this.datUsuario = datUsuario;
       this.catCategoria = catCategoria;
       this.catMunicipio = catMunicipio;
       this.lotes = lotes;
       this.cantidad = cantidad;
       this.fechaSupervision = fechaSupervision;
       this.precio = precio;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R7_Inspeccion", unique=true, nullable=false)
    public Integer getIdR7Inspeccion() {
        return this.idR7Inspeccion;
    }
    
    public void setIdR7Inspeccion(Integer idR7Inspeccion) {
        this.idR7Inspeccion = idR7Inspeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Fecha_Ciclo", nullable=false)
    public CatFechaCiclo getCatFechaCiclo() {
        return this.catFechaCiclo;
    }
    
    public void setCatFechaCiclo(CatFechaCiclo catFechaCiclo) {
        this.catFechaCiclo = catFechaCiclo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Cultivo", nullable=false)
    public CatCultivo getCatCultivo() {
        return this.catCultivo;
    }
    
    public void setCatCultivo(CatCultivo catCultivo) {
        this.catCultivo = catCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Problemas_Supervision", nullable=false)
    public CatProblemasSupervision getCatProblemasSupervision() {
        return this.catProblemasSupervision;
    }
    
    public void setCatProblemasSupervision(CatProblemasSupervision catProblemasSupervision) {
        this.catProblemasSupervision = catProblemasSupervision;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Variedad_Cultivo", nullable=false)
    public CatVariedadCultivo getCatVariedadCultivo() {
        return this.catVariedadCultivo;
    }
    
    public void setCatVariedadCultivo(CatVariedadCultivo catVariedadCultivo) {
        this.catVariedadCultivo = catVariedadCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Ciclo_Agricola", nullable=false)
    public CatCicloAgricola getCatCicloAgricola() {
        return this.catCicloAgricola;
    }
    
    public void setCatCicloAgricola(CatCicloAgricola catCicloAgricola) {
        this.catCicloAgricola = catCicloAgricola;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuario() {
        return this.datUsuario;
    }
    
    public void setDatUsuario(DatUsuario datUsuario) {
        this.datUsuario = datUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria", nullable=false)
    public CatCategoria getCatCategoria() {
        return this.catCategoria;
    }
    
    public void setCatCategoria(CatCategoria catCategoria) {
        this.catCategoria = catCategoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

    
    @Column(name="Lotes")
    public Integer getLotes() {
        return this.lotes;
    }
    
    public void setLotes(Integer lotes) {
        this.lotes = lotes;
    }

    
    @Column(name="Cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Supervision", nullable=false, length=19)
    public Date getFechaSupervision() {
        return this.fechaSupervision;
    }
    
    public void setFechaSupervision(Date fechaSupervision) {
        this.fechaSupervision = fechaSupervision;
    }

    
    @Column(name="Precio", precision=12, scale=0)
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }




}


