package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatR5Particulares generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Particulares"
    ,catalog="sisem"
)
public class DatR5Particulares  implements java.io.Serializable {


     private Integer idR5Particulares;
     private CatFormaMuestreo catFormaMuestreo;
     private CatTipoMuestra catTipoMuestra;
     private CatEquipoMuestreo catEquipoMuestreo;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5Particulares() {
    }

	
    public DatR5Particulares(CatFormaMuestreo catFormaMuestreo, CatTipoMuestra catTipoMuestra, CatEquipoMuestreo catEquipoMuestreo) {
        this.catFormaMuestreo = catFormaMuestreo;
        this.catTipoMuestra = catTipoMuestra;
        this.catEquipoMuestreo = catEquipoMuestreo;
    }
    public DatR5Particulares(CatFormaMuestreo catFormaMuestreo, CatTipoMuestra catTipoMuestra, CatEquipoMuestreo catEquipoMuestreo, Set<DatR5Cabecera> datR5Cabeceras) {
       this.catFormaMuestreo = catFormaMuestreo;
       this.catTipoMuestra = catTipoMuestra;
       this.catEquipoMuestreo = catEquipoMuestreo;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Particulares", unique=true, nullable=false)
    public Integer getIdR5Particulares() {
        return this.idR5Particulares;
    }
    
    public void setIdR5Particulares(Integer idR5Particulares) {
        this.idR5Particulares = idR5Particulares;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Forma_Muestreo", nullable=false)
    public CatFormaMuestreo getCatFormaMuestreo() {
        return this.catFormaMuestreo;
    }
    
    public void setCatFormaMuestreo(CatFormaMuestreo catFormaMuestreo) {
        this.catFormaMuestreo = catFormaMuestreo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Tipo_Muestra", nullable=false)
    public CatTipoMuestra getCatTipoMuestra() {
        return this.catTipoMuestra;
    }
    
    public void setCatTipoMuestra(CatTipoMuestra catTipoMuestra) {
        this.catTipoMuestra = catTipoMuestra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Cat_Equipo_Muestreo_Id_Equipo_Muestreo", nullable=false)
    public CatEquipoMuestreo getCatEquipoMuestreo() {
        return this.catEquipoMuestreo;
    }
    
    public void setCatEquipoMuestreo(CatEquipoMuestreo catEquipoMuestreo) {
        this.catEquipoMuestreo = catEquipoMuestreo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5Particulares")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


