package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatR7Cabecera generated by hbm2java
 */
@Entity
@Table(name="Dat_R7_Cabecera"
    ,catalog="sisem"
)
public class DatR7Cabecera  implements java.io.Serializable {


     private Integer idR7Cabecera;
     private CatUnidadMedida catUnidadMedida;
     private DatUsuario datUsuario;
     private DatOrganismo datOrganismo;
     private int numeroSupervision;
     private Integer numeroBodegas;
     private Integer numeroLotes;
     private Integer numeroEstibas;
     private Integer numeroPiezas;
     private int cantidadBeneficiada;
     private int cantidadMateriaPrima;
     private int cantidadInspeccionada;
     private String observaciones;
     private Date fechaMuestreo;
     private Date fechaCreacion;
     private boolean status;
     private boolean statusCerrada;
     private Set<DatR5Origen> datR5Origens = new HashSet<DatR5Origen>(0);

    public DatR7Cabecera() {
    }

	
    public DatR7Cabecera(CatUnidadMedida catUnidadMedida, DatUsuario datUsuario, DatOrganismo datOrganismo, int numeroSupervision, int cantidadBeneficiada, int cantidadMateriaPrima, int cantidadInspeccionada, String observaciones, Date fechaMuestreo, Date fechaCreacion, boolean status, boolean statusCerrada) {
        this.catUnidadMedida = catUnidadMedida;
        this.datUsuario = datUsuario;
        this.datOrganismo = datOrganismo;
        this.numeroSupervision = numeroSupervision;
        this.cantidadBeneficiada = cantidadBeneficiada;
        this.cantidadMateriaPrima = cantidadMateriaPrima;
        this.cantidadInspeccionada = cantidadInspeccionada;
        this.observaciones = observaciones;
        this.fechaMuestreo = fechaMuestreo;
        this.fechaCreacion = fechaCreacion;
        this.status = status;
        this.statusCerrada = statusCerrada;
    }
    public DatR7Cabecera(CatUnidadMedida catUnidadMedida, DatUsuario datUsuario, DatOrganismo datOrganismo, int numeroSupervision, Integer numeroBodegas, Integer numeroLotes, Integer numeroEstibas, Integer numeroPiezas, int cantidadBeneficiada, int cantidadMateriaPrima, int cantidadInspeccionada, String observaciones, Date fechaMuestreo, Date fechaCreacion, boolean status, boolean statusCerrada, Set<DatR5Origen> datR5Origens) {
       this.catUnidadMedida = catUnidadMedida;
       this.datUsuario = datUsuario;
       this.datOrganismo = datOrganismo;
       this.numeroSupervision = numeroSupervision;
       this.numeroBodegas = numeroBodegas;
       this.numeroLotes = numeroLotes;
       this.numeroEstibas = numeroEstibas;
       this.numeroPiezas = numeroPiezas;
       this.cantidadBeneficiada = cantidadBeneficiada;
       this.cantidadMateriaPrima = cantidadMateriaPrima;
       this.cantidadInspeccionada = cantidadInspeccionada;
       this.observaciones = observaciones;
       this.fechaMuestreo = fechaMuestreo;
       this.fechaCreacion = fechaCreacion;
       this.status = status;
       this.statusCerrada = statusCerrada;
       this.datR5Origens = datR5Origens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R7_Cabecera", unique=true, nullable=false)
    public Integer getIdR7Cabecera() {
        return this.idR7Cabecera;
    }
    
    public void setIdR7Cabecera(Integer idR7Cabecera) {
        this.idR7Cabecera = idR7Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuario() {
        return this.datUsuario;
    }
    
    public void setDatUsuario(DatUsuario datUsuario) {
        this.datUsuario = datUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo", nullable=false)
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

    
    @Column(name="Numero_Supervision", nullable=false)
    public int getNumeroSupervision() {
        return this.numeroSupervision;
    }
    
    public void setNumeroSupervision(int numeroSupervision) {
        this.numeroSupervision = numeroSupervision;
    }

    
    @Column(name="Numero_Bodegas")
    public Integer getNumeroBodegas() {
        return this.numeroBodegas;
    }
    
    public void setNumeroBodegas(Integer numeroBodegas) {
        this.numeroBodegas = numeroBodegas;
    }

    
    @Column(name="Numero_Lotes")
    public Integer getNumeroLotes() {
        return this.numeroLotes;
    }
    
    public void setNumeroLotes(Integer numeroLotes) {
        this.numeroLotes = numeroLotes;
    }

    
    @Column(name="Numero_Estibas")
    public Integer getNumeroEstibas() {
        return this.numeroEstibas;
    }
    
    public void setNumeroEstibas(Integer numeroEstibas) {
        this.numeroEstibas = numeroEstibas;
    }

    
    @Column(name="Numero_Piezas")
    public Integer getNumeroPiezas() {
        return this.numeroPiezas;
    }
    
    public void setNumeroPiezas(Integer numeroPiezas) {
        this.numeroPiezas = numeroPiezas;
    }

    
    @Column(name="Cantidad_Beneficiada", nullable=false)
    public int getCantidadBeneficiada() {
        return this.cantidadBeneficiada;
    }
    
    public void setCantidadBeneficiada(int cantidadBeneficiada) {
        this.cantidadBeneficiada = cantidadBeneficiada;
    }

    
    @Column(name="Cantidad_Materia_Prima", nullable=false)
    public int getCantidadMateriaPrima() {
        return this.cantidadMateriaPrima;
    }
    
    public void setCantidadMateriaPrima(int cantidadMateriaPrima) {
        this.cantidadMateriaPrima = cantidadMateriaPrima;
    }

    
    @Column(name="Cantidad_Inspeccionada", nullable=false)
    public int getCantidadInspeccionada() {
        return this.cantidadInspeccionada;
    }
    
    public void setCantidadInspeccionada(int cantidadInspeccionada) {
        this.cantidadInspeccionada = cantidadInspeccionada;
    }

    
    @Column(name="Observaciones", nullable=false, length=450)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Muestreo", nullable=false, length=19)
    public Date getFechaMuestreo() {
        return this.fechaMuestreo;
    }
    
    public void setFechaMuestreo(Date fechaMuestreo) {
        this.fechaMuestreo = fechaMuestreo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="Status_Cerrada", nullable=false)
    public boolean isStatusCerrada() {
        return this.statusCerrada;
    }
    
    public void setStatusCerrada(boolean statusCerrada) {
        this.statusCerrada = statusCerrada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR7Cabecera")
    public Set<DatR5Origen> getDatR5Origens() {
        return this.datR5Origens;
    }
    
    public void setDatR5Origens(Set<DatR5Origen> datR5Origens) {
        this.datR5Origens = datR5Origens;
    }




}


