package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatR5Origen generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Origen"
    ,catalog="sisem"
)
public class DatR5Origen  implements java.io.Serializable {


     private Integer idR5Origen;
     private DatR3Cabecera datR3Cabecera;
     private DatR4Cabecera datR4Cabecera;
     private DatR1Inspeccion datR1Inspeccion;
     private DatR7Cabecera datR7Cabecera;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5Origen() {
    }

	
    public DatR5Origen(DatR3Cabecera datR3Cabecera, DatR4Cabecera datR4Cabecera, DatR1Inspeccion datR1Inspeccion, DatR7Cabecera datR7Cabecera) {
        this.datR3Cabecera = datR3Cabecera;
        this.datR4Cabecera = datR4Cabecera;
        this.datR1Inspeccion = datR1Inspeccion;
        this.datR7Cabecera = datR7Cabecera;
    }
    public DatR5Origen(DatR3Cabecera datR3Cabecera, DatR4Cabecera datR4Cabecera, DatR1Inspeccion datR1Inspeccion, DatR7Cabecera datR7Cabecera, Set<DatR5Cabecera> datR5Cabeceras) {
       this.datR3Cabecera = datR3Cabecera;
       this.datR4Cabecera = datR4Cabecera;
       this.datR1Inspeccion = datR1Inspeccion;
       this.datR7Cabecera = datR7Cabecera;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Origen", unique=true, nullable=false)
    public Integer getIdR5Origen() {
        return this.idR5Origen;
    }
    
    public void setIdR5Origen(Integer idR5Origen) {
        this.idR5Origen = idR5Origen;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R3_Cabecera", nullable=false)
    public DatR3Cabecera getDatR3Cabecera() {
        return this.datR3Cabecera;
    }
    
    public void setDatR3Cabecera(DatR3Cabecera datR3Cabecera) {
        this.datR3Cabecera = datR3Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R4_Cabecera", nullable=false)
    public DatR4Cabecera getDatR4Cabecera() {
        return this.datR4Cabecera;
    }
    
    public void setDatR4Cabecera(DatR4Cabecera datR4Cabecera) {
        this.datR4Cabecera = datR4Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R1_Inspeccion", nullable=false)
    public DatR1Inspeccion getDatR1Inspeccion() {
        return this.datR1Inspeccion;
    }
    
    public void setDatR1Inspeccion(DatR1Inspeccion datR1Inspeccion) {
        this.datR1Inspeccion = datR1Inspeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R7_Cabecera", nullable=false)
    public DatR7Cabecera getDatR7Cabecera() {
        return this.datR7Cabecera;
    }
    
    public void setDatR7Cabecera(DatR7Cabecera datR7Cabecera) {
        this.datR7Cabecera = datR7Cabecera;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5Origen")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


