package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatR4Cabecera generated by hbm2java
 */
@Entity
@Table(name="Dat_R4_cabecera"
    ,catalog="sisem"
)
public class DatR4Cabecera  implements java.io.Serializable {


     private int idR4Cabecera;
     private DatR4Cabecera datR4Cabecera;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasado;
     private DatR1Inspeccion datR1Inspeccion;
     private CatStatusMovilizacion catStatusMovilizacion;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel;
     private DatUsuario datUsuarioByIdUsuarioCreacion;
     private DatUsuario datUsuarioByIdUsuarioEdicion;
     private CatCategoria catCategoria;
     private DatR3Cabecera datR3Cabecera;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaTransporte;
     private boolean status;
     private String numeroMovilizacion;
     private float germinacion;
     private float pureza;
     private Float cantidadGranel;
     private Float cantidadEnvasada;
     private Integer cantidadEnvase;
     private float capacidadTransporte;
     private String observaciones;
     private String matriculaVehiculo;
     private Date fechaCreacion;
     private Date fechaEdicion;
     private Boolean statusCerrada;
     private Set<DatR3Cabecera> datR3Cabeceras = new HashSet<DatR3Cabecera>(0);
     private Set<DatR5Origen> datR5Origens = new HashSet<DatR5Origen>(0);
     private Set<DatR4Cabecera> datR4Cabeceras = new HashSet<DatR4Cabecera>(0);
     private Set<DatAlerta> datAlertas = new HashSet<DatAlerta>(0);

    public DatR4Cabecera() {
    }

	
    public DatR4Cabecera(int idR4Cabecera, DatR4Cabecera datR4Cabecera, DatR1Inspeccion datR1Inspeccion, CatStatusMovilizacion catStatusMovilizacion, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, CatCategoria catCategoria, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaTransporte, boolean status, String numeroMovilizacion, float germinacion, float pureza, float capacidadTransporte, String matriculaVehiculo, Date fechaCreacion) {
        this.idR4Cabecera = idR4Cabecera;
        this.datR4Cabecera = datR4Cabecera;
        this.datR1Inspeccion = datR1Inspeccion;
        this.catStatusMovilizacion = catStatusMovilizacion;
        this.catUnidadMedidaByIdUnidadMedidaGranel = catUnidadMedidaByIdUnidadMedidaGranel;
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
        this.catCategoria = catCategoria;
        this.catUnidadMedidaByIdUnidadMedidaTransporte = catUnidadMedidaByIdUnidadMedidaTransporte;
        this.status = status;
        this.numeroMovilizacion = numeroMovilizacion;
        this.germinacion = germinacion;
        this.pureza = pureza;
        this.capacidadTransporte = capacidadTransporte;
        this.matriculaVehiculo = matriculaVehiculo;
        this.fechaCreacion = fechaCreacion;
    }
    public DatR4Cabecera(int idR4Cabecera, DatR4Cabecera datR4Cabecera, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasado, DatR1Inspeccion datR1Inspeccion, CatStatusMovilizacion catStatusMovilizacion, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, CatCategoria catCategoria, DatR3Cabecera datR3Cabecera, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaTransporte, boolean status, String numeroMovilizacion, float germinacion, float pureza, Float cantidadGranel, Float cantidadEnvasada, Integer cantidadEnvase, float capacidadTransporte, String observaciones, String matriculaVehiculo, Date fechaCreacion, Date fechaEdicion, Boolean statusCerrada, Set<DatR3Cabecera> datR3Cabeceras, Set<DatR5Origen> datR5Origens, Set<DatR4Cabecera> datR4Cabeceras, Set<DatAlerta> datAlertas) {
       this.idR4Cabecera = idR4Cabecera;
       this.datR4Cabecera = datR4Cabecera;
       this.catUnidadMedidaByIdUnidadMedidaEnvasado = catUnidadMedidaByIdUnidadMedidaEnvasado;
       this.datR1Inspeccion = datR1Inspeccion;
       this.catStatusMovilizacion = catStatusMovilizacion;
       this.catUnidadMedidaByIdUnidadMedidaGranel = catUnidadMedidaByIdUnidadMedidaGranel;
       this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
       this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
       this.catCategoria = catCategoria;
       this.datR3Cabecera = datR3Cabecera;
       this.catUnidadMedidaByIdUnidadMedidaTransporte = catUnidadMedidaByIdUnidadMedidaTransporte;
       this.status = status;
       this.numeroMovilizacion = numeroMovilizacion;
       this.germinacion = germinacion;
       this.pureza = pureza;
       this.cantidadGranel = cantidadGranel;
       this.cantidadEnvasada = cantidadEnvasada;
       this.cantidadEnvase = cantidadEnvase;
       this.capacidadTransporte = capacidadTransporte;
       this.observaciones = observaciones;
       this.matriculaVehiculo = matriculaVehiculo;
       this.fechaCreacion = fechaCreacion;
       this.fechaEdicion = fechaEdicion;
       this.statusCerrada = statusCerrada;
       this.datR3Cabeceras = datR3Cabeceras;
       this.datR5Origens = datR5Origens;
       this.datR4Cabeceras = datR4Cabeceras;
       this.datAlertas = datAlertas;
    }
   
     @Id 

    
    @Column(name="Id_R4_Cabecera", unique=true, nullable=false)
    public int getIdR4Cabecera() {
        return this.idR4Cabecera;
    }
    
    public void setIdR4Cabecera(int idR4Cabecera) {
        this.idR4Cabecera = idR4Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R4_cabecera_Padre", nullable=false)
    public DatR4Cabecera getDatR4Cabecera() {
        return this.datR4Cabecera;
    }
    
    public void setDatR4Cabecera(DatR4Cabecera datR4Cabecera) {
        this.datR4Cabecera = datR4Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Envasado")
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaEnvasado() {
        return this.catUnidadMedidaByIdUnidadMedidaEnvasado;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaEnvasado(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasado) {
        this.catUnidadMedidaByIdUnidadMedidaEnvasado = catUnidadMedidaByIdUnidadMedidaEnvasado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R1_Inspeccion", nullable=false)
    public DatR1Inspeccion getDatR1Inspeccion() {
        return this.datR1Inspeccion;
    }
    
    public void setDatR1Inspeccion(DatR1Inspeccion datR1Inspeccion) {
        this.datR1Inspeccion = datR1Inspeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Status_Movilizacion", nullable=false)
    public CatStatusMovilizacion getCatStatusMovilizacion() {
        return this.catStatusMovilizacion;
    }
    
    public void setCatStatusMovilizacion(CatStatusMovilizacion catStatusMovilizacion) {
        this.catStatusMovilizacion = catStatusMovilizacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Granel", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaGranel() {
        return this.catUnidadMedidaByIdUnidadMedidaGranel;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaGranel(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel) {
        this.catUnidadMedidaByIdUnidadMedidaGranel = catUnidadMedidaByIdUnidadMedidaGranel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioCreacion() {
        return this.datUsuarioByIdUsuarioCreacion;
    }
    
    public void setDatUsuarioByIdUsuarioCreacion(DatUsuario datUsuarioByIdUsuarioCreacion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Edicion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioEdicion() {
        return this.datUsuarioByIdUsuarioEdicion;
    }
    
    public void setDatUsuarioByIdUsuarioEdicion(DatUsuario datUsuarioByIdUsuarioEdicion) {
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria", nullable=false)
    public CatCategoria getCatCategoria() {
        return this.catCategoria;
    }
    
    public void setCatCategoria(CatCategoria catCategoria) {
        this.catCategoria = catCategoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R3_Cabecera_Padre")
    public DatR3Cabecera getDatR3Cabecera() {
        return this.datR3Cabecera;
    }
    
    public void setDatR3Cabecera(DatR3Cabecera datR3Cabecera) {
        this.datR3Cabecera = datR3Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Transporte", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaTransporte() {
        return this.catUnidadMedidaByIdUnidadMedidaTransporte;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaTransporte(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaTransporte) {
        this.catUnidadMedidaByIdUnidadMedidaTransporte = catUnidadMedidaByIdUnidadMedidaTransporte;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="Numero_Movilizacion", nullable=false, length=45)
    public String getNumeroMovilizacion() {
        return this.numeroMovilizacion;
    }
    
    public void setNumeroMovilizacion(String numeroMovilizacion) {
        this.numeroMovilizacion = numeroMovilizacion;
    }

    
    @Column(name="Germinacion", nullable=false, precision=12, scale=0)
    public float getGerminacion() {
        return this.germinacion;
    }
    
    public void setGerminacion(float germinacion) {
        this.germinacion = germinacion;
    }

    
    @Column(name="Pureza", nullable=false, precision=12, scale=0)
    public float getPureza() {
        return this.pureza;
    }
    
    public void setPureza(float pureza) {
        this.pureza = pureza;
    }

    
    @Column(name="Cantidad_Granel", precision=12, scale=0)
    public Float getCantidadGranel() {
        return this.cantidadGranel;
    }
    
    public void setCantidadGranel(Float cantidadGranel) {
        this.cantidadGranel = cantidadGranel;
    }

    
    @Column(name="Cantidad_Envasada", precision=12, scale=0)
    public Float getCantidadEnvasada() {
        return this.cantidadEnvasada;
    }
    
    public void setCantidadEnvasada(Float cantidadEnvasada) {
        this.cantidadEnvasada = cantidadEnvasada;
    }

    
    @Column(name="Cantidad_Envase")
    public Integer getCantidadEnvase() {
        return this.cantidadEnvase;
    }
    
    public void setCantidadEnvase(Integer cantidadEnvase) {
        this.cantidadEnvase = cantidadEnvase;
    }

    
    @Column(name="Capacidad_Transporte", nullable=false, precision=12, scale=0)
    public float getCapacidadTransporte() {
        return this.capacidadTransporte;
    }
    
    public void setCapacidadTransporte(float capacidadTransporte) {
        this.capacidadTransporte = capacidadTransporte;
    }

    
    @Column(name="Observaciones", length=450)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    
    @Column(name="Matricula_Vehiculo", nullable=false, length=45)
    public String getMatriculaVehiculo() {
        return this.matriculaVehiculo;
    }
    
    public void setMatriculaVehiculo(String matriculaVehiculo) {
        this.matriculaVehiculo = matriculaVehiculo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Edicion", length=19)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

    
    @Column(name="Status_Cerrada")
    public Boolean getStatusCerrada() {
        return this.statusCerrada;
    }
    
    public void setStatusCerrada(Boolean statusCerrada) {
        this.statusCerrada = statusCerrada;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR4Cabecera")
    public Set<DatR3Cabecera> getDatR3Cabeceras() {
        return this.datR3Cabeceras;
    }
    
    public void setDatR3Cabeceras(Set<DatR3Cabecera> datR3Cabeceras) {
        this.datR3Cabeceras = datR3Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR4Cabecera")
    public Set<DatR5Origen> getDatR5Origens() {
        return this.datR5Origens;
    }
    
    public void setDatR5Origens(Set<DatR5Origen> datR5Origens) {
        this.datR5Origens = datR5Origens;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR4Cabecera")
    public Set<DatR4Cabecera> getDatR4Cabeceras() {
        return this.datR4Cabeceras;
    }
    
    public void setDatR4Cabeceras(Set<DatR4Cabecera> datR4Cabeceras) {
        this.datR4Cabeceras = datR4Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR4Cabecera")
    public Set<DatAlerta> getDatAlertas() {
        return this.datAlertas;
    }
    
    public void setDatAlertas(Set<DatAlerta> datAlertas) {
        this.datAlertas = datAlertas;
    }




}


