package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatR5Ciclo generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Ciclo"
    ,catalog="sisem"
)
public class DatR5Ciclo  implements java.io.Serializable {


     private Integer idR5Ciclo;
     private CatFechaCiclo catFechaCiclo;
     private CatCicloAgricola catCicloAgricola;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5Ciclo() {
    }

	
    public DatR5Ciclo(CatFechaCiclo catFechaCiclo, CatCicloAgricola catCicloAgricola) {
        this.catFechaCiclo = catFechaCiclo;
        this.catCicloAgricola = catCicloAgricola;
    }
    public DatR5Ciclo(CatFechaCiclo catFechaCiclo, CatCicloAgricola catCicloAgricola, Set<DatR5Cabecera> datR5Cabeceras) {
       this.catFechaCiclo = catFechaCiclo;
       this.catCicloAgricola = catCicloAgricola;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Ciclo", unique=true, nullable=false)
    public Integer getIdR5Ciclo() {
        return this.idR5Ciclo;
    }
    
    public void setIdR5Ciclo(Integer idR5Ciclo) {
        this.idR5Ciclo = idR5Ciclo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Fecha_Ciclo", nullable=false)
    public CatFechaCiclo getCatFechaCiclo() {
        return this.catFechaCiclo;
    }
    
    public void setCatFechaCiclo(CatFechaCiclo catFechaCiclo) {
        this.catFechaCiclo = catFechaCiclo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Ciclo_Agricola", nullable=false)
    public CatCicloAgricola getCatCicloAgricola() {
        return this.catCicloAgricola;
    }
    
    public void setCatCicloAgricola(CatCicloAgricola catCicloAgricola) {
        this.catCicloAgricola = catCicloAgricola;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5Ciclo")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


