package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatRepresentanteLegal generated by hbm2java
 */
@Entity
@Table(name="Dat_Representante_Legal"
    ,catalog="sisem"
)
public class DatRepresentanteLegal  implements java.io.Serializable {


     private Integer idRepresentanteLegal;
     private DatOrganismo datOrganismo;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private Integer claveLada;
     private Integer telefono;
     private String correoElectronico;
     private Set<DatA5Cabecera> datA5Cabeceras = new HashSet<DatA5Cabecera>(0);

    public DatRepresentanteLegal() {
    }

	
    public DatRepresentanteLegal(DatOrganismo datOrganismo, String nombre, String apellidoPaterno, String apellidoMaterno) {
        this.datOrganismo = datOrganismo;
        this.nombre = nombre;
        this.apellidoPaterno = apellidoPaterno;
        this.apellidoMaterno = apellidoMaterno;
    }
    public DatRepresentanteLegal(DatOrganismo datOrganismo, String nombre, String apellidoPaterno, String apellidoMaterno, Integer claveLada, Integer telefono, String correoElectronico, Set<DatA5Cabecera> datA5Cabeceras) {
       this.datOrganismo = datOrganismo;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.claveLada = claveLada;
       this.telefono = telefono;
       this.correoElectronico = correoElectronico;
       this.datA5Cabeceras = datA5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Representante_Legal", unique=true, nullable=false)
    public Integer getIdRepresentanteLegal() {
        return this.idRepresentanteLegal;
    }
    
    public void setIdRepresentanteLegal(Integer idRepresentanteLegal) {
        this.idRepresentanteLegal = idRepresentanteLegal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo", nullable=false)
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

    
    @Column(name="Nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido Paterno", nullable=false, length=45)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="Apellido Materno", nullable=false, length=45)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    
    @Column(name="Clave_Lada")
    public Integer getClaveLada() {
        return this.claveLada;
    }
    
    public void setClaveLada(Integer claveLada) {
        this.claveLada = claveLada;
    }

    
    @Column(name="Telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="Correo_Electronico", length=50)
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datRepresentanteLegal")
    public Set<DatA5Cabecera> getDatA5Cabeceras() {
        return this.datA5Cabeceras;
    }
    
    public void setDatA5Cabeceras(Set<DatA5Cabecera> datA5Cabeceras) {
        this.datA5Cabeceras = datA5Cabeceras;
    }




}


