package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatR3Cabecera generated by hbm2java
 */
@Entity
@Table(name="Dat_R3_Cabecera"
    ,catalog="sisem"
)
public class DatR3Cabecera  implements java.io.Serializable {


     private Integer idR3Cabecera;
     private DatR4Cabecera datR4Cabecera;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaVehiculo;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaCantidad;
     private DatR1Inspeccion datR1Inspeccion;
     private CatStatusMovilizacion catStatusMovilizacion;
     private CatUnidadSnics catUnidadSnics;
     private DatUsuario datUsuarioByIdUsuarioCreacion;
     private DatUsuario datUsuarioByIdUsuarioEdicion;
     private DatR3Cabecera datR3Cabecera;
     private CatMunicipio catMunicipio;
     private DatOrganismo datOrganismo;
     private int numeroRemision;
     private float cantidad;
     private float capacidadVehiculo;
     private String observaciones;
     private Date fechaCreacion;
     private boolean status;
     private Boolean statusCerrada;
     private Date fechaEdicion;
     private Set<DatR3Cabecera> datR3Cabeceras = new HashSet<DatR3Cabecera>(0);
     private Set<DatAlerta> datAlertas = new HashSet<DatAlerta>(0);
     private Set<DatR4Cabecera> datR4Cabeceras = new HashSet<DatR4Cabecera>(0);
     private Set<DatR5Origen> datR5Origens = new HashSet<DatR5Origen>(0);

    public DatR3Cabecera() {
    }

	
    public DatR3Cabecera(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaVehiculo, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaCantidad, DatR1Inspeccion datR1Inspeccion, CatStatusMovilizacion catStatusMovilizacion, CatUnidadSnics catUnidadSnics, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, CatMunicipio catMunicipio, DatOrganismo datOrganismo, int numeroRemision, float cantidad, float capacidadVehiculo, Date fechaCreacion, boolean status) {
        this.catUnidadMedidaByIdUnidadMedidaVehiculo = catUnidadMedidaByIdUnidadMedidaVehiculo;
        this.catUnidadMedidaByIdUnidadMedidaCantidad = catUnidadMedidaByIdUnidadMedidaCantidad;
        this.datR1Inspeccion = datR1Inspeccion;
        this.catStatusMovilizacion = catStatusMovilizacion;
        this.catUnidadSnics = catUnidadSnics;
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
        this.catMunicipio = catMunicipio;
        this.datOrganismo = datOrganismo;
        this.numeroRemision = numeroRemision;
        this.cantidad = cantidad;
        this.capacidadVehiculo = capacidadVehiculo;
        this.fechaCreacion = fechaCreacion;
        this.status = status;
    }
    public DatR3Cabecera(DatR4Cabecera datR4Cabecera, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaVehiculo, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaCantidad, DatR1Inspeccion datR1Inspeccion, CatStatusMovilizacion catStatusMovilizacion, CatUnidadSnics catUnidadSnics, DatUsuario datUsuarioByIdUsuarioCreacion, DatUsuario datUsuarioByIdUsuarioEdicion, DatR3Cabecera datR3Cabecera, CatMunicipio catMunicipio, DatOrganismo datOrganismo, int numeroRemision, float cantidad, float capacidadVehiculo, String observaciones, Date fechaCreacion, boolean status, Boolean statusCerrada, Date fechaEdicion, Set<DatR3Cabecera> datR3Cabeceras, Set<DatAlerta> datAlertas, Set<DatR4Cabecera> datR4Cabeceras, Set<DatR5Origen> datR5Origens) {
       this.datR4Cabecera = datR4Cabecera;
       this.catUnidadMedidaByIdUnidadMedidaVehiculo = catUnidadMedidaByIdUnidadMedidaVehiculo;
       this.catUnidadMedidaByIdUnidadMedidaCantidad = catUnidadMedidaByIdUnidadMedidaCantidad;
       this.datR1Inspeccion = datR1Inspeccion;
       this.catStatusMovilizacion = catStatusMovilizacion;
       this.catUnidadSnics = catUnidadSnics;
       this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
       this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
       this.datR3Cabecera = datR3Cabecera;
       this.catMunicipio = catMunicipio;
       this.datOrganismo = datOrganismo;
       this.numeroRemision = numeroRemision;
       this.cantidad = cantidad;
       this.capacidadVehiculo = capacidadVehiculo;
       this.observaciones = observaciones;
       this.fechaCreacion = fechaCreacion;
       this.status = status;
       this.statusCerrada = statusCerrada;
       this.fechaEdicion = fechaEdicion;
       this.datR3Cabeceras = datR3Cabeceras;
       this.datAlertas = datAlertas;
       this.datR4Cabeceras = datR4Cabeceras;
       this.datR5Origens = datR5Origens;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R3_Cabecera", unique=true, nullable=false)
    public Integer getIdR3Cabecera() {
        return this.idR3Cabecera;
    }
    
    public void setIdR3Cabecera(Integer idR3Cabecera) {
        this.idR3Cabecera = idR3Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R4_Cabecera_Padre")
    public DatR4Cabecera getDatR4Cabecera() {
        return this.datR4Cabecera;
    }
    
    public void setDatR4Cabecera(DatR4Cabecera datR4Cabecera) {
        this.datR4Cabecera = datR4Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Vehiculo", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaVehiculo() {
        return this.catUnidadMedidaByIdUnidadMedidaVehiculo;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaVehiculo(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaVehiculo) {
        this.catUnidadMedidaByIdUnidadMedidaVehiculo = catUnidadMedidaByIdUnidadMedidaVehiculo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Cantidad", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaCantidad() {
        return this.catUnidadMedidaByIdUnidadMedidaCantidad;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaCantidad(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaCantidad) {
        this.catUnidadMedidaByIdUnidadMedidaCantidad = catUnidadMedidaByIdUnidadMedidaCantidad;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R1_Inspeccion", nullable=false)
    public DatR1Inspeccion getDatR1Inspeccion() {
        return this.datR1Inspeccion;
    }
    
    public void setDatR1Inspeccion(DatR1Inspeccion datR1Inspeccion) {
        this.datR1Inspeccion = datR1Inspeccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Status_Movilizacion", nullable=false)
    public CatStatusMovilizacion getCatStatusMovilizacion() {
        return this.catStatusMovilizacion;
    }
    
    public void setCatStatusMovilizacion(CatStatusMovilizacion catStatusMovilizacion) {
        this.catStatusMovilizacion = catStatusMovilizacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Snics_Recibe", nullable=false)
    public CatUnidadSnics getCatUnidadSnics() {
        return this.catUnidadSnics;
    }
    
    public void setCatUnidadSnics(CatUnidadSnics catUnidadSnics) {
        this.catUnidadSnics = catUnidadSnics;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioCreacion() {
        return this.datUsuarioByIdUsuarioCreacion;
    }
    
    public void setDatUsuarioByIdUsuarioCreacion(DatUsuario datUsuarioByIdUsuarioCreacion) {
        this.datUsuarioByIdUsuarioCreacion = datUsuarioByIdUsuarioCreacion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Edicion", nullable=false)
    public DatUsuario getDatUsuarioByIdUsuarioEdicion() {
        return this.datUsuarioByIdUsuarioEdicion;
    }
    
    public void setDatUsuarioByIdUsuarioEdicion(DatUsuario datUsuarioByIdUsuarioEdicion) {
        this.datUsuarioByIdUsuarioEdicion = datUsuarioByIdUsuarioEdicion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R3_Cabecera_Padre")
    public DatR3Cabecera getDatR3Cabecera() {
        return this.datR3Cabecera;
    }
    
    public void setDatR3Cabecera(DatR3Cabecera datR3Cabecera) {
        this.datR3Cabecera = datR3Cabecera;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo_Recibe", nullable=false)
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

    
    @Column(name="Numero_Remision", nullable=false)
    public int getNumeroRemision() {
        return this.numeroRemision;
    }
    
    public void setNumeroRemision(int numeroRemision) {
        this.numeroRemision = numeroRemision;
    }

    
    @Column(name="Cantidad", nullable=false, precision=12, scale=0)
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="Capacidad_vehiculo", nullable=false, precision=12, scale=0)
    public float getCapacidadVehiculo() {
        return this.capacidadVehiculo;
    }
    
    public void setCapacidadVehiculo(float capacidadVehiculo) {
        this.capacidadVehiculo = capacidadVehiculo;
    }

    
    @Column(name="Observaciones", length=500)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }

    
    @Column(name="Status_Cerrada")
    public Boolean getStatusCerrada() {
        return this.statusCerrada;
    }
    
    public void setStatusCerrada(Boolean statusCerrada) {
        this.statusCerrada = statusCerrada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Edicion", length=19)
    public Date getFechaEdicion() {
        return this.fechaEdicion;
    }
    
    public void setFechaEdicion(Date fechaEdicion) {
        this.fechaEdicion = fechaEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR3Cabecera")
    public Set<DatR3Cabecera> getDatR3Cabeceras() {
        return this.datR3Cabeceras;
    }
    
    public void setDatR3Cabeceras(Set<DatR3Cabecera> datR3Cabeceras) {
        this.datR3Cabeceras = datR3Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR3Cabecera")
    public Set<DatAlerta> getDatAlertas() {
        return this.datAlertas;
    }
    
    public void setDatAlertas(Set<DatAlerta> datAlertas) {
        this.datAlertas = datAlertas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR3Cabecera")
    public Set<DatR4Cabecera> getDatR4Cabeceras() {
        return this.datR4Cabeceras;
    }
    
    public void setDatR4Cabeceras(Set<DatR4Cabecera> datR4Cabeceras) {
        this.datR4Cabeceras = datR4Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR3Cabecera")
    public Set<DatR5Origen> getDatR5Origens() {
        return this.datR5Origens;
    }
    
    public void setDatR5Origens(Set<DatR5Origen> datR5Origens) {
        this.datR5Origens = datR5Origens;
    }




}


