package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatR5MateriaPrima generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Materia_Prima"
    ,catalog="sisem"
)
public class DatR5MateriaPrima  implements java.io.Serializable {


     private Integer idR5MateriaPrima;
     private CatUnidadMedida catUnidadMedida;
     private float cantidadMuestreada;
     private Date fechaMuestreo;
     private String observaciones;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5MateriaPrima() {
    }

	
    public DatR5MateriaPrima(CatUnidadMedida catUnidadMedida, float cantidadMuestreada, Date fechaMuestreo, String observaciones) {
        this.catUnidadMedida = catUnidadMedida;
        this.cantidadMuestreada = cantidadMuestreada;
        this.fechaMuestreo = fechaMuestreo;
        this.observaciones = observaciones;
    }
    public DatR5MateriaPrima(CatUnidadMedida catUnidadMedida, float cantidadMuestreada, Date fechaMuestreo, String observaciones, Set<DatR5Cabecera> datR5Cabeceras) {
       this.catUnidadMedida = catUnidadMedida;
       this.cantidadMuestreada = cantidadMuestreada;
       this.fechaMuestreo = fechaMuestreo;
       this.observaciones = observaciones;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Materia_Prima", unique=true, nullable=false)
    public Integer getIdR5MateriaPrima() {
        return this.idR5MateriaPrima;
    }
    
    public void setIdR5MateriaPrima(Integer idR5MateriaPrima) {
        this.idR5MateriaPrima = idR5MateriaPrima;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

    
    @Column(name="Cantidad_Muestreada", nullable=false, precision=12, scale=0)
    public float getCantidadMuestreada() {
        return this.cantidadMuestreada;
    }
    
    public void setCantidadMuestreada(float cantidadMuestreada) {
        this.cantidadMuestreada = cantidadMuestreada;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Muestreo", nullable=false, length=19)
    public Date getFechaMuestreo() {
        return this.fechaMuestreo;
    }
    
    public void setFechaMuestreo(Date fechaMuestreo) {
        this.fechaMuestreo = fechaMuestreo;
    }

    
    @Column(name="Observaciones", nullable=false, length=450)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5MateriaPrima")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


