package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DatR4Direccion generated by hbm2java
 */
@Entity
@Table(name="Dat_R4_Direccion"
    ,catalog="sisem"
)
public class DatR4Direccion  implements java.io.Serializable {


     private Integer idR4Direccion;
     private CatColonia catColonia;
     private CatEstado catEstado;
     private CatMunicipio catMunicipio;
     private CatUnidadSnics catUnidadSnics;
     private String calle;

    public DatR4Direccion() {
    }

    public DatR4Direccion(CatColonia catColonia, CatEstado catEstado, CatMunicipio catMunicipio, CatUnidadSnics catUnidadSnics, String calle) {
       this.catColonia = catColonia;
       this.catEstado = catEstado;
       this.catMunicipio = catMunicipio;
       this.catUnidadSnics = catUnidadSnics;
       this.calle = calle;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R4_Direccion", unique=true, nullable=false)
    public Integer getIdR4Direccion() {
        return this.idR4Direccion;
    }
    
    public void setIdR4Direccion(Integer idR4Direccion) {
        this.idR4Direccion = idR4Direccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Colonia", nullable=false)
    public CatColonia getCatColonia() {
        return this.catColonia;
    }
    
    public void setCatColonia(CatColonia catColonia) {
        this.catColonia = catColonia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Snics", nullable=false)
    public CatUnidadSnics getCatUnidadSnics() {
        return this.catUnidadSnics;
    }
    
    public void setCatUnidadSnics(CatUnidadSnics catUnidadSnics) {
        this.catUnidadSnics = catUnidadSnics;
    }

    
    @Column(name="Calle", nullable=false, length=100)
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }




}


