package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DatR1Predio generated by hbm2java
 */
@Entity
@Table(name="Dat_R1_Predio"
    ,catalog="sisem"
)
public class DatR1Predio  implements java.io.Serializable {


     private Integer idR1Periodo;
     private CatColonia catColonia;
     private CatEstado catEstado;
     private CatMunicipio catMunicipio;
     private DatR1Cabecera datR1Cabecera;
     private String nombrePredio;

    public DatR1Predio() {
    }

    public DatR1Predio(CatColonia catColonia, CatEstado catEstado, CatMunicipio catMunicipio, DatR1Cabecera datR1Cabecera, String nombrePredio) {
       this.catColonia = catColonia;
       this.catEstado = catEstado;
       this.catMunicipio = catMunicipio;
       this.datR1Cabecera = datR1Cabecera;
       this.nombrePredio = nombrePredio;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="datR1Cabecera"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Id_R1_Periodo", unique=true, nullable=false)
    public Integer getIdR1Periodo() {
        return this.idR1Periodo;
    }
    
    public void setIdR1Periodo(Integer idR1Periodo) {
        this.idR1Periodo = idR1Periodo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Colonia", nullable=false)
    public CatColonia getCatColonia() {
        return this.catColonia;
    }
    
    public void setCatColonia(CatColonia catColonia) {
        this.catColonia = catColonia;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Estado", nullable=false)
    public CatEstado getCatEstado() {
        return this.catEstado;
    }
    
    public void setCatEstado(CatEstado catEstado) {
        this.catEstado = catEstado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Municipio", nullable=false)
    public CatMunicipio getCatMunicipio() {
        return this.catMunicipio;
    }
    
    public void setCatMunicipio(CatMunicipio catMunicipio) {
        this.catMunicipio = catMunicipio;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public DatR1Cabecera getDatR1Cabecera() {
        return this.datR1Cabecera;
    }
    
    public void setDatR1Cabecera(DatR1Cabecera datR1Cabecera) {
        this.datR1Cabecera = datR1Cabecera;
    }

    
    @Column(name="Nombre_Predio", nullable=false, length=45)
    public String getNombrePredio() {
        return this.nombrePredio;
    }
    
    public void setNombrePredio(String nombrePredio) {
        this.nombrePredio = nombrePredio;
    }




}


