package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatR5Detalle generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Detalle"
    ,catalog="sisem"
)
public class DatR5Detalle  implements java.io.Serializable {


     private Integer idR5Detalle;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasada;
     private CatVariedadCultivo catVariedadCultivo;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel;
     private CatCategoria catCategoria;
     private CatTipoEnvase catTipoEnvase;
     private CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvase;
     private String numeroLote;
     private Float cantidadGranel;
     private Float cantidadEnvasada;
     private String numeroEnvases;
     private Float capacidadEnvases;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5Detalle() {
    }

	
    public DatR5Detalle(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasada, CatVariedadCultivo catVariedadCultivo, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel, CatCategoria catCategoria, CatTipoEnvase catTipoEnvase, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvase) {
        this.catUnidadMedidaByIdUnidadMedidaEnvasada = catUnidadMedidaByIdUnidadMedidaEnvasada;
        this.catVariedadCultivo = catVariedadCultivo;
        this.catUnidadMedidaByIdUnidadMedidaGranel = catUnidadMedidaByIdUnidadMedidaGranel;
        this.catCategoria = catCategoria;
        this.catTipoEnvase = catTipoEnvase;
        this.catUnidadMedidaByIdUnidadMedidaEnvase = catUnidadMedidaByIdUnidadMedidaEnvase;
    }
    public DatR5Detalle(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasada, CatVariedadCultivo catVariedadCultivo, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel, CatCategoria catCategoria, CatTipoEnvase catTipoEnvase, CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvase, String numeroLote, Float cantidadGranel, Float cantidadEnvasada, String numeroEnvases, Float capacidadEnvases, Set<DatR5Cabecera> datR5Cabeceras) {
       this.catUnidadMedidaByIdUnidadMedidaEnvasada = catUnidadMedidaByIdUnidadMedidaEnvasada;
       this.catVariedadCultivo = catVariedadCultivo;
       this.catUnidadMedidaByIdUnidadMedidaGranel = catUnidadMedidaByIdUnidadMedidaGranel;
       this.catCategoria = catCategoria;
       this.catTipoEnvase = catTipoEnvase;
       this.catUnidadMedidaByIdUnidadMedidaEnvase = catUnidadMedidaByIdUnidadMedidaEnvase;
       this.numeroLote = numeroLote;
       this.cantidadGranel = cantidadGranel;
       this.cantidadEnvasada = cantidadEnvasada;
       this.numeroEnvases = numeroEnvases;
       this.capacidadEnvases = capacidadEnvases;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Detalle", unique=true, nullable=false)
    public Integer getIdR5Detalle() {
        return this.idR5Detalle;
    }
    
    public void setIdR5Detalle(Integer idR5Detalle) {
        this.idR5Detalle = idR5Detalle;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Envasada", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaEnvasada() {
        return this.catUnidadMedidaByIdUnidadMedidaEnvasada;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaEnvasada(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvasada) {
        this.catUnidadMedidaByIdUnidadMedidaEnvasada = catUnidadMedidaByIdUnidadMedidaEnvasada;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Variedad_Cultivo", nullable=false)
    public CatVariedadCultivo getCatVariedadCultivo() {
        return this.catVariedadCultivo;
    }
    
    public void setCatVariedadCultivo(CatVariedadCultivo catVariedadCultivo) {
        this.catVariedadCultivo = catVariedadCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Granel", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaGranel() {
        return this.catUnidadMedidaByIdUnidadMedidaGranel;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaGranel(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaGranel) {
        this.catUnidadMedidaByIdUnidadMedidaGranel = catUnidadMedidaByIdUnidadMedidaGranel;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria", nullable=false)
    public CatCategoria getCatCategoria() {
        return this.catCategoria;
    }
    
    public void setCatCategoria(CatCategoria catCategoria) {
        this.catCategoria = catCategoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Tipo_Envase", nullable=false)
    public CatTipoEnvase getCatTipoEnvase() {
        return this.catTipoEnvase;
    }
    
    public void setCatTipoEnvase(CatTipoEnvase catTipoEnvase) {
        this.catTipoEnvase = catTipoEnvase;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Envase", nullable=false)
    public CatUnidadMedida getCatUnidadMedidaByIdUnidadMedidaEnvase() {
        return this.catUnidadMedidaByIdUnidadMedidaEnvase;
    }
    
    public void setCatUnidadMedidaByIdUnidadMedidaEnvase(CatUnidadMedida catUnidadMedidaByIdUnidadMedidaEnvase) {
        this.catUnidadMedidaByIdUnidadMedidaEnvase = catUnidadMedidaByIdUnidadMedidaEnvase;
    }

    
    @Column(name="Numero_Lote", length=45)
    public String getNumeroLote() {
        return this.numeroLote;
    }
    
    public void setNumeroLote(String numeroLote) {
        this.numeroLote = numeroLote;
    }

    
    @Column(name="Cantidad_Granel", precision=12, scale=0)
    public Float getCantidadGranel() {
        return this.cantidadGranel;
    }
    
    public void setCantidadGranel(Float cantidadGranel) {
        this.cantidadGranel = cantidadGranel;
    }

    
    @Column(name="Cantidad_Envasada", precision=12, scale=0)
    public Float getCantidadEnvasada() {
        return this.cantidadEnvasada;
    }
    
    public void setCantidadEnvasada(Float cantidadEnvasada) {
        this.cantidadEnvasada = cantidadEnvasada;
    }

    
    @Column(name="Numero_Envases", length=45)
    public String getNumeroEnvases() {
        return this.numeroEnvases;
    }
    
    public void setNumeroEnvases(String numeroEnvases) {
        this.numeroEnvases = numeroEnvases;
    }

    
    @Column(name="Capacidad_Envases", precision=12, scale=0)
    public Float getCapacidadEnvases() {
        return this.capacidadEnvases;
    }
    
    public void setCapacidadEnvases(Float capacidadEnvases) {
        this.capacidadEnvases = capacidadEnvases;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5Detalle")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


