package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DatR1Categoria generated by hbm2java
 */
@Entity
@Table(name="Dat_R1_Categoria"
    ,catalog="sisem"
)
public class DatR1Categoria  implements java.io.Serializable {


     private Integer idR1Categoria;
     private CatCategoriaProduccion catCategoriaProduccion;
     private DatR1Cabecera datR1Cabecera;
     private Date fechaAutorizacion;
     private Integer numeroAutorizacion;

    public DatR1Categoria() {
    }

	
    public DatR1Categoria(CatCategoriaProduccion catCategoriaProduccion, DatR1Cabecera datR1Cabecera) {
        this.catCategoriaProduccion = catCategoriaProduccion;
        this.datR1Cabecera = datR1Cabecera;
    }
    public DatR1Categoria(CatCategoriaProduccion catCategoriaProduccion, DatR1Cabecera datR1Cabecera, Date fechaAutorizacion, Integer numeroAutorizacion) {
       this.catCategoriaProduccion = catCategoriaProduccion;
       this.datR1Cabecera = datR1Cabecera;
       this.fechaAutorizacion = fechaAutorizacion;
       this.numeroAutorizacion = numeroAutorizacion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R1_Categoria", unique=true, nullable=false)
    public Integer getIdR1Categoria() {
        return this.idR1Categoria;
    }
    
    public void setIdR1Categoria(Integer idR1Categoria) {
        this.idR1Categoria = idR1Categoria;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria_Produccion", nullable=false)
    public CatCategoriaProduccion getCatCategoriaProduccion() {
        return this.catCategoriaProduccion;
    }
    
    public void setCatCategoriaProduccion(CatCategoriaProduccion catCategoriaProduccion) {
        this.catCategoriaProduccion = catCategoriaProduccion;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_R1_Cabecera", nullable=false)
    public DatR1Cabecera getDatR1Cabecera() {
        return this.datR1Cabecera;
    }
    
    public void setDatR1Cabecera(DatR1Cabecera datR1Cabecera) {
        this.datR1Cabecera = datR1Cabecera;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Autorizacion", length=19)
    public Date getFechaAutorizacion() {
        return this.fechaAutorizacion;
    }
    
    public void setFechaAutorizacion(Date fechaAutorizacion) {
        this.fechaAutorizacion = fechaAutorizacion;
    }

    
    @Column(name="Numero Autorizacion")
    public Integer getNumeroAutorizacion() {
        return this.numeroAutorizacion;
    }
    
    public void setNumeroAutorizacion(Integer numeroAutorizacion) {
        this.numeroAutorizacion = numeroAutorizacion;
    }




}


