package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatR5Transporte generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Transporte"
    ,catalog="sisem"
)
public class DatR5Transporte  implements java.io.Serializable {


     private Integer idR5Transporte;
     private CatUnidadMedida catUnidadMedida;
     private String matricula;
     private float capacidad;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5Transporte() {
    }

	
    public DatR5Transporte(CatUnidadMedida catUnidadMedida, String matricula, float capacidad) {
        this.catUnidadMedida = catUnidadMedida;
        this.matricula = matricula;
        this.capacidad = capacidad;
    }
    public DatR5Transporte(CatUnidadMedida catUnidadMedida, String matricula, float capacidad, Set<DatR5Cabecera> datR5Cabeceras) {
       this.catUnidadMedida = catUnidadMedida;
       this.matricula = matricula;
       this.capacidad = capacidad;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Transporte", unique=true, nullable=false)
    public Integer getIdR5Transporte() {
        return this.idR5Transporte;
    }
    
    public void setIdR5Transporte(Integer idR5Transporte) {
        this.idR5Transporte = idR5Transporte;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Transporte", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

    
    @Column(name="Matricula", nullable=false, length=45)
    public String getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(String matricula) {
        this.matricula = matricula;
    }

    
    @Column(name="Capacidad", nullable=false, precision=12, scale=0)
    public float getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(float capacidad) {
        this.capacidad = capacidad;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5Transporte")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


