package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatR5Estiba generated by hbm2java
 */
@Entity
@Table(name="Dat_R5_Estiba"
    ,catalog="sisem"
)
public class DatR5Estiba  implements java.io.Serializable {


     private Integer idR5Estiba;
     private CatUnidadMedida catUnidadMedida;
     private CatLugarMuestreo catLugarMuestreo;
     private Integer cantidadEstiba;
     private Integer maxEstiba;
     private String identificacion;
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);

    public DatR5Estiba() {
    }

	
    public DatR5Estiba(CatUnidadMedida catUnidadMedida, CatLugarMuestreo catLugarMuestreo) {
        this.catUnidadMedida = catUnidadMedida;
        this.catLugarMuestreo = catLugarMuestreo;
    }
    public DatR5Estiba(CatUnidadMedida catUnidadMedida, CatLugarMuestreo catLugarMuestreo, Integer cantidadEstiba, Integer maxEstiba, String identificacion, Set<DatR5Cabecera> datR5Cabeceras) {
       this.catUnidadMedida = catUnidadMedida;
       this.catLugarMuestreo = catLugarMuestreo;
       this.cantidadEstiba = cantidadEstiba;
       this.maxEstiba = maxEstiba;
       this.identificacion = identificacion;
       this.datR5Cabeceras = datR5Cabeceras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_R5_Estiba", unique=true, nullable=false)
    public Integer getIdR5Estiba() {
        return this.idR5Estiba;
    }
    
    public void setIdR5Estiba(Integer idR5Estiba) {
        this.idR5Estiba = idR5Estiba;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida_Estiba", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Lugar_Muestreo", nullable=false)
    public CatLugarMuestreo getCatLugarMuestreo() {
        return this.catLugarMuestreo;
    }
    
    public void setCatLugarMuestreo(CatLugarMuestreo catLugarMuestreo) {
        this.catLugarMuestreo = catLugarMuestreo;
    }

    
    @Column(name="Cantidad_Estiba")
    public Integer getCantidadEstiba() {
        return this.cantidadEstiba;
    }
    
    public void setCantidadEstiba(Integer cantidadEstiba) {
        this.cantidadEstiba = cantidadEstiba;
    }

    
    @Column(name="Max_Estiba")
    public Integer getMaxEstiba() {
        return this.maxEstiba;
    }
    
    public void setMaxEstiba(Integer maxEstiba) {
        this.maxEstiba = maxEstiba;
    }

    
    @Column(name="Identificacion", length=45)
    public String getIdentificacion() {
        return this.identificacion;
    }
    
    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datR5Estiba")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }




}


