package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DatSerieExistencias generated by hbm2java
 */
@Entity
@Table(name="Dat_Serie_Existencias"
    ,catalog="sisem"
)
public class DatSerieExistencias  implements java.io.Serializable {


     private Integer idSerieExistencias;
     private DatExistenciasEtiquetas datExistenciasEtiquetas;
     private int idFoliosExistencias;
     private String serie;

    public DatSerieExistencias() {
    }

    public DatSerieExistencias(DatExistenciasEtiquetas datExistenciasEtiquetas, int idFoliosExistencias, String serie) {
       this.datExistenciasEtiquetas = datExistenciasEtiquetas;
       this.idFoliosExistencias = idFoliosExistencias;
       this.serie = serie;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="datExistenciasEtiquetas"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="Id_Serie_Existencias", unique=true, nullable=false)
    public Integer getIdSerieExistencias() {
        return this.idSerieExistencias;
    }
    
    public void setIdSerieExistencias(Integer idSerieExistencias) {
        this.idSerieExistencias = idSerieExistencias;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public DatExistenciasEtiquetas getDatExistenciasEtiquetas() {
        return this.datExistenciasEtiquetas;
    }
    
    public void setDatExistenciasEtiquetas(DatExistenciasEtiquetas datExistenciasEtiquetas) {
        this.datExistenciasEtiquetas = datExistenciasEtiquetas;
    }

    
    @Column(name="Id_Folios_Existencias", nullable=false)
    public int getIdFoliosExistencias() {
        return this.idFoliosExistencias;
    }
    
    public void setIdFoliosExistencias(int idFoliosExistencias) {
        this.idFoliosExistencias = idFoliosExistencias;
    }

    
    @Column(name="Serie", nullable=false, length=45)
    public String getSerie() {
        return this.serie;
    }
    
    public void setSerie(String serie) {
        this.serie = serie;
    }




}


