package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DatUsuario generated by hbm2java
 */
@Entity
@Table(name="Dat_Usuario"
    ,catalog="sisem"
)
public class DatUsuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String nombreUsuario;
     private String contrasena;
     private Boolean status;
     private Boolean handheld;
     private Set<DatSnowflake> datSnowflakes = new HashSet<DatSnowflake>(0);
     private Set<DatR3Cabecera> datR3CabecerasForIdUsuarioEdicion = new HashSet<DatR3Cabecera>(0);
     private Set<DatR3Cabecera> datR3CabecerasForIdUsuarioCreacion = new HashSet<DatR3Cabecera>(0);
     private Set<CatEquipoMuestreo> catEquipoMuestreosForIdUsuarioEdicion = new HashSet<CatEquipoMuestreo>(0);
     private Set<CatTipoDomicilio> catTipoDomiciliosForIdUsuarioEdicion = new HashSet<CatTipoDomicilio>(0);
     private Set<CatTipoMuestra> catTipoMuestrasForIdUsuarioEdicion = new HashSet<CatTipoMuestra>(0);
     private Set<CatTipoMuestra> catTipoMuestrasForIdUsuarioCreacion = new HashSet<CatTipoMuestra>(0);
     private Set<DatR7Inspeccion> datR7Inspeccions = new HashSet<DatR7Inspeccion>(0);
     private Set<CatFormaMuestreo> catFormaMuestreosForIdUsuarioCreacion = new HashSet<CatFormaMuestreo>(0);
     private Set<CatOrigen> catOrigensForIdUsuarioCreacion = new HashSet<CatOrigen>(0);
     private Set<DatR4Cabecera> datR4CabecerasForIdUsuarioCreacion = new HashSet<DatR4Cabecera>(0);
     private Set<LinkBoletinUsuario> linkBoletinUsuarios = new HashSet<LinkBoletinUsuario>(0);
     private Set<DatR4Cabecera> datR4CabecerasForIdUsuarioEdicion = new HashSet<DatR4Cabecera>(0);
     private Set<CatLugarMuestreo> catLugarMuestreosForIdUsuarioCreacion = new HashSet<CatLugarMuestreo>(0);
     private Set<CatEspecie> catEspeciesForIdUsuarioCreacion = new HashSet<CatEspecie>(0);
     private Set<CatTipoPlanta> catTipoPlantasForIdUsuarioEdicion = new HashSet<CatTipoPlanta>(0);
     private Set<CatOrigen> catOrigensForIdUsuarioEdicion = new HashSet<CatOrigen>(0);
     private Set<CatFormaMuestreo> catFormaMuestreosForIdUsuarioEdicion = new HashSet<CatFormaMuestreo>(0);
     private Set<CatTipoEnvase> catTipoEnvasesForIdUsuarioEdicion = new HashSet<CatTipoEnvase>(0);
     private Set<CatProblemasSupervision> catProblemasSupervisionsForIdUsuarioEdicion = new HashSet<CatProblemasSupervision>(0);
     private Set<DatR1Cabecera> datR1Cabeceras = new HashSet<DatR1Cabecera>(0);
     private Set<CatModalidad> catModalidadsForIdUsuarioEdicion = new HashSet<CatModalidad>(0);
     private Set<LinkRolUsuario> linkRolUsuarios = new HashSet<LinkRolUsuario>(0);
     private Set<CatEquipoMuestreo> catEquipoMuestreosForIdUsuarioCreacion = new HashSet<CatEquipoMuestreo>(0);
     private Set<DatA5Cabecera> datA5Cabeceras = new HashSet<DatA5Cabecera>(0);
     private Set<CatCicloAgricola> catCicloAgricolasForIdUsuarioEdicion = new HashSet<CatCicloAgricola>(0);
     private Set<LinkRolPermiso> linkRolPermisos = new HashSet<LinkRolPermiso>(0);
     private Set<CatModalidad> catModalidadsForIdUsuarioCreacion = new HashSet<CatModalidad>(0);
     private Set<CatCicloAgricola> catCicloAgricolasForIdUsuarioCreacion = new HashSet<CatCicloAgricola>(0);
     private Set<CatProblemasSupervision> catProblemasSupervisionsForIdUsuarioCreacion = new HashSet<CatProblemasSupervision>(0);
     private Set<CatTipoEnvase> catTipoEnvasesForIdUsuarioCreacion = new HashSet<CatTipoEnvase>(0);
     private Set<DatLaboratorioCabecera> datLaboratorioCabecerasForIdUsuarioCreacion = new HashSet<DatLaboratorioCabecera>(0);
     private Set<DatR7Cabecera> datR7Cabeceras = new HashSet<DatR7Cabecera>(0);
     private Set<DatLaboratorioCabecera> datLaboratorioCabecerasForIdUsuarioEdicion = new HashSet<DatLaboratorioCabecera>(0);
     private Set<CatSustrato> catSustratosForIdUsuarioEdicion = new HashSet<CatSustrato>(0);
     private Set<CatActividadesOrganismo> catActividadesOrganismosForIdUsuarioCreacion = new HashSet<CatActividadesOrganismo>(0);
     private Set<CatActividadesOrganismo> catActividadesOrganismosForIdUsuarioEdicion = new HashSet<CatActividadesOrganismo>(0);
     private Set<CatSustrato> catSustratosForIdUsuarioCreacion = new HashSet<CatSustrato>(0);
     private Set<DatOrganismo> datOrganismos = new HashSet<DatOrganismo>(0);
     private Set<CatCondicionCultivo> catCondicionCultivosForIdUsuarioEdicion = new HashSet<CatCondicionCultivo>(0);
     private Set<DatR1Inspeccion> datR1Inspeccions = new HashSet<DatR1Inspeccion>(0);
     private Set<CatTipoDomicilio> catTipoDomiciliosForIdUsuarioCreacion = new HashSet<CatTipoDomicilio>(0);
     private Set<DatR5Cabecera> datR5Cabeceras = new HashSet<DatR5Cabecera>(0);
     private Set<CatTipoPlanta> catTipoPlantasForIdUsuarioCreacion = new HashSet<CatTipoPlanta>(0);
     private Set<CatEspecie> catEspeciesForIdUsuarioEdicion = new HashSet<CatEspecie>(0);
     private Set<CatLugarMuestreo> catLugarMuestreosForIdUsuarioEdicion = new HashSet<CatLugarMuestreo>(0);
     private Set<CatCondicionCultivo> catCondicionCultivosForIdUsuarioCreacion = new HashSet<CatCondicionCultivo>(0);
     private Set<CatCategoria> catCategoriasForIdUsuarioCreacion = new HashSet<CatCategoria>(0);
     private Set<CatUnidadMedida> catUnidadMedidasForIdUsuarioCreacion = new HashSet<CatUnidadMedida>(0);
     private Set<CatUnidadMedida> catUnidadMedidasForIdUsuarioEdicion = new HashSet<CatUnidadMedida>(0);
     private Set<CatCategoria> catCategoriasForIdUsuarioEdicion = new HashSet<CatCategoria>(0);

    public DatUsuario() {
    }

    public DatUsuario(String nombre, String apellidoPaterno, String apellidoMaterno, String nombreUsuario, String contrasena, Boolean status, Boolean handheld, Set<DatSnowflake> datSnowflakes, Set<DatR3Cabecera> datR3CabecerasForIdUsuarioEdicion, Set<DatR3Cabecera> datR3CabecerasForIdUsuarioCreacion, Set<CatEquipoMuestreo> catEquipoMuestreosForIdUsuarioEdicion, Set<CatTipoDomicilio> catTipoDomiciliosForIdUsuarioEdicion, Set<CatTipoMuestra> catTipoMuestrasForIdUsuarioEdicion, Set<CatTipoMuestra> catTipoMuestrasForIdUsuarioCreacion, Set<DatR7Inspeccion> datR7Inspeccions, Set<CatFormaMuestreo> catFormaMuestreosForIdUsuarioCreacion, Set<CatOrigen> catOrigensForIdUsuarioCreacion, Set<DatR4Cabecera> datR4CabecerasForIdUsuarioCreacion, Set<LinkBoletinUsuario> linkBoletinUsuarios, Set<DatR4Cabecera> datR4CabecerasForIdUsuarioEdicion, Set<CatLugarMuestreo> catLugarMuestreosForIdUsuarioCreacion, Set<CatEspecie> catEspeciesForIdUsuarioCreacion, Set<CatTipoPlanta> catTipoPlantasForIdUsuarioEdicion, Set<CatOrigen> catOrigensForIdUsuarioEdicion, Set<CatFormaMuestreo> catFormaMuestreosForIdUsuarioEdicion, Set<CatTipoEnvase> catTipoEnvasesForIdUsuarioEdicion, Set<CatProblemasSupervision> catProblemasSupervisionsForIdUsuarioEdicion, Set<DatR1Cabecera> datR1Cabeceras, Set<CatModalidad> catModalidadsForIdUsuarioEdicion, Set<LinkRolUsuario> linkRolUsuarios, Set<CatEquipoMuestreo> catEquipoMuestreosForIdUsuarioCreacion, Set<DatA5Cabecera> datA5Cabeceras, Set<CatCicloAgricola> catCicloAgricolasForIdUsuarioEdicion, Set<LinkRolPermiso> linkRolPermisos, Set<CatModalidad> catModalidadsForIdUsuarioCreacion, Set<CatCicloAgricola> catCicloAgricolasForIdUsuarioCreacion, Set<CatProblemasSupervision> catProblemasSupervisionsForIdUsuarioCreacion, Set<CatTipoEnvase> catTipoEnvasesForIdUsuarioCreacion, Set<DatLaboratorioCabecera> datLaboratorioCabecerasForIdUsuarioCreacion, Set<DatR7Cabecera> datR7Cabeceras, Set<DatLaboratorioCabecera> datLaboratorioCabecerasForIdUsuarioEdicion, Set<CatSustrato> catSustratosForIdUsuarioEdicion, Set<CatActividadesOrganismo> catActividadesOrganismosForIdUsuarioCreacion, Set<CatActividadesOrganismo> catActividadesOrganismosForIdUsuarioEdicion, Set<CatSustrato> catSustratosForIdUsuarioCreacion, Set<DatOrganismo> datOrganismos, Set<CatCondicionCultivo> catCondicionCultivosForIdUsuarioEdicion, Set<DatR1Inspeccion> datR1Inspeccions, Set<CatTipoDomicilio> catTipoDomiciliosForIdUsuarioCreacion, Set<DatR5Cabecera> datR5Cabeceras, Set<CatTipoPlanta> catTipoPlantasForIdUsuarioCreacion, Set<CatEspecie> catEspeciesForIdUsuarioEdicion, Set<CatLugarMuestreo> catLugarMuestreosForIdUsuarioEdicion, Set<CatCondicionCultivo> catCondicionCultivosForIdUsuarioCreacion, Set<CatCategoria> catCategoriasForIdUsuarioCreacion, Set<CatUnidadMedida> catUnidadMedidasForIdUsuarioCreacion, Set<CatUnidadMedida> catUnidadMedidasForIdUsuarioEdicion, Set<CatCategoria> catCategoriasForIdUsuarioEdicion) {
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.nombreUsuario = nombreUsuario;
       this.contrasena = contrasena;
       this.status = status;
       this.handheld = handheld;
       this.datSnowflakes = datSnowflakes;
       this.datR3CabecerasForIdUsuarioEdicion = datR3CabecerasForIdUsuarioEdicion;
       this.datR3CabecerasForIdUsuarioCreacion = datR3CabecerasForIdUsuarioCreacion;
       this.catEquipoMuestreosForIdUsuarioEdicion = catEquipoMuestreosForIdUsuarioEdicion;
       this.catTipoDomiciliosForIdUsuarioEdicion = catTipoDomiciliosForIdUsuarioEdicion;
       this.catTipoMuestrasForIdUsuarioEdicion = catTipoMuestrasForIdUsuarioEdicion;
       this.catTipoMuestrasForIdUsuarioCreacion = catTipoMuestrasForIdUsuarioCreacion;
       this.datR7Inspeccions = datR7Inspeccions;
       this.catFormaMuestreosForIdUsuarioCreacion = catFormaMuestreosForIdUsuarioCreacion;
       this.catOrigensForIdUsuarioCreacion = catOrigensForIdUsuarioCreacion;
       this.datR4CabecerasForIdUsuarioCreacion = datR4CabecerasForIdUsuarioCreacion;
       this.linkBoletinUsuarios = linkBoletinUsuarios;
       this.datR4CabecerasForIdUsuarioEdicion = datR4CabecerasForIdUsuarioEdicion;
       this.catLugarMuestreosForIdUsuarioCreacion = catLugarMuestreosForIdUsuarioCreacion;
       this.catEspeciesForIdUsuarioCreacion = catEspeciesForIdUsuarioCreacion;
       this.catTipoPlantasForIdUsuarioEdicion = catTipoPlantasForIdUsuarioEdicion;
       this.catOrigensForIdUsuarioEdicion = catOrigensForIdUsuarioEdicion;
       this.catFormaMuestreosForIdUsuarioEdicion = catFormaMuestreosForIdUsuarioEdicion;
       this.catTipoEnvasesForIdUsuarioEdicion = catTipoEnvasesForIdUsuarioEdicion;
       this.catProblemasSupervisionsForIdUsuarioEdicion = catProblemasSupervisionsForIdUsuarioEdicion;
       this.datR1Cabeceras = datR1Cabeceras;
       this.catModalidadsForIdUsuarioEdicion = catModalidadsForIdUsuarioEdicion;
       this.linkRolUsuarios = linkRolUsuarios;
       this.catEquipoMuestreosForIdUsuarioCreacion = catEquipoMuestreosForIdUsuarioCreacion;
       this.datA5Cabeceras = datA5Cabeceras;
       this.catCicloAgricolasForIdUsuarioEdicion = catCicloAgricolasForIdUsuarioEdicion;
       this.linkRolPermisos = linkRolPermisos;
       this.catModalidadsForIdUsuarioCreacion = catModalidadsForIdUsuarioCreacion;
       this.catCicloAgricolasForIdUsuarioCreacion = catCicloAgricolasForIdUsuarioCreacion;
       this.catProblemasSupervisionsForIdUsuarioCreacion = catProblemasSupervisionsForIdUsuarioCreacion;
       this.catTipoEnvasesForIdUsuarioCreacion = catTipoEnvasesForIdUsuarioCreacion;
       this.datLaboratorioCabecerasForIdUsuarioCreacion = datLaboratorioCabecerasForIdUsuarioCreacion;
       this.datR7Cabeceras = datR7Cabeceras;
       this.datLaboratorioCabecerasForIdUsuarioEdicion = datLaboratorioCabecerasForIdUsuarioEdicion;
       this.catSustratosForIdUsuarioEdicion = catSustratosForIdUsuarioEdicion;
       this.catActividadesOrganismosForIdUsuarioCreacion = catActividadesOrganismosForIdUsuarioCreacion;
       this.catActividadesOrganismosForIdUsuarioEdicion = catActividadesOrganismosForIdUsuarioEdicion;
       this.catSustratosForIdUsuarioCreacion = catSustratosForIdUsuarioCreacion;
       this.datOrganismos = datOrganismos;
       this.catCondicionCultivosForIdUsuarioEdicion = catCondicionCultivosForIdUsuarioEdicion;
       this.datR1Inspeccions = datR1Inspeccions;
       this.catTipoDomiciliosForIdUsuarioCreacion = catTipoDomiciliosForIdUsuarioCreacion;
       this.datR5Cabeceras = datR5Cabeceras;
       this.catTipoPlantasForIdUsuarioCreacion = catTipoPlantasForIdUsuarioCreacion;
       this.catEspeciesForIdUsuarioEdicion = catEspeciesForIdUsuarioEdicion;
       this.catLugarMuestreosForIdUsuarioEdicion = catLugarMuestreosForIdUsuarioEdicion;
       this.catCondicionCultivosForIdUsuarioCreacion = catCondicionCultivosForIdUsuarioCreacion;
       this.catCategoriasForIdUsuarioCreacion = catCategoriasForIdUsuarioCreacion;
       this.catUnidadMedidasForIdUsuarioCreacion = catUnidadMedidasForIdUsuarioCreacion;
       this.catUnidadMedidasForIdUsuarioEdicion = catUnidadMedidasForIdUsuarioEdicion;
       this.catCategoriasForIdUsuarioEdicion = catCategoriasForIdUsuarioEdicion;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="Id_Usuario", unique=true, nullable=false)
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    
    @Column(name="Nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="Apellido_Paterno", length=45)
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }

    
    @Column(name="Apellido_Materno", length=45)
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }

    
    @Column(name="Nombre_Usuario", length=45)
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    
    @Column(name="contrasena", length=200)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }

    
    @Column(name="Status")
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    
    @Column(name="Handheld")
    public Boolean getHandheld() {
        return this.handheld;
    }
    
    public void setHandheld(Boolean handheld) {
        this.handheld = handheld;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatSnowflake> getDatSnowflakes() {
        return this.datSnowflakes;
    }
    
    public void setDatSnowflakes(Set<DatSnowflake> datSnowflakes) {
        this.datSnowflakes = datSnowflakes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<DatR3Cabecera> getDatR3CabecerasForIdUsuarioEdicion() {
        return this.datR3CabecerasForIdUsuarioEdicion;
    }
    
    public void setDatR3CabecerasForIdUsuarioEdicion(Set<DatR3Cabecera> datR3CabecerasForIdUsuarioEdicion) {
        this.datR3CabecerasForIdUsuarioEdicion = datR3CabecerasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<DatR3Cabecera> getDatR3CabecerasForIdUsuarioCreacion() {
        return this.datR3CabecerasForIdUsuarioCreacion;
    }
    
    public void setDatR3CabecerasForIdUsuarioCreacion(Set<DatR3Cabecera> datR3CabecerasForIdUsuarioCreacion) {
        this.datR3CabecerasForIdUsuarioCreacion = datR3CabecerasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatEquipoMuestreo> getCatEquipoMuestreosForIdUsuarioEdicion() {
        return this.catEquipoMuestreosForIdUsuarioEdicion;
    }
    
    public void setCatEquipoMuestreosForIdUsuarioEdicion(Set<CatEquipoMuestreo> catEquipoMuestreosForIdUsuarioEdicion) {
        this.catEquipoMuestreosForIdUsuarioEdicion = catEquipoMuestreosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatTipoDomicilio> getCatTipoDomiciliosForIdUsuarioEdicion() {
        return this.catTipoDomiciliosForIdUsuarioEdicion;
    }
    
    public void setCatTipoDomiciliosForIdUsuarioEdicion(Set<CatTipoDomicilio> catTipoDomiciliosForIdUsuarioEdicion) {
        this.catTipoDomiciliosForIdUsuarioEdicion = catTipoDomiciliosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatTipoMuestra> getCatTipoMuestrasForIdUsuarioEdicion() {
        return this.catTipoMuestrasForIdUsuarioEdicion;
    }
    
    public void setCatTipoMuestrasForIdUsuarioEdicion(Set<CatTipoMuestra> catTipoMuestrasForIdUsuarioEdicion) {
        this.catTipoMuestrasForIdUsuarioEdicion = catTipoMuestrasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatTipoMuestra> getCatTipoMuestrasForIdUsuarioCreacion() {
        return this.catTipoMuestrasForIdUsuarioCreacion;
    }
    
    public void setCatTipoMuestrasForIdUsuarioCreacion(Set<CatTipoMuestra> catTipoMuestrasForIdUsuarioCreacion) {
        this.catTipoMuestrasForIdUsuarioCreacion = catTipoMuestrasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatR7Inspeccion> getDatR7Inspeccions() {
        return this.datR7Inspeccions;
    }
    
    public void setDatR7Inspeccions(Set<DatR7Inspeccion> datR7Inspeccions) {
        this.datR7Inspeccions = datR7Inspeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatFormaMuestreo> getCatFormaMuestreosForIdUsuarioCreacion() {
        return this.catFormaMuestreosForIdUsuarioCreacion;
    }
    
    public void setCatFormaMuestreosForIdUsuarioCreacion(Set<CatFormaMuestreo> catFormaMuestreosForIdUsuarioCreacion) {
        this.catFormaMuestreosForIdUsuarioCreacion = catFormaMuestreosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatOrigen> getCatOrigensForIdUsuarioCreacion() {
        return this.catOrigensForIdUsuarioCreacion;
    }
    
    public void setCatOrigensForIdUsuarioCreacion(Set<CatOrigen> catOrigensForIdUsuarioCreacion) {
        this.catOrigensForIdUsuarioCreacion = catOrigensForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<DatR4Cabecera> getDatR4CabecerasForIdUsuarioCreacion() {
        return this.datR4CabecerasForIdUsuarioCreacion;
    }
    
    public void setDatR4CabecerasForIdUsuarioCreacion(Set<DatR4Cabecera> datR4CabecerasForIdUsuarioCreacion) {
        this.datR4CabecerasForIdUsuarioCreacion = datR4CabecerasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<LinkBoletinUsuario> getLinkBoletinUsuarios() {
        return this.linkBoletinUsuarios;
    }
    
    public void setLinkBoletinUsuarios(Set<LinkBoletinUsuario> linkBoletinUsuarios) {
        this.linkBoletinUsuarios = linkBoletinUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<DatR4Cabecera> getDatR4CabecerasForIdUsuarioEdicion() {
        return this.datR4CabecerasForIdUsuarioEdicion;
    }
    
    public void setDatR4CabecerasForIdUsuarioEdicion(Set<DatR4Cabecera> datR4CabecerasForIdUsuarioEdicion) {
        this.datR4CabecerasForIdUsuarioEdicion = datR4CabecerasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatLugarMuestreo> getCatLugarMuestreosForIdUsuarioCreacion() {
        return this.catLugarMuestreosForIdUsuarioCreacion;
    }
    
    public void setCatLugarMuestreosForIdUsuarioCreacion(Set<CatLugarMuestreo> catLugarMuestreosForIdUsuarioCreacion) {
        this.catLugarMuestreosForIdUsuarioCreacion = catLugarMuestreosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatEspecie> getCatEspeciesForIdUsuarioCreacion() {
        return this.catEspeciesForIdUsuarioCreacion;
    }
    
    public void setCatEspeciesForIdUsuarioCreacion(Set<CatEspecie> catEspeciesForIdUsuarioCreacion) {
        this.catEspeciesForIdUsuarioCreacion = catEspeciesForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatTipoPlanta> getCatTipoPlantasForIdUsuarioEdicion() {
        return this.catTipoPlantasForIdUsuarioEdicion;
    }
    
    public void setCatTipoPlantasForIdUsuarioEdicion(Set<CatTipoPlanta> catTipoPlantasForIdUsuarioEdicion) {
        this.catTipoPlantasForIdUsuarioEdicion = catTipoPlantasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatOrigen> getCatOrigensForIdUsuarioEdicion() {
        return this.catOrigensForIdUsuarioEdicion;
    }
    
    public void setCatOrigensForIdUsuarioEdicion(Set<CatOrigen> catOrigensForIdUsuarioEdicion) {
        this.catOrigensForIdUsuarioEdicion = catOrigensForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatFormaMuestreo> getCatFormaMuestreosForIdUsuarioEdicion() {
        return this.catFormaMuestreosForIdUsuarioEdicion;
    }
    
    public void setCatFormaMuestreosForIdUsuarioEdicion(Set<CatFormaMuestreo> catFormaMuestreosForIdUsuarioEdicion) {
        this.catFormaMuestreosForIdUsuarioEdicion = catFormaMuestreosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatTipoEnvase> getCatTipoEnvasesForIdUsuarioEdicion() {
        return this.catTipoEnvasesForIdUsuarioEdicion;
    }
    
    public void setCatTipoEnvasesForIdUsuarioEdicion(Set<CatTipoEnvase> catTipoEnvasesForIdUsuarioEdicion) {
        this.catTipoEnvasesForIdUsuarioEdicion = catTipoEnvasesForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatProblemasSupervision> getCatProblemasSupervisionsForIdUsuarioEdicion() {
        return this.catProblemasSupervisionsForIdUsuarioEdicion;
    }
    
    public void setCatProblemasSupervisionsForIdUsuarioEdicion(Set<CatProblemasSupervision> catProblemasSupervisionsForIdUsuarioEdicion) {
        this.catProblemasSupervisionsForIdUsuarioEdicion = catProblemasSupervisionsForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatR1Cabecera> getDatR1Cabeceras() {
        return this.datR1Cabeceras;
    }
    
    public void setDatR1Cabeceras(Set<DatR1Cabecera> datR1Cabeceras) {
        this.datR1Cabeceras = datR1Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatModalidad> getCatModalidadsForIdUsuarioEdicion() {
        return this.catModalidadsForIdUsuarioEdicion;
    }
    
    public void setCatModalidadsForIdUsuarioEdicion(Set<CatModalidad> catModalidadsForIdUsuarioEdicion) {
        this.catModalidadsForIdUsuarioEdicion = catModalidadsForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<LinkRolUsuario> getLinkRolUsuarios() {
        return this.linkRolUsuarios;
    }
    
    public void setLinkRolUsuarios(Set<LinkRolUsuario> linkRolUsuarios) {
        this.linkRolUsuarios = linkRolUsuarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatEquipoMuestreo> getCatEquipoMuestreosForIdUsuarioCreacion() {
        return this.catEquipoMuestreosForIdUsuarioCreacion;
    }
    
    public void setCatEquipoMuestreosForIdUsuarioCreacion(Set<CatEquipoMuestreo> catEquipoMuestreosForIdUsuarioCreacion) {
        this.catEquipoMuestreosForIdUsuarioCreacion = catEquipoMuestreosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatA5Cabecera> getDatA5Cabeceras() {
        return this.datA5Cabeceras;
    }
    
    public void setDatA5Cabeceras(Set<DatA5Cabecera> datA5Cabeceras) {
        this.datA5Cabeceras = datA5Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatCicloAgricola> getCatCicloAgricolasForIdUsuarioEdicion() {
        return this.catCicloAgricolasForIdUsuarioEdicion;
    }
    
    public void setCatCicloAgricolasForIdUsuarioEdicion(Set<CatCicloAgricola> catCicloAgricolasForIdUsuarioEdicion) {
        this.catCicloAgricolasForIdUsuarioEdicion = catCicloAgricolasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<LinkRolPermiso> getLinkRolPermisos() {
        return this.linkRolPermisos;
    }
    
    public void setLinkRolPermisos(Set<LinkRolPermiso> linkRolPermisos) {
        this.linkRolPermisos = linkRolPermisos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatModalidad> getCatModalidadsForIdUsuarioCreacion() {
        return this.catModalidadsForIdUsuarioCreacion;
    }
    
    public void setCatModalidadsForIdUsuarioCreacion(Set<CatModalidad> catModalidadsForIdUsuarioCreacion) {
        this.catModalidadsForIdUsuarioCreacion = catModalidadsForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatCicloAgricola> getCatCicloAgricolasForIdUsuarioCreacion() {
        return this.catCicloAgricolasForIdUsuarioCreacion;
    }
    
    public void setCatCicloAgricolasForIdUsuarioCreacion(Set<CatCicloAgricola> catCicloAgricolasForIdUsuarioCreacion) {
        this.catCicloAgricolasForIdUsuarioCreacion = catCicloAgricolasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatProblemasSupervision> getCatProblemasSupervisionsForIdUsuarioCreacion() {
        return this.catProblemasSupervisionsForIdUsuarioCreacion;
    }
    
    public void setCatProblemasSupervisionsForIdUsuarioCreacion(Set<CatProblemasSupervision> catProblemasSupervisionsForIdUsuarioCreacion) {
        this.catProblemasSupervisionsForIdUsuarioCreacion = catProblemasSupervisionsForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatTipoEnvase> getCatTipoEnvasesForIdUsuarioCreacion() {
        return this.catTipoEnvasesForIdUsuarioCreacion;
    }
    
    public void setCatTipoEnvasesForIdUsuarioCreacion(Set<CatTipoEnvase> catTipoEnvasesForIdUsuarioCreacion) {
        this.catTipoEnvasesForIdUsuarioCreacion = catTipoEnvasesForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<DatLaboratorioCabecera> getDatLaboratorioCabecerasForIdUsuarioCreacion() {
        return this.datLaboratorioCabecerasForIdUsuarioCreacion;
    }
    
    public void setDatLaboratorioCabecerasForIdUsuarioCreacion(Set<DatLaboratorioCabecera> datLaboratorioCabecerasForIdUsuarioCreacion) {
        this.datLaboratorioCabecerasForIdUsuarioCreacion = datLaboratorioCabecerasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatR7Cabecera> getDatR7Cabeceras() {
        return this.datR7Cabeceras;
    }
    
    public void setDatR7Cabeceras(Set<DatR7Cabecera> datR7Cabeceras) {
        this.datR7Cabeceras = datR7Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<DatLaboratorioCabecera> getDatLaboratorioCabecerasForIdUsuarioEdicion() {
        return this.datLaboratorioCabecerasForIdUsuarioEdicion;
    }
    
    public void setDatLaboratorioCabecerasForIdUsuarioEdicion(Set<DatLaboratorioCabecera> datLaboratorioCabecerasForIdUsuarioEdicion) {
        this.datLaboratorioCabecerasForIdUsuarioEdicion = datLaboratorioCabecerasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatSustrato> getCatSustratosForIdUsuarioEdicion() {
        return this.catSustratosForIdUsuarioEdicion;
    }
    
    public void setCatSustratosForIdUsuarioEdicion(Set<CatSustrato> catSustratosForIdUsuarioEdicion) {
        this.catSustratosForIdUsuarioEdicion = catSustratosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatActividadesOrganismo> getCatActividadesOrganismosForIdUsuarioCreacion() {
        return this.catActividadesOrganismosForIdUsuarioCreacion;
    }
    
    public void setCatActividadesOrganismosForIdUsuarioCreacion(Set<CatActividadesOrganismo> catActividadesOrganismosForIdUsuarioCreacion) {
        this.catActividadesOrganismosForIdUsuarioCreacion = catActividadesOrganismosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatActividadesOrganismo> getCatActividadesOrganismosForIdUsuarioEdicion() {
        return this.catActividadesOrganismosForIdUsuarioEdicion;
    }
    
    public void setCatActividadesOrganismosForIdUsuarioEdicion(Set<CatActividadesOrganismo> catActividadesOrganismosForIdUsuarioEdicion) {
        this.catActividadesOrganismosForIdUsuarioEdicion = catActividadesOrganismosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatSustrato> getCatSustratosForIdUsuarioCreacion() {
        return this.catSustratosForIdUsuarioCreacion;
    }
    
    public void setCatSustratosForIdUsuarioCreacion(Set<CatSustrato> catSustratosForIdUsuarioCreacion) {
        this.catSustratosForIdUsuarioCreacion = catSustratosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatOrganismo> getDatOrganismos() {
        return this.datOrganismos;
    }
    
    public void setDatOrganismos(Set<DatOrganismo> datOrganismos) {
        this.datOrganismos = datOrganismos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatCondicionCultivo> getCatCondicionCultivosForIdUsuarioEdicion() {
        return this.catCondicionCultivosForIdUsuarioEdicion;
    }
    
    public void setCatCondicionCultivosForIdUsuarioEdicion(Set<CatCondicionCultivo> catCondicionCultivosForIdUsuarioEdicion) {
        this.catCondicionCultivosForIdUsuarioEdicion = catCondicionCultivosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatR1Inspeccion> getDatR1Inspeccions() {
        return this.datR1Inspeccions;
    }
    
    public void setDatR1Inspeccions(Set<DatR1Inspeccion> datR1Inspeccions) {
        this.datR1Inspeccions = datR1Inspeccions;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatTipoDomicilio> getCatTipoDomiciliosForIdUsuarioCreacion() {
        return this.catTipoDomiciliosForIdUsuarioCreacion;
    }
    
    public void setCatTipoDomiciliosForIdUsuarioCreacion(Set<CatTipoDomicilio> catTipoDomiciliosForIdUsuarioCreacion) {
        this.catTipoDomiciliosForIdUsuarioCreacion = catTipoDomiciliosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuario")
    public Set<DatR5Cabecera> getDatR5Cabeceras() {
        return this.datR5Cabeceras;
    }
    
    public void setDatR5Cabeceras(Set<DatR5Cabecera> datR5Cabeceras) {
        this.datR5Cabeceras = datR5Cabeceras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatTipoPlanta> getCatTipoPlantasForIdUsuarioCreacion() {
        return this.catTipoPlantasForIdUsuarioCreacion;
    }
    
    public void setCatTipoPlantasForIdUsuarioCreacion(Set<CatTipoPlanta> catTipoPlantasForIdUsuarioCreacion) {
        this.catTipoPlantasForIdUsuarioCreacion = catTipoPlantasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatEspecie> getCatEspeciesForIdUsuarioEdicion() {
        return this.catEspeciesForIdUsuarioEdicion;
    }
    
    public void setCatEspeciesForIdUsuarioEdicion(Set<CatEspecie> catEspeciesForIdUsuarioEdicion) {
        this.catEspeciesForIdUsuarioEdicion = catEspeciesForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatLugarMuestreo> getCatLugarMuestreosForIdUsuarioEdicion() {
        return this.catLugarMuestreosForIdUsuarioEdicion;
    }
    
    public void setCatLugarMuestreosForIdUsuarioEdicion(Set<CatLugarMuestreo> catLugarMuestreosForIdUsuarioEdicion) {
        this.catLugarMuestreosForIdUsuarioEdicion = catLugarMuestreosForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatCondicionCultivo> getCatCondicionCultivosForIdUsuarioCreacion() {
        return this.catCondicionCultivosForIdUsuarioCreacion;
    }
    
    public void setCatCondicionCultivosForIdUsuarioCreacion(Set<CatCondicionCultivo> catCondicionCultivosForIdUsuarioCreacion) {
        this.catCondicionCultivosForIdUsuarioCreacion = catCondicionCultivosForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatCategoria> getCatCategoriasForIdUsuarioCreacion() {
        return this.catCategoriasForIdUsuarioCreacion;
    }
    
    public void setCatCategoriasForIdUsuarioCreacion(Set<CatCategoria> catCategoriasForIdUsuarioCreacion) {
        this.catCategoriasForIdUsuarioCreacion = catCategoriasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioCreacion")
    public Set<CatUnidadMedida> getCatUnidadMedidasForIdUsuarioCreacion() {
        return this.catUnidadMedidasForIdUsuarioCreacion;
    }
    
    public void setCatUnidadMedidasForIdUsuarioCreacion(Set<CatUnidadMedida> catUnidadMedidasForIdUsuarioCreacion) {
        this.catUnidadMedidasForIdUsuarioCreacion = catUnidadMedidasForIdUsuarioCreacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatUnidadMedida> getCatUnidadMedidasForIdUsuarioEdicion() {
        return this.catUnidadMedidasForIdUsuarioEdicion;
    }
    
    public void setCatUnidadMedidasForIdUsuarioEdicion(Set<CatUnidadMedida> catUnidadMedidasForIdUsuarioEdicion) {
        this.catUnidadMedidasForIdUsuarioEdicion = catUnidadMedidasForIdUsuarioEdicion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="datUsuarioByIdUsuarioEdicion")
    public Set<CatCategoria> getCatCategoriasForIdUsuarioEdicion() {
        return this.catCategoriasForIdUsuarioEdicion;
    }
    
    public void setCatCategoriasForIdUsuarioEdicion(Set<CatCategoria> catCategoriasForIdUsuarioEdicion) {
        this.catCategoriasForIdUsuarioEdicion = catCategoriasForIdUsuarioEdicion;
    }




}


