package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkOrganismoCultivoId generated by hbm2java
 */
@Embeddable
public class LinkOrganismoCultivoId  implements java.io.Serializable {


     private int idOrganismo;
     private int idCultivo;

    public LinkOrganismoCultivoId() {
    }

    public LinkOrganismoCultivoId(int idOrganismo, int idCultivo) {
       this.idOrganismo = idOrganismo;
       this.idCultivo = idCultivo;
    }
   


    @Column(name="Id_Organismo", nullable=false)
    public int getIdOrganismo() {
        return this.idOrganismo;
    }
    
    public void setIdOrganismo(int idOrganismo) {
        this.idOrganismo = idOrganismo;
    }


    @Column(name="Id_Cultivo", nullable=false)
    public int getIdCultivo() {
        return this.idCultivo;
    }
    
    public void setIdCultivo(int idCultivo) {
        this.idCultivo = idCultivo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkOrganismoCultivoId) ) return false;
		 LinkOrganismoCultivoId castOther = ( LinkOrganismoCultivoId ) other; 
         
		 return (this.getIdOrganismo()==castOther.getIdOrganismo())
 && (this.getIdCultivo()==castOther.getIdCultivo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOrganismo();
         result = 37 * result + this.getIdCultivo();
         return result;
   }   


}


