package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkBoletinUsuario generated by hbm2java
 */
@Entity
@Table(name="Link_Boletin_Usuario"
    ,catalog="sisem"
)
public class LinkBoletinUsuario  implements java.io.Serializable {


     private LinkBoletinUsuarioId id;
     private DatUsuario datUsuario;
     private DatBoletin datBoletin;
     private boolean status;

    public LinkBoletinUsuario() {
    }

    public LinkBoletinUsuario(LinkBoletinUsuarioId id, DatUsuario datUsuario, DatBoletin datBoletin, boolean status) {
       this.id = id;
       this.datUsuario = datUsuario;
       this.datBoletin = datBoletin;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idBoletin", column=@Column(name="Id_Boletin", nullable=false) ), 
        @AttributeOverride(name="idUsuario", column=@Column(name="Id_Usuario", nullable=false) ) } )
    public LinkBoletinUsuarioId getId() {
        return this.id;
    }
    
    public void setId(LinkBoletinUsuarioId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario", nullable=false, insertable=false, updatable=false)
    public DatUsuario getDatUsuario() {
        return this.datUsuario;
    }
    
    public void setDatUsuario(DatUsuario datUsuario) {
        this.datUsuario = datUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Boletin", nullable=false, insertable=false, updatable=false)
    public DatBoletin getDatBoletin() {
        return this.datBoletin;
    }
    
    public void setDatBoletin(DatBoletin datBoletin) {
        this.datBoletin = datBoletin;
    }

    
    @Column(name="Status", nullable=false)
    public boolean isStatus() {
        return this.status;
    }
    
    public void setStatus(boolean status) {
        this.status = status;
    }




}


