package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkRolPermisoId generated by hbm2java
 */
@Embeddable
public class LinkRolPermisoId  implements java.io.Serializable {


     private int idPermiso;
     private int idRol;

    public LinkRolPermisoId() {
    }

    public LinkRolPermisoId(int idPermiso, int idRol) {
       this.idPermiso = idPermiso;
       this.idRol = idRol;
    }
   


    @Column(name="Id_Permiso", nullable=false)
    public int getIdPermiso() {
        return this.idPermiso;
    }
    
    public void setIdPermiso(int idPermiso) {
        this.idPermiso = idPermiso;
    }


    @Column(name="Id_Rol", nullable=false)
    public int getIdRol() {
        return this.idRol;
    }
    
    public void setIdRol(int idRol) {
        this.idRol = idRol;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkRolPermisoId) ) return false;
		 LinkRolPermisoId castOther = ( LinkRolPermisoId ) other; 
         
		 return (this.getIdPermiso()==castOther.getIdPermiso())
 && (this.getIdRol()==castOther.getIdRol());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPermiso();
         result = 37 * result + this.getIdRol();
         return result;
   }   


}


