package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LinkRolPermiso generated by hbm2java
 */
@Entity
@Table(name="Link_Rol_Permiso"
    ,catalog="sisem"
)
public class LinkRolPermiso  implements java.io.Serializable {


     private LinkRolPermisoId id;
     private CatRol catRol;
     private DatUsuario datUsuario;
     private CatPermiso catPermiso;
     private Date fechaCreacion;

    public LinkRolPermiso() {
    }

    public LinkRolPermiso(LinkRolPermisoId id, CatRol catRol, DatUsuario datUsuario, CatPermiso catPermiso, Date fechaCreacion) {
       this.id = id;
       this.catRol = catRol;
       this.datUsuario = datUsuario;
       this.catPermiso = catPermiso;
       this.fechaCreacion = fechaCreacion;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idPermiso", column=@Column(name="Id_Permiso", nullable=false) ), 
        @AttributeOverride(name="idRol", column=@Column(name="Id_Rol", nullable=false) ) } )
    public LinkRolPermisoId getId() {
        return this.id;
    }
    
    public void setId(LinkRolPermisoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Rol", nullable=false, insertable=false, updatable=false)
    public CatRol getCatRol() {
        return this.catRol;
    }
    
    public void setCatRol(CatRol catRol) {
        this.catRol = catRol;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Usuario_Creacion", nullable=false)
    public DatUsuario getDatUsuario() {
        return this.datUsuario;
    }
    
    public void setDatUsuario(DatUsuario datUsuario) {
        this.datUsuario = datUsuario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Permiso", nullable=false, insertable=false, updatable=false)
    public CatPermiso getCatPermiso() {
        return this.catPermiso;
    }
    
    public void setCatPermiso(CatPermiso catPermiso) {
        this.catPermiso = catPermiso;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Fecha_Creacion", nullable=false, length=19)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }




}


