package mx.com.sagarpa.snics.persistence.entities;
// Generated 23/12/2015 02:01:48 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkRolUsuarioUnidadSnics generated by hbm2java
 */
@Entity
@Table(name="Link_Rol_Usuario_Unidad_Snics"
    ,catalog="sisem"
)
public class LinkRolUsuarioUnidadSnics  implements java.io.Serializable {


     private LinkRolUsuarioUnidadSnicsId id;
     private CatUnidadSnics catUnidadSnics;

    public LinkRolUsuarioUnidadSnics() {
    }

    public LinkRolUsuarioUnidadSnics(LinkRolUsuarioUnidadSnicsId id, CatUnidadSnics catUnidadSnics) {
       this.id = id;
       this.catUnidadSnics = catUnidadSnics;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idRolUsuario", column=@Column(name="Id_Rol_Usuario", nullable=false) ), 
        @AttributeOverride(name="idUnidadSnics", column=@Column(name="Id_Unidad_Snics", nullable=false) ) } )
    public LinkRolUsuarioUnidadSnicsId getId() {
        return this.id;
    }
    
    public void setId(LinkRolUsuarioUnidadSnicsId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Snics", nullable=false, insertable=false, updatable=false)
    public CatUnidadSnics getCatUnidadSnics() {
        return this.catUnidadSnics;
    }
    
    public void setCatUnidadSnics(CatUnidadSnics catUnidadSnics) {
        this.catUnidadSnics = catUnidadSnics;
    }




}


