package mx.com.sagarpa.snics.persistence.entities;
// Generated 18/12/2015 02:58:23 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkOrganismoActividades generated by hbm2java
 */
@Entity
@Table(name="Link_Organismo_Actividades"
    ,catalog="sisem"
)
public class LinkOrganismoActividades  implements java.io.Serializable {


     private LinkOrganismoActividadesId id;
     private DatOrganismo datOrganismo;
     private CatActividadesOrganismo catActividadesOrganismo;

    public LinkOrganismoActividades() {
    }

    public LinkOrganismoActividades(LinkOrganismoActividadesId id, DatOrganismo datOrganismo, CatActividadesOrganismo catActividadesOrganismo) {
       this.id = id;
       this.datOrganismo = datOrganismo;
       this.catActividadesOrganismo = catActividadesOrganismo;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOrganismo", column=@Column(name="Id_Organismo", nullable=false) ), 
        @AttributeOverride(name="idActividadesOrganismo", column=@Column(name="Id_Actividades_Organismo", nullable=false) ) } )
    public LinkOrganismoActividadesId getId() {
        return this.id;
    }
    
    public void setId(LinkOrganismoActividadesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo", nullable=false, insertable=false, updatable=false)
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Actividades_Organismo", nullable=false, insertable=false, updatable=false)
    public CatActividadesOrganismo getCatActividadesOrganismo() {
        return this.catActividadesOrganismo;
    }
    
    public void setCatActividadesOrganismo(CatActividadesOrganismo catActividadesOrganismo) {
        this.catActividadesOrganismo = catActividadesOrganismo;
    }




}


