package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkMovimientoEtiquetasSnicsId generated by hbm2java
 */
@Embeddable
public class LinkMovimientoEtiquetasSnicsId  implements java.io.Serializable {


     private int idMovimientoEtiquetas;
     private int idUnidadSnicsEntrega;

    public LinkMovimientoEtiquetasSnicsId() {
    }

    public LinkMovimientoEtiquetasSnicsId(int idMovimientoEtiquetas, int idUnidadSnicsEntrega) {
       this.idMovimientoEtiquetas = idMovimientoEtiquetas;
       this.idUnidadSnicsEntrega = idUnidadSnicsEntrega;
    }
   


    @Column(name="Id_Movimiento_Etiquetas", nullable=false)
    public int getIdMovimientoEtiquetas() {
        return this.idMovimientoEtiquetas;
    }
    
    public void setIdMovimientoEtiquetas(int idMovimientoEtiquetas) {
        this.idMovimientoEtiquetas = idMovimientoEtiquetas;
    }


    @Column(name="Id_Unidad_Snics_entrega", nullable=false)
    public int getIdUnidadSnicsEntrega() {
        return this.idUnidadSnicsEntrega;
    }
    
    public void setIdUnidadSnicsEntrega(int idUnidadSnicsEntrega) {
        this.idUnidadSnicsEntrega = idUnidadSnicsEntrega;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkMovimientoEtiquetasSnicsId) ) return false;
		 LinkMovimientoEtiquetasSnicsId castOther = ( LinkMovimientoEtiquetasSnicsId ) other; 
         
		 return (this.getIdMovimientoEtiquetas()==castOther.getIdMovimientoEtiquetas())
 && (this.getIdUnidadSnicsEntrega()==castOther.getIdUnidadSnicsEntrega());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMovimientoEtiquetas();
         result = 37 * result + this.getIdUnidadSnicsEntrega();
         return result;
   }   


}


