package mx.com.sagarpa.snics.persistence.entities;
// Generated 18/12/2015 02:58:23 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LinkOrganismoActividadesId generated by hbm2java
 */
@Embeddable
public class LinkOrganismoActividadesId  implements java.io.Serializable {


     private int idOrganismo;
     private int idActividadesOrganismo;

    public LinkOrganismoActividadesId() {
    }

    public LinkOrganismoActividadesId(int idOrganismo, int idActividadesOrganismo) {
       this.idOrganismo = idOrganismo;
       this.idActividadesOrganismo = idActividadesOrganismo;
    }
   


    @Column(name="Id_Organismo", nullable=false)
    public int getIdOrganismo() {
        return this.idOrganismo;
    }
    
    public void setIdOrganismo(int idOrganismo) {
        this.idOrganismo = idOrganismo;
    }


    @Column(name="Id_Actividades_Organismo", nullable=false)
    public int getIdActividadesOrganismo() {
        return this.idActividadesOrganismo;
    }
    
    public void setIdActividadesOrganismo(int idActividadesOrganismo) {
        this.idActividadesOrganismo = idActividadesOrganismo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LinkOrganismoActividadesId) ) return false;
		 LinkOrganismoActividadesId castOther = ( LinkOrganismoActividadesId ) other; 
         
		 return (this.getIdOrganismo()==castOther.getIdOrganismo())
 && (this.getIdActividadesOrganismo()==castOther.getIdActividadesOrganismo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOrganismo();
         result = 37 * result + this.getIdActividadesOrganismo();
         return result;
   }   


}


