package mx.com.sagarpa.snics.persistence.entities;
// Generated 30/12/2015 05:02:20 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LinkOrganismoCultivo generated by hbm2java
 */
@Entity
@Table(name="Link_Organismo_Cultivo"
    ,catalog="sisem"
)
public class LinkOrganismoCultivo  implements java.io.Serializable {


     private LinkOrganismoCultivoId id;
     private CatUnidadMedida catUnidadMedida;
     private CatCultivo catCultivo;
     private CatTipoCultivo catTipoCultivo;
     private DatOrganismo datOrganismo;
     private CatCategoria catCategoria;
     private int idOrganismoCultivo;
     private int cantidad;

    public LinkOrganismoCultivo() {
    }

    public LinkOrganismoCultivo(LinkOrganismoCultivoId id, CatUnidadMedida catUnidadMedida, CatCultivo catCultivo, CatTipoCultivo catTipoCultivo, DatOrganismo datOrganismo, CatCategoria catCategoria, int idOrganismoCultivo, int cantidad) {
       this.id = id;
       this.catUnidadMedida = catUnidadMedida;
       this.catCultivo = catCultivo;
       this.catTipoCultivo = catTipoCultivo;
       this.datOrganismo = datOrganismo;
       this.catCategoria = catCategoria;
       this.idOrganismoCultivo = idOrganismoCultivo;
       this.cantidad = cantidad;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idOrganismo", column=@Column(name="Id_Organismo", nullable=false) ), 
        @AttributeOverride(name="idCultivo", column=@Column(name="Id_Cultivo", nullable=false) ) } )
    public LinkOrganismoCultivoId getId() {
        return this.id;
    }
    
    public void setId(LinkOrganismoCultivoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Unidad_Medida", nullable=false)
    public CatUnidadMedida getCatUnidadMedida() {
        return this.catUnidadMedida;
    }
    
    public void setCatUnidadMedida(CatUnidadMedida catUnidadMedida) {
        this.catUnidadMedida = catUnidadMedida;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Cultivo", nullable=false, insertable=false, updatable=false)
    public CatCultivo getCatCultivo() {
        return this.catCultivo;
    }
    
    public void setCatCultivo(CatCultivo catCultivo) {
        this.catCultivo = catCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Tipo_Cultivo", nullable=false)
    public CatTipoCultivo getCatTipoCultivo() {
        return this.catTipoCultivo;
    }
    
    public void setCatTipoCultivo(CatTipoCultivo catTipoCultivo) {
        this.catTipoCultivo = catTipoCultivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Organismo", nullable=false, insertable=false, updatable=false)
    public DatOrganismo getDatOrganismo() {
        return this.datOrganismo;
    }
    
    public void setDatOrganismo(DatOrganismo datOrganismo) {
        this.datOrganismo = datOrganismo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Id_Categoria", nullable=false)
    public CatCategoria getCatCategoria() {
        return this.catCategoria;
    }
    
    public void setCatCategoria(CatCategoria catCategoria) {
        this.catCategoria = catCategoria;
    }

    
    @Column(name="Id_Organismo_Cultivo", nullable=false)
    public int getIdOrganismoCultivo() {
        return this.idOrganismoCultivo;
    }
    
    public void setIdOrganismoCultivo(int idOrganismoCultivo) {
        this.idOrganismoCultivo = idOrganismoCultivo;
    }

    
    @Column(name="Cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


