package mx.com.sagarpa.snics.persistence.entities;
// Generated 15/12/2015 02:32:28 PM by Hibernate Tools 3.2.4.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prueba generated by hbm2java
 */
@Entity
@Table(name="prueba"
    ,catalog="sisem"
)
public class Prueba  implements java.io.Serializable {


     private Integer idprueba;

    public Prueba() {
    }

   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprueba", unique=true, nullable=false)
    public Integer getIdprueba() {
        return this.idprueba;
    }
    
    public void setIdprueba(Integer idprueba) {
        this.idprueba = idprueba;
    }




}


